feat: update earn table
shapeshift/web pull request #1031
Opened 2022-02-16 16:58 UTC by reallybeard

## Description

- Reworked earn table to include more data
- Added an asset teaser popover
- Updated the latest version of framer-motion to fix a bug in the older version

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

## Risk

Outline the scope of your changes and the risk associated with them. You must use your discretion as an engineer to determine the potential impact of your changes.

E.g. an upgrade to `hdwallet` or core state management would be considered higher risk, and might require a full regression test. UI or isolated view changes, or something behind a feature flag may have near zero risk. Small bug fixes might require testing isolated to the specific fix.

## Testing

If your testing steps are technical, outline steps for an engineer to verify.

If your testing steps are functional, please provide a full guide with any features requiring special attention for operations to test your branch in the preview environment.

## Screenshots (if applicable)
![Screen Shot 2022-02-16 at 10 56 24 AM](https://user-images.githubusercontent.com/89934888/154316406-d921fa27-ee35-409f-9889-3d04bef72156.png)
![Screen Shot 2022-02-16 at 10 56 36 AM](https://user-images.githubusercontent.com/89934888/154316408-c41eebb0-2342-40fa-9a85-749556759166.png)
![Screen Shot 2022-02-16 at 10 56 48 AM](https://user-images.githubusercontent.com/89934888/154316413-8ede34d8-33d3-4711-873b-8ece244341dd.png)

2022-02-16 20:48 UTC, 0xdef1cafe requested changes
visually looks good but code changes required

2022-02-16 20:48 UTC, 0xdef1cafe commented on src/components/StakingVaults/EarnOpportunityRow.tsx
> +  }
```suggestion
  const handleOnMouseLeave = debouncedHandleMouseEnter.cancel
```

2022-02-16 21:26 UTC, reallybeard commented on src/components/StakingVaults/EarnOpportunities.tsx
> +            {vaults.map((vault, index) => (
The second part I think is a little out of scope of this, the yearn vaults need to be re-worked to allow this to happen.

2022-02-16 21:28 UTC, reallybeard commented on src/components/StakingVaults/AssetTeaser.tsx
> +    if (tokenId) baseUrl = baseUrl + `/${tokenId}`
This follows the pattern we established with the AccountRow component.

2022-02-22 17:45 UTC, 0xdef1cafe requested changes

2022-02-22 17:45 UTC, 0xdef1cafe commented on package.json
> +    "framer-motion": "4.1.16",
```suggestion
    "framer-motion": "^4.1.16",
```

2022-02-22 18:06 UTC, 0xdef1cafe approved these changes

2022-02-22 18:07 UTC, DaoDev44 approved these changes

2022-02-22 18:08 UTC, 0xdef1cafe approved these changes

2022-02-22 18:08 UTC, merged