Terms of Service and Privacy Policy
shapeshift/web pull request #1053
Opened 2022-02-22 14:02 UTC by ufe-pr

## Description

I added 2 new pages to the app, Terms of Service and Privacy Policy.
Corresponding links were also included in the Connect Wallet Page and the User Menu drop-down with appropriate styling.

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue

https://github.com/shapeshift/web/issues/963

## Risk

Possibly https://github.com/shapeshift/web/issues/963#issuecomment-1047050272

## Testing

## Screenshots

The Connect Wallet Page showing the links to the Privacy Policy and Terms of Service
![localhost_3000_connect-wallet_returnUrl=_accounts](https://user-images.githubusercontent.com/53881516/154758046-c2af4aa8-f85b-47d5-97af-dfb620428a80.png)

The Terms of Service Page
![localhost_3000_legal_terms-of-service](https://user-images.githubusercontent.com/53881516/154758055-fc4a43f8-a0e5-4231-8f1d-8cbd1264471e.png)

The User Menu showing the links to the Privacy Policy and Terms of Service
![localhost_3000_legal_terms-of-service (1)](https://user-images.githubusercontent.com/53881516/154758071-96c13b44-dd9f-471d-a717-67b4930067c8.png)

The Privacy Policy Page
![localhost_3000_legal_terms-of-service (2)](https://user-images.githubusercontent.com/53881516/154758079-8c76608f-86de-4928-a8d8-4dfa1961f4b1.png)

2022-02-23 02:37 UTC, cjthompson commented
These screenshots show a lot of weird formatting issues especially regarding spaces (either lack of spaces after punctuation or additional spaces inside quotes where there shouldn't be).

2022-02-23 14:09 UTC, ufe-pr commented
> These screenshots show a lot of weird formatting issues especially regarding spaces (either lack of spaces after punctuation or additional spaces inside quotes where there shouldn't be).
> 
> ![image](https://user-images.githubusercontent.com/1958266/155253135-3bac6883-d6c2-438a-9dd9-40ed600a8e4d.png) ![image](https://user-images.githubusercontent.com/1958266/155253154-3882487a-f239-436d-bc99-4657843cd88b.png) ![image](https://user-images.githubusercontent.com/1958266/155253209-41598173-d952-4ada-95b4-71afda22ed46.png)


I've fixed the formatting issues and created a new commit.

![localhost_3000_legal_terms-of-service (5)](https://user-images.githubusercontent.com/53881516/155334812-0bf50fde-eaa6-4b3b-9918-897b44ab3619.png)

![localhost_3000_legal_terms-of-service (4)](https://user-images.githubusercontent.com/53881516/155335553-27986f52-dc4b-4e89-8ac2-6003329e22ab.png)

2022-02-23 18:24 UTC, 0xdef1cafe requested changes
various formatting changes, and a request to remove a section that is not yet relevant, that IMO should be included at a later date, but IANAL

2022-02-23 18:24 UTC, 0xdef1cafe commented on src/pages/Legal/TermsOfService.tsx
> +            DECENTRALIZED AUTONOMOUS ORGANIZATION (WHO WE REFER TO IN HE FIRST PERSON IN THESE
```suggestion
            DECENTRALIZED AUTONOMOUS ORGANIZATION (WHO WE REFER TO IN THE FIRST PERSON IN THESE
```

2022-02-23 18:24 UTC, 0xdef1cafe commented on src/pages/Legal/TermsOfService.tsx
> +            CONDITION BEFORE BUYING OR SELLING SUCH CRYPTOCURRENCY. Ok…thanks for bearing with us
```suggestion
            CONDITION BEFORE BUYING OR SELLING SUCH CRYPTOCURRENCY. Ok… thanks for bearing with us
```

2022-02-23 18:24 UTC, 0xdef1cafe commented on src/pages/Legal/TermsOfService.tsx
> +              into such value as is listed on the Platform.YOU ARE RESPONSIBLE FOR CONFIRMING AN
```suggestion
              into such value as is listed on the Platform. YOU ARE RESPONSIBLE FOR CONFIRMING AN
```

2022-02-23 18:24 UTC, 0xdef1cafe commented on src/pages/Legal/TermsOfService.tsx
> +            <RawText as='strong'>Alpha Platform:</RawText> We have made available an alternate
IMO, this entire section regarding `alpha.shapeshift.com` should be removed until it's hosted, and references to the mobile apps should be removed until we host an open source version of the apps, as the current versions are not hosted via the DAO, and we should not blur any lines there.

2022-02-23 18:24 UTC, 0xdef1cafe commented on src/pages/Legal/TermsOfService.tsx
> +            shareholders, employees, and to fund us as a DAO. FOX Tokens used as governance tokens
```suggestion
            shareholders, employees, and to fund us as a DAO. FOX Tokens are used as governance tokens
```

2022-02-23 18:24 UTC, 0xdef1cafe commented on src/pages/Legal/TermsOfService.tsx
> +              <RawText as='strong'>here</RawText>
add space after here

2022-02-23 18:24 UTC, 0xdef1cafe commented on src/pages/Legal/TermsOfService.tsx
> +            <RawText as='strong'>Disclaimer of Warranties:</RawText> As we pointed out,the Platform
```suggestion
            <RawText as='strong'>Disclaimer of Warranties:</RawText> As we pointed out, the Platform
```

2022-02-23 18:30 UTC, 0xdef1cafe requested changes
more formatting changes

2022-02-23 18:30 UTC, 0xdef1cafe commented on src/pages/Legal/PrivacyPolicy.tsx
> +              <RawText as='strong'>here</RawText>
add full stop after here

2022-02-23 18:30 UTC, 0xdef1cafe commented on src/pages/Legal/PrivacyPolicy.tsx
> +              <RawText as='strong'>here</RawText>
add space after here

2022-02-25 01:32 UTC, ufe-pr commented
@0xdef1cafe I'm about to implement the suggested changes. Should I also remove the sections concerning the alpha platform and mobile apps?

2022-02-25 16:42 UTC, 0xdef1cafe commented
hey @ufe-pr - thanks for following up. after speaking with the lawyer that drafted this, please remove all references to

* mobile apps
* alpha.shapeshift.com
* pendo

we'll add these sections when they're ready and relevant

2022-02-28 15:37 UTC, 0xdef1cafe commented
hey @ufe-pr - are you able to action the requested changes please?

2022-03-01 07:25 UTC, ufe-pr commented
hi @0xdef1cafe
I've implemented the changes. Please review.

2022-03-01 23:16 UTC, 0xdef1cafe commented
hey @ufe-pr thanks for the PR - we're going to consider this done, fix the merge conflicts in https://github.com/shapeshift/web/pull/1093 and get it merged

2022-03-01 23:16 UTC, closed without merging