feat: no msw in production builds
shapeshift/web pull request #1078
Opened 2022-02-28 10:36 UTC by chxash

## Description

Fix for https://github.com/shapeshift/web/issues/840

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [X] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [X] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

 https://github.com/shapeshift/web/issues/840

## Risk

There should be no impact.

## Testing

For testing this, I verified that MSW was still effective even after removing the .js file in public directory.
To do that, I commented network mocks (jest.mock) in setupGlobalMocks.ts and verified that MSW was still capturing any network call during unit tests.

## Screenshots (if applicable)

2022-02-28 15:32 UTC, 0xdef1cafe requested changes
thanks for this - just requesting we don't modify the `yarn.lock` file in this PR as it seems unrelated?

2022-02-28 17:29 UTC, theoboldfrazier commented on yarn.lock
> +"@types/history@^4.7.11":
This change looks to be in develop already. The github diff is off.

2022-02-28 18:12 UTC, 0xdef1cafe commented on yarn.lock
> +"@types/history@^4.7.11":
ok cool, in that case @chxash can you please rebase off develop?

2022-03-01 09:03 UTC, chxash commented
> thanks for this - just requesting we don't modify the `yarn.lock` file in this PR as it seems unrelated?

Done ! Sorry for this

2022-03-01 09:03 UTC, chxash commented on yarn.lock
> +"@types/history@^4.7.11":
done !

2022-03-01 16:06 UTC, 0xdef1cafe approved these changes

2022-03-01 17:34 UTC, gomesalexandre approved these changes

2022-03-01 17:41 UTC, merged