feat: add cypress-autorecord to mock requests
shapeshift/web pull request #1191
Opened 2022-03-17 14:47 UTC by codinglittlecat

## Description

- add cypress-autorecord (https://github.com/Nanciee/cypress-autorecord)
## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
This PR closes #1103

2022-03-18 01:25 UTC, 0xdef1cafe commented
@0xApotheosis structurally looks great to me, if it meets your requirements it gets my stamp

2022-03-18 01:37 UTC, 0xApotheosis commented
Thanks @codinglittlecat! I'll take a look at this in the next 24 hours 👌

2022-03-18 01:42 UTC, 0xApotheosis commented
@codinglittlecat at first glance, we don't seem to have the mocked responses committed to version control.

Are you able to run `cypress-autorecord` and do this, please?

2022-03-18 04:57 UTC, codinglittlecat commented
@0xApotheosis mock datat is generated automatically when you run `yarn cypress:test`

2022-03-18 20:52 UTC, 0xApotheosis requested changes
At the moment we are regenerating all of the mocks every time `yarn test:cypress` is run. This is triggered by the `autoRecord()` added to the beginning of our tests.

Instead, in this PR we want to commit the generated tests, but not re-generate them every time. So, we can remove `autoRecord()` from the tests, and update `cypress.json` with:

```ts
"autorecord": {
  "forceRecord": false
}
```

We'll also want to clean our tests after each run by adding:

```ts
"cleanMocks": true
```

And update the README to include instructions on adding mock data to new tests, e.g. using:

```ts
 "recordTests": ["new test"]
```

2022-03-18 20:52 UTC, 0xApotheosis commented on cypress/README.md
> +```js
As we use Typescript, can you update this to `ts` and update the code style to match our lint? E.g. remove `;`.

2022-03-18 20:52 UTC, 0xApotheosis commented on cypress/README.md
> +  autoRecord(); // Call the autoRecord function at the beginning of your describe block
We don't actually want to call this every time - only initially to get the mocks and commit them to version control.

2022-03-18 20:52 UTC, 0xApotheosis commented on cypress/support/index.ts
> +Cypress.on('window:before:load', win => {
Can you please add a comment on what this does/why it is needed?

2022-03-18 20:57 UTC, 0xApotheosis requested changes
A few more things to fix:

- The "nav bar works" test doesn't seem to be using the mocks
- Running all tests at once generates a new set of mock files under a `All Integration Specs` label - we'll need to commit these mocks to version control, too
- When running the tests with the mocks we get a number of exceptions, causing the tests to fail - this might be something to do with the speed that the tests now run at. We'll need to find a solution for these

2022-03-18 20:59 UTC, 0xApotheosis commented
Otherwise, we are looking good @codinglittlecat - the tests do run a lot faster with these mocks in place! Nice work.

2022-03-20 22:49 UTC, 0xApotheosis requested changes
Thanks for the updates @codinglittlecat!

This is still not quite right. When I checkout this branch, run `yarn test:cypress`, and run all integration tests, the committed mocks are not used.

It might be the case that we need to use `autoRecord()` in each test, but then disable it in the config, I'm not sure.

I also suspect the mocks we want committed are the ones generated when _all_ tests are run (which I suspect will stored under `cypress/mocks/All Integration Specs.json`) - at the moment it seems like you're generating the mocks by running each set of tests individually - but as the CI pipeline runs them all at once, we'll want to match this behaviour.

In the screenshot below, it shows that the mocks are still being modified after I made some tweaks to get it using them again (perhaps `"forceRecord": false` didn't have the effect we thought it would).

<img width="861" alt="Screen Shot 2022-03-21 at 9 32 03 am" src="https://user-images.githubusercontent.com/97164662/159188822-02e81da0-42af-43a8-8878-7ace59d96545.png">

Also, the `nav bar works` test is still not being mocked, even when using the mocks committed under `mocks/dashboard_spec.json`. See screenshot below:

<img width="900" alt="Screen Shot 2022-03-21 at 9 39 58 am" src="https://user-images.githubusercontent.com/97164662/159189115-b51b4260-3056-4d79-9d37-df959a9d0126.png">
 
In summary:

- Commit the mocks generated when _all_ tests are run, and remove the rest
- Ensure that the PR is in a state such that when it is checked out, and `yarn cypress:run` is run locally, no mocks are modified - it should use the committed mocks
- Ensure we have a _working_ mechanism (ideally a flag) to update mocks in the future, and to clear out stale any mocks
- Ensure all requests are mocked (e.g. those in "nav bar works")

Please request another review when you are happy that these requirements are met, or reach out to me on Discord with any questions 😊

2022-03-24 19:39 UTC, 0xApotheosis commented
@codinglittlecat are you able to get these changes to us within 24 hours?

If not we'll need to bring this in-house for the sake of expediency.

2022-03-25 19:34 UTC, 0xdef1cafe commented
hey @codinglittlecat - are you also @visitskyworld?

2022-03-25 20:34 UTC, 0xApotheosis commented
@codinglittlecat / @visitskyworld I can see a few commits since my last comment, though they only seemed to have addressed one of the remaining 5 outstanding concerns (and most crucially, Cypress is still reaching out to the server for _every_ request - preventing this from occurring is the key requirement that this PR needs to achieve).

Please see below a summary of where I currently see this PR with respect to the requests I've made:

---

✅  Commit the mocks generated when all tests are run, and remove the rest

❌  Ensure that the PR is in a state such that when it is checked out, and `yarn cypress:run` is run locally, no mocks are modified - it should use the committed mocks (currently it's still hitting the server for _every_ request) - i.e., this PR doesn't achieve the primary objective of the bounty

❌  Ensure we have a working mechanism (ideally a flag) to update mocks in the future, and to clear out stale any mocks

❌  Ensure all requests are mocked (e.g. those in "nav bar works")

❌  When running the tests with the mocks we get a number of exceptions, causing the tests to fail - this might be something to do with the speed that the tests now run at. We'll need to find a solution for these

---

As this is dragging on a bit now, we'll take this in house or re-bounty it.

Due to the quality and responsiveness of our interactions on this bounty, and the previous bounty you attempted, we've had to make the difficult call not to accept you for future bounties moving forward - please do not apply.

I appreciate the attempt, and I'd encourage you to continue developing your skills and seeking out other open-source projects to contribute to.

2022-03-25 20:34 UTC, closed without merging