feat: remove route prop on layout components
shapeshift/web pull request #1283
Opened 2022-03-24 19:04 UTC by reallybeard

## Description

To make it easier when building out other routes, we needed to remove the required `route` prop. I moved the route generation into a context provider, as well as the active route. Now it will inherit the nested routes from the route provider and display them if the route has any.

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1282 

## Risk

Medium risk as we are moving the logic of routes into a provider, and this may effect plugins.

## Testing

Make sure all routes work, including defi. And test that the plugins are still working as expected.

## Screenshots (if applicable)

2022-03-24 19:21 UTC, cjthompson commented on src/AppProviders.tsx
> +                    <AppRouteProvider>
How is this different than the `BrowserRouterProvider`? Could they be combined?

2022-03-24 19:40 UTC, cjthompson approved these changes
Approved with comments

2022-03-24 21:40 UTC, DaoDev44 approved these changes

2022-03-24 23:52 UTC, 0xdef1cafe requested changes

2022-03-24 23:52 UTC, 0xdef1cafe commented on src/Routes/Routes.tsx
> +export const useAppRoutes = (): IRouteContext =>
this is dangerous - you're casting something possibly undefined to a concrete type

https://github.com/shapeshift/web/blob/develop/src/context/PluginProvider/PluginProvider.tsx#L135 is how to implement this safely

2022-03-24 23:56 UTC, 0xdef1cafe commented on src/Routes/Routes.tsx
> +export const useAppRoutes = (): IRouteContext =>
otherwise i will gladly give big boy stamp and 🍭

2022-03-25 18:17 UTC, 0xdef1cafe approved these changes

2022-03-25 18:44 UTC, merged