Remove circular dependencies
shapeshift/web pull request #1355
Opened 2022-03-30 23:28 UTC by theoboldfrazier

## Description

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

## Risk

## Testing

## Screenshots (if applicable)

2022-03-30 23:36 UTC, 0xdef1cafe commented on src/components/Delegate/StakingOpportunitiesRow.tsx
> +import { StakingAction } from 'plugins/cosmos/components/modals/Staking/StakingTypes'
```suggestion
import { StakingAction } from 'plugins/cosmos/components/modals/Staking/StakingCommon'
```

2022-03-30 23:36 UTC, 0xdef1cafe commented on src/components/Modals/Send/AddressInput/AddressInput.tsx
> +import { SendRoutes } from '../SendTypes'
```suggestion
import { SendRoutes } from '../SendCommon'
```

2022-03-30 23:36 UTC, 0xdef1cafe commented on src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx
> +import { PortfolioBalancesById } from 'state/slices/portfolioSlice/portfolioSliceTypes'
```suggestion
import { PortfolioBalancesById } from 'state/slices/portfolioSlice/portfolioSliceCommon'
```

2022-03-30 23:37 UTC, 0xdef1cafe requested changes
rename all "fooTypes" to "fooCommon"

2022-03-31 02:09 UTC, 0xdef1cafe approved these changes

2022-03-31 02:17 UTC, cjthompson approved these changes

2022-03-31 02:24 UTC, merged