fix: collapse drawer when menu item is clicked
shapeshift/web pull request #1521
Opened 2022-04-19 19:40 UTC by reallybeard

## Description

- when the drawer is open its trapping focus so we need to collapse it whenever you click on a menu item
- Pass down the onClose from the useDisclosure
- Add a helper handleClick function that fires the onClose and the onClick

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1400 

## Risk

Small risk

## Testing

Click on a switch wallet or submit feedback/settings the drawer should collapse giving focus to whatever menu you just clicked.

## Screenshots (if applicable)

2022-04-19 19:42 UTC, NeOMakinG requested changes

2022-04-19 19:42 UTC, NeOMakinG commented on src/components/Layout/Header/Header.tsx
> +  const { onToggle, isOpen, onClose } = useDisclosure({ id: 'navDrawer' })
I think the id is useless, isn't it?

2022-04-20 04:47 UTC, 0xApotheosis requested changes
I like the approach, but it doesn't seem to fix it for me. When I click "Switch wallet" the draw stays open and I can't type in any inputs, see screenshot below. 

Tested with the responsive dev tools in Brave.

@NeOMakinG I see an approval from you, did it work ok for you when testing?

<img width="685" alt="Screen Shot 2022-04-20 at 2 43 37 pm" src="https://user-images.githubusercontent.com/97164662/164152192-0aec0a8b-c23c-434f-ac94-642bfa6f6c68.png">

2022-04-20 04:50 UTC, reallybeard commented
> I like the approach, but it doesn't seem to fix it for me. When I click "Switch wallet" the draw stays open and I can't type in any inputs, see screenshot below.
> 
> Tested with the responsive dev tools in Brave.
> 
> @NeOMakinG I see an approval from you, did it work ok for you when testing?
> 
> <img alt="Screen Shot 2022-04-20 at 2 43 37 pm" width="685" src="https://user-images.githubusercontent.com/97164662/164152192-0aec0a8b-c23c-434f-ac94-642bfa6f6c68.png">

Doesn't seem to work on the cloudflare pages deployment... looking into it

2022-04-20 06:23 UTC, 0xApotheosis approved these changes
The last commit fixed it 👍

2022-04-20 07:34 UTC, merged