feat: add service-worker
shapeshift/web pull request #1558
Opened 2022-04-21 22:06 UTC by cjthompson

## Description

feat: add service-worker

`create-react-app` already includes `workbox` for supporting service-workers for PWAs, so no change to the webpack config was required.

However, because `react-scripts` automatically calls `InjectManifest`, the `service-worker` file must include a reference to `__WB_MANIFEST` or the build will fail.  That manifest can be used for doing caching of assets but we're not doing that right now.

## Notice

- [X] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [X] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1545

## Risk

Low. The worst case is the service worker doesn't load but that won't cause anything else to stop working. It's possible there's a slight performance decrease when there are a lot of HTTP calls due to the logging of all service worker events.

## Testing

It's best to test this is an ephemeral environment.
1. Check the Console tab in Developer Tools.
2. Look for `ServiceWorker` log entries

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/1958266/164559491-152b3044-d737-4183-ae1d-61487f2c0eaa.png)

### From the Fleek build:
![image](https://user-images.githubusercontent.com/1958266/164580665-d36c819f-c2a0-4105-ba8b-73c69480942e.png)

2022-04-21 22:14 UTC, 0xdef1cafe commented
@cjthompson are we able to push a "breaking change" to this branch to ensure we don't cache the wrong thing and get users in a broken state? 

https://create-react-app.dev/docs/making-a-progressive-web-app/#why-opt-in

https://github.com/facebook/create-react-app/issues/2398

2022-04-21 22:25 UTC, cjthompson commented
> @cjthompson are we able to push a "breaking change" to this branch to ensure we don't cache the wrong thing and get users in a broken state?
> 
> https://create-react-app.dev/docs/making-a-progressive-web-app/#why-opt-in
> 
> [facebook/create-react-app#2398](https://github.com/facebook/create-react-app/issues/2398)

There service-worker doesn't actual do anything right now. It doesn't cache anything so it can't cache the wrong things.

2022-04-22 15:24 UTC, 0xdef1cafe requested changes
small requested change, and me rambling out loud

2022-04-22 15:24 UTC, 0xdef1cafe commented on src/serviceWorkerRegistration.ts
> +    }
we recently removed `PUBLIC_URL` from env vars in production - will this work?

2022-04-22 15:24 UTC, 0xdef1cafe commented on src/serviceWorkerRegistration.ts
> +      debugger
erroneous debugger
```suggestion
```

2022-04-22 15:24 UTC, 0xdef1cafe commented on src/serviceWorkerRegistration.ts
> +    }
just checked this in the console and indeed it does, nvm

2022-04-22 15:30 UTC, 0xdef1cafe approved these changes

2022-04-22 16:47 UTC, asamere approved these changes

2022-04-22 17:05 UTC, merged