feat: flatten caip imports
shapeshift/web pull request #1591
Opened 2022-04-26 21:10 UTC by gomesalexandre

## Description

This imports caip utils from the new flattened exports in https://github.com/shapeshift/lib/pull/560

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/lib/issues/548

## Risk

## Testing

## Screenshots (if applicable)

2022-04-27 19:58 UTC, 0xdef1cafe requested changes

2022-04-27 19:58 UTC, 0xdef1cafe commented on package.json
> +    "@shapeshiftoss/chain-adapters": "^2.13.3",
```suggestion
```

2022-04-27 20:00 UTC, 0xdef1cafe commented on package.json
> +    "@shapeshiftoss/chain-adapters": "^2.13.3",
don't bump these manually - CI does this

2022-05-06 20:42 UTC, 0xdef1cafe approved these changes

2022-05-06 21:33 UTC, 0xApotheosis approved these changes
🍭

2022-05-06 21:34 UTC, merged