Friendly captcha
shapeshift/web pull request #1600
Opened 2022-04-27 21:50 UTC by theoboldfrazier

## Description

Adds a captcha to legacy login form.

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1598 

## Risk

Low risk to legacy login, behind a feature flag.

## Testing

You should see a captcha automatically show and verify that you are a person. Once verified, the captcha disappears.

## Screenshots (if applicable)

<img width="921" alt="Screen Shot 2022-04-27 at 15 47 10" src="https://user-images.githubusercontent.com/88169003/165636704-83ecb5f9-d54d-4f45-a644-b6639833509f.png">

2022-04-28 21:48 UTC, cjthompson approved these changes

2022-04-29 00:14 UTC, 0xdef1cafe commented on src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx
>    }
```suggestion
```

2022-04-29 00:14 UTC, 0xdef1cafe commented on src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx
> +                <FriendlyCaptcha handleCaptcha={handleCaptcha} />
```suggestion
                <FriendlyCaptcha handleCaptcha={setCaptchaSolution} />
```

2022-04-29 00:15 UTC, 0xdef1cafe commented on src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx
>    }
also - this type sig is different to another component where it's `string | any` - which is it?

2022-04-29 00:15 UTC, 0xdef1cafe commented on src/context/WalletProvider/NativeWallet/components/Captcha.tsx
> +  )
```suggestion
```

2022-04-29 00:16 UTC, 0xdef1cafe commented on src/context/WalletProvider/NativeWallet/components/Captcha.tsx
> +        errorCallback: errorCallback,
```suggestion
        doneCallback: handleCaptcha,
        errorCallback: handleCaptcha,
```

2022-04-29 00:17 UTC, 0xdef1cafe commented on src/context/WalletProvider/NativeWallet/components/Captcha.tsx
> +    }
```suggestion
    return () => widget.current?.destroy?.()
```

2022-04-29 00:18 UTC, 0xdef1cafe requested changes
few suggested simplifications - some stylistic

unless i'm missing something these callbacks seem entirely unnecessary?

2022-04-29 00:20 UTC, 0xdef1cafe commented on src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx
>    }
if we just pass down `setCaptchaSolution` to the child it'll be referentially stable and we don't need the callbacks in the child either?

2022-04-29 17:02 UTC, theoboldfrazier commented on src/context/WalletProvider/NativeWallet/components/Captcha.tsx
> +  )
@0xdef1cafe Good find. Yeah, those callbacks were extraneous.

I pulled them out.

2022-04-29 17:02 UTC, theoboldfrazier commented on src/context/WalletProvider/NativeWallet/components/Captcha.tsx
> +    }
Done.

2022-04-29 17:12 UTC, 0xdef1cafe commented
hey @theoboldfrazier - as discussed w/ @DiggyDiggy2 can we please center the captcha inside the modal? 🙏

2022-04-29 20:30 UTC, theoboldfrazier commented
@0xdef1cafe done.

2022-05-02 15:35 UTC, elmutt submitted a review, later dismissed

2022-05-02 16:21 UTC, mrnerdhair requested changes
Gimme a minute to double-check the `friendly-captcha` library itself and see what it does. I looked at it briefly a while ago, and I have a vague memory that we might need to put it in an iframe for some reason.

2022-05-02 23:02 UTC, 0xdef1cafe submitted a review, later dismissed

2022-05-02 23:05 UTC, 0xdef1cafe commented
@theoboldfrazier env vars added to cloudflare and fleek

2022-05-03 00:44 UTC, mrnerdhair commented
Right, so looks like the `friendly-challenge` library sets `innerHTML` using some string-interpolated templates in order to render its UI. It doesn't look like it particularly _needs_ to do it that way -- it could just as easily do things in a provably-safe manner -- so I suggest we just make it work like that, probably using just `patch-package` for convenience.

Scope would be basically https://github.com/FriendlyCaptcha/friendly-challenge/blob/217438a5002e99134bbf0d50e097efb7b29082d0/src/captcha.ts, where the `get*HTML()` would need to return DOM elements; probably by importing `lit-html` (which they used `innerHTML` to [avoid](https://github.com/FriendlyCaptcha/friendly-challenge/blob/217438a5002e99134bbf0d50e097efb7b29082d0/src/dom.ts#L12) upstream since they were optimizing for lower dependency count).

Suggested AC would be that the modified `friendly-challenge` library works under a CSP of `trusted-types lit-html; require-trusted-types-for 'script'`. While `web` won't work under that policy out-of-the box (mainly because `react-dom` hasn't gotten their trusted types support out from behind a feature flag yet), it's a really easily-definable and easily-testable way to show that the library's performing safely.

I suggest that someone:
1) Spin up a blank app -- just `yarn init` in an empty folder, and install `microbundle`, `patch-package`, `postinstall-postinstall`, `lit-html`, and `friendly-challenge`. Set the build command to `microbundle` and the postinstall command to `patch-package`.
2) Cook up the world's stupidest static HTML page which imports the bundle `microbundle` spits out.
3) Write a tiny bit of code -- in plain JS b/c installing `tsc` wouldn't be worth the effort -- that imports the `friendly-challenge` library and renders the captcha to the page.
4) Make sure that all works, then add the CSP using a meta tag to break it.
5) Unbreak everything by screwing with `node_modules/friendly-challenge` until it uses `lit-html` instead of `innerHTML`
6) `patch-package friendly-challenge` to generate the patch
7) Cut-n-paste that patch into this PR

2022-05-03 19:56 UTC, cjthompson approved these changes

2022-05-03 20:09 UTC, cjthompson commented
I don't know why the build is failing. It works just fine locally, even when doing a clean and installing from scratch.

2022-05-03 22:15 UTC, mrnerdhair approved these changes

2022-05-03 22:38 UTC, merged