fix(UserMenu): locked metamask not reconnecting
shapeshift/web pull request #1667
Opened 2022-05-03 15:59 UTC by brymut

## Description
 Added a button group to separate the dropdown button while wallet is stuck in a loading state when Metamask is locked
Fixes #1262 

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

## Risk

## Testing

## Screenshots (if applicable)

2022-05-03 16:39 UTC, 0xdef1cafe commented
@brymut please fill out the PR template before i review this

2022-05-03 22:54 UTC, brymut commented
Apologies @0xdef1cafe , I thought I had marked this PR as a Draft

2022-05-04 03:52 UTC, 0xApotheosis requested changes
This meets the AC, and works.

Design-wise we should show `ChevronRightIcon` when the menu is not expanded, and `ChevronDownIcon` only when it is.

It was not in the AC, but in the future I'd prefer us query the state of Metamask, as the UI can still get in strange states when Metamask is locked, and it's not always intuitive why.

2022-05-04 07:00 UTC, brymut commented
I have applied the requested change regarding the ChevronRightIcon and the ChevronDownIcon changing depending on the state of the dropdown expansion state

Uploading Screen Recording 2022-05-04 at 9.56.46 AM.mov…

.

2022-05-04 07:20 UTC, 0xApotheosis commented
Thanks for the quick turnaround @brymut!

I just read through the issue, and I think we've also missed a comment from @DiggyDiggy2 to add "wallet locked" text: https://github.com/shapeshift/web/issues/1262#issuecomment-1076830263

2022-05-04 07:22 UTC, brymut commented
I guess we would have to query the state of MetaMask to get this info? @0xApotheosis

2022-05-04 07:32 UTC, 0xApotheosis commented
That's probably true, else we can't tell if it's locked, or just loading.

I don't see that requirement in the AC, so I'm ok with this PR.

I'll leave it to @0xdef1cafe as the bounty sponsor to confirm.

2022-05-04 07:47 UTC, 0xApotheosis requested changes
@brymut I just ran this again locally and also noticed that the `WalletConnected` flashes as the menu is opening.
You can also see this in the video you posted above.

This is a regression - I don't experience this behavior in production.

2022-05-04 07:58 UTC, brymut commented
> @brymut I just ran this again locally and also noticed that the `WalletConnected` flashes as the menu is opening. You can also see this in the video you posted above.
> 
> This is a regression - I don't experience this behavior in production.

Hi, I think that flash was because I tried to trim the clip and accidently made a bad cut.
As for the `WalletConnected` flashing, I'm not sure I quite understand, could you please reproduce. I ran through the process again in this clip below and didn't experience it.

2022-05-04 08:42 UTC, 0xApotheosis commented
@brymut 

https://user-images.githubusercontent.com/97164662/166648733-a29db811-63c6-4a6b-b2b8-846a3a8fa0e0.mov

2022-05-04 08:50 UTC, brymut commented
> @brymut
> 
>  Screen.Recording.2022-05-04.at.6.41.20.pm.mov

Right sorry, I hadn't noticed that, will investigate

2022-05-04 10:31 UTC, brymut commented
@0xApotheosis Ok, so it appears that the internal state `isOpen` provided by ChakraUI causes unnecessary re-renders for this use case, so I have opted to use React's `useState` hook to track the state of the dropdown menu and it appears to get rid of the regression.

https://user-images.githubusercontent.com/14836056/166665050-a4f9f9b2-4861-41b2-913b-c402fd941341.mov

2022-05-04 12:00 UTC, gomesalexandre commented
> It was not in the AC, but in the future I'd prefer us query the state of Metamask, as the UI can still get in strange states when Metamask is locked, and it's not always intuitive why.

Actually:
> It might be worth first investigating if we're even able to query this state from MetaMask. This may require a PR into [hdwallet](https://github.com/shapeshift/hdwallet/).

I would expect this PR to at least spike whether or not it's possible, and if not, have some information on where to go from here for follow-up PRs.
From *quickly* spiking this (no runtime test of it), hdwallet has some `isLocked` method implemented in all `hdwallet` packages, although implemented as a simple `return false` for native and portis. On packages where it is fully implemented (MetaMask/XDEFI/KeepKey), it effectively queries the Ethereum Provider for the `isUnlocked()`state ([docs](https://docs.metamask.io/guide/ethereum-provider.html#ethereum-metamask-isunlocked)) for MM/XDEFI, and the pin/passphrase cached/protected state for KK.

Can you have a look into using this? It should make the implementation stronger and will also make us able to have the "wallet locked" state that was mentioned by product.

2022-05-04 12:14 UTC, brymut commented
> Can you have a look into using this? It should make the implementation stronger and will also make us able to have the "wallet locked" state that was mentioned by product.

I have been looking into this too, however I'm still familiarising myself with the web repo, will get back to you with a solution that better handles the locked state or at least suggestions for follow up PRs as you've suggested.

Would this require a more uniform approach to handling the locked state for other wallet providers aside from Metamask too? @gomesalexandre

2022-05-04 12:36 UTC, gomesalexandre commented
> I have been looking into this too, however I'm still familiarising myself with the web repo, will get back to you with a solution that better handles the locked state or at least suggestions for follow up PRs as you've suggested.

Let me know if there's anything I can help with. Given this method is already implemented, you shouldn't have to fiddle with `yarn link`ing anything so the process should be all on web (although you might want to clone the `hdwallet` repo to dig into the code easier than with GitHub web UI).

> Would this require a more uniform approach to handling the locked state for other wallet providers aside from Metamask too? @gomesalexandre

As far as this issue is concerned, this should be MetaMask only. Given XDEFI has a very close API to MetaMask, and so does the [WIP Tally integration](https://github.com/shapeshift/hdwallet/pull/506) (basically a MetaMask fork/rewrite), it would be nice to have an approach that works for MetaMask/XDEFI for now, and Tally in the future by adding a single switch case/line/member in some const. But that's not required as part of this bounty. 

KeepKey/Native both have quite a bit of different logic and are not concerned by this. The only important thing here is that they have no regressions (I can test this out with KeepKey when reviewing).

2022-05-05 14:16 UTC, brymut commented
Hi @gomesalexandre, I've had a look into the connection process for the wallet and my suggesion would be to track the locked/unlocked state of the wallet in the `WalletProvider`, `initialState` and adding an `isUnlocked`:
https://github.com/shapeshift/web/blob/48dad159f49d4cf2fa9a8c514c0df142b84a808f/src/context/WalletProvider/WalletProvider.tsx#L76-L91
and to toggle that state we can create a `WalletActions.SET_IS_UNLOCKED` action:
https://github.com/shapeshift/web/blob/48dad159f49d4cf2fa9a8c514c0df142b84a808f/src/context/WalletProvider/actions.ts#L9-L25
, which we can dispatch when setting up the wallet state in the Metamask WalletProvider, and other similar areas for the other WalletProviders as appropriate as we proceed, we can query Metamask using the `isUnlocked` method you linked to [in the docs](https://docs.metamask.io/guide/ethereum-provider.html#ethereum-metamask-isunlocked) :
https://github.com/shapeshift/web/blob/48dad159f49d4cf2fa9a8c514c0df142b84a808f/src/context/WalletProvider/MetaMask/components/Connect.tsx#L51
Then when it comes to displaying the state of the WalletButton instead of creating a new UI element to inform the user that the wallet is locked, we can just immediate call `disconnect` so that they can begin the wallet connection process again which would prompt them to check on the state of their wallet, like in the screen recording below:

https://user-images.githubusercontent.com/14836056/166942686-cadac9e8-e52f-4d54-b99d-113ca45e50fa.mov

Only downside is that to my knowledge, we cant get an event listener for when the wallet is locked so it can only be detected when the page is refreshed. What are your thoughts on this?

2022-05-05 17:12 UTC, gomesalexandre commented
@brymut That implementation sounds good overall! A couple notes/comments:
- We should probably use `isLocked` to match the logic in hdwallet
- The `isLocked` state will always be false for Native/Portis - we shouldn't use this logic anyway since we will discriminate on the wallet type to fire the `disconnect()`
- KeepKey technically has some `isLocked` method as well but we handle that in a more complex way in web so it could always be `false` as well` - same thing, since we discriminate on the wallet type, we should never end up in a branch where `disconnect()` is fired for KeepKey anyway

Re: Disconnecting the user. Disconnecting on such changes is the usual flow so that sounds good to me. You're right that we have no such event handlers so there is no way for you to easily add that in this PR, which is fine since that's out of this scope of this issue.

2022-05-06 04:44 UTC, brymut commented
Thanks @gomesalexandre I've taken note, and when it's tracked in a separate issue, I'd be more than happy to handle it in the subsequent PR. Is there anything else to be done on this one?

2022-05-06 08:28 UTC, gomesalexandre commented
> Thanks @gomesalexandre I've taken note, and when it's tracked in a separate issue, I'd be more than happy to handle it in the subsequent PR. Is there anything else to be done on this one?

I'll raise this one today, we'll probably need to spike it first. There's quite a lot of architectural changes required to be able to react on such changes, but the value is high, it would improve the UX a lot.

As far as your PR is concerned, your spike and proposed implementation seems to cover all we'll need here. Just tagging @0xdef1cafe in case he sees any concern with having the locked state in `<WalletProvider />`, but I say go with it. Worst case scenario if it works but there are architectural concerns, we can take it over from there 😉.

2022-05-06 08:31 UTC, brymut commented
So should I push the proposed implementation in this PR?

2022-05-06 08:38 UTC, gomesalexandre commented
@brymut Go for it!

2022-05-06 11:19 UTC, gomesalexandre commented on src/context/WalletProvider/MetaMask/components/Connect.tsx
> +        const isLocked = !(await provider?._metamask.isUnlocked())
Don't interact with the MetaMask provider directly but use the hdwallet method mentioned in https://github.com/shapeshift/web/pull/1667#issuecomment-1117228360:
```suggestion
        const isLocked = await wallet.isLocked()
```

2022-05-06 11:43 UTC, gomesalexandre requested changes
Looking much better now using locked state, but this produces regressions.

When connecting for the first time in the tab lifecycle, it will always disconnect. Trying to reconnect again will work (tested with Native/MetaMask). That's why you're seeing those Cypress failures.

Please have a look at the comment I added for the `isLocked` initial state, it is the reason you see regressions/failed tests. Setting it to false initially means we will never get a chance to connect the wallet until we explicitly set it to `false` with the relevant redux action, which means we'll always disconnect on the first wallet connection.

2022-05-06 11:43 UTC, gomesalexandre commented on src/context/WalletProvider/WalletProvider.tsx
> +  isLocked: true,
Should be set to `false` initially.

2022-05-06 15:21 UTC, brymut commented
Hi @gomesalexandre I've applied the requested changes, also I think I may have noticed another potential reason why the state remained loading infinitely when metamask is disconnected, in `WalletProvider` here, the promise fails when the Metamask wallet is locked: 
https://github.com/shapeshift/web/blob/cd666cfe363fa6073acf2801fabbb7a7089e7eb6/src/context/WalletProvider/WalletProvider.tsx#L345-L347
And since there is no try/catch block to catch this, so `disconnect()` is never called and the rest of the code in the case block fails silently. I've tried applying a try/catch block there and the behaviour is exactly what we are trying to create in this PR without any need for tracking the `isLocked` state which I think might be a better solution for now. Here is the screen recording:

https://user-images.githubusercontent.com/14836056/167162860-717954bd-b212-44c9-9aeb-7e800f01c0ba.mov

2022-05-06 15:47 UTC, gomesalexandre commented
> And since there is no try/catch block to catch this, `disconnect()` is never called and the rest of the code in the case block fails silently. I've tried applying a try/catch block there on dev branch without the changes in this PR and the behaviour is exactly what we are trying to create in this PR without any need for tracking the `isLocked` state which I think might be a better solution for now. Here is the screen recording:

Gave it a try locally and I could indeed see an error, although it is `"Already processing eth_requestAccounts. Please wait."` (since I dismissed the MetaMask unlock when refreshing the page, and it is still showing as a pending notification. IMO these are not mutually exclusive, we should track the locked state **and** catch the `pairDevice()` errors. `isLocked()` just seems like a more declarative way to handle this as opposed to catching on `pairDevice()` and I find this implementation more reliable.

2022-05-06 18:17 UTC, gomesalexandre approved these changes
LGTM, tested by refreshing on a locked Metamask with dismissed unlock and it is possible to open "Connect Wallet" as a dropdown option.

2022-05-08 09:49 UTC, brymut commented
Hi @0xdef1cafe could you please have a look?

2022-05-10 10:11 UTC, 0xApotheosis reviewed
This all works well, well done @brymut.

My one reservation the moment is that the behaviour on lock has changed.

Currently, when a metamask wallet is locked the app will disconnect the wallet. Now that is no longer the case. However, this feature cannot be implemented without changing this functionality, so I'm assuming that was the product intent.

One other product note is that if we try to connect a Metamask wallet that's locked, and had the Metamask password wallet dismissed, it hangs. That is outside the scope of this PR, though.

2022-05-10 10:12 UTC, merged