feat: add FoxPage MainOpportunity component
shapeshift/web pull request #1799
Opened 2022-05-16 08:55 UTC by NeOMakinG

## Description
I added a new component called `MainOpportunity`
It currently has a few props:
```ts
type MainOpportunityProps = {
  apy: string
  tvl: BigNumber
  balance: string
  onClick: () => void
}
```
This API will probably change in the future depending on how we design its functionality

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
closes #1785

## Risk
No risk

## Testing
Check on storybook that the component looks like mockups

## Screenshots (if applicable)
<img width="762" alt="image" src="https://user-images.githubusercontent.com/14963751/168556090-ba3cb93e-c4de-4ed2-99f0-6dfae00dae43.png">

2022-05-17 20:53 UTC, elmutt approved these changes

2022-05-19 19:13 UTC, gomesalexandre requested changes
A few changes requested WRT the API
Ran the Storybook locally and it LGTM visually, ready to stamp it after comments are tackled!

2022-05-19 19:13 UTC, gomesalexandre commented on src/plugins/foxPage/components/Layout.stories.tsx
> +                  apy='11.61%'
```suggestion
                  apy='0.1161'
```

2022-05-19 19:13 UTC, gomesalexandre commented on src/plugins/foxPage/components/Layout.stories.tsx
> +                  tvl={bnOrZero(150000000)}
This should be a string as well, let the component make it a BN, as they don't serialize well.
```suggestion
                  tvl={'150000000'}
```

2022-05-19 19:13 UTC, gomesalexandre commented on src/plugins/foxPage/components/MainOpportunity.tsx
> +              assetSymbol: 'FOX',
Pass this one from props also?

2022-05-19 19:13 UTC, gomesalexandre commented on src/plugins/foxPage/components/MainOpportunity.tsx
> +              value={tvl.toString()}
If you don't BN it, you won't need to `.toString()` it here

2022-05-19 19:28 UTC, theoboldfrazier commented on src/plugins/foxPage/components/MainOpportunity.tsx
> +export const MainOpportunity = ({ apy, tvl, balance, onClick }: MainOpportunityProps) => {
I'm wondering if `MainOpportunity` is the best naming here. It's very ambiguous when we consider non-fox opportunities down the road.

Perhaps `FoxOpportunity` might be better to clarify that this is directly related to general Fox earning opportunities.

2022-05-19 20:24 UTC, NeOMakinG commented
Thanks for the review, should be fine now :)

2022-05-19 21:56 UTC, theoboldfrazier approved these changes

2022-05-20 16:42 UTC, 0xdef1cafe commented on src/plugins/foxPage/components/FoxOpportunity.tsx
> +}: MainOpportunityProps) => {
```suggestion
export const FoxOpportunity: React.FC<MainOpportunityProps> = ({
  apy,
  tvl,
  assetSymbol,
  balance,
  onClick,
}) => {
```

non-blocking comment, but this is always the nicer way to do things - type the function, not the args

2022-05-20 16:42 UTC, 0xdef1cafe approved these changes

2022-05-20 16:49 UTC, gomesalexandre approved these changes
Pulled locally, story still LGTM. Component has been properly updated with an `Amount.Percent` to accomodate the new 0.-format APY.

2022-05-20 17:07 UTC, merged