fix: Defi page icon for FOXY in Overview tab changed from FOX to FOXY
shapeshift/web pull request #1889
Opened 2022-05-25 22:37 UTC by irohdw

Added replaceIcon function to src/pages/defi/components/OpportunityCard.tsx. It is called in the AssetIcon tag in line 113.

Added a commented out replaceValue function in line 18 src/pages/defi/components/OpportunityCardList.tsx. It could be used to replace the icon by swapping the FOX asset ID for FOXY.

If the icon for FOX moves to a different URL, then this code will not replace the icon properly.

## Description

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

## Risk

## Testing

## Screenshots (if applicable)

2022-05-31 09:08 UTC, gomesalexandre commented
@irohdw Is this one now ready for review?

2022-05-31 14:11 UTC, irohdw commented
> @irohdw Is this one now ready for review?

Yes it is.

2022-05-31 23:01 UTC, 0xdef1cafe commented on src/pages/Defi/components/OpportunityCardList.tsx
> +  iconReplaceMap.set(foxID, foxyIcon)
this is unnecessary, and asset specific logic leaking into a view.

2022-05-31 23:02 UTC, 0xdef1cafe commented on src/pages/Defi/components/OpportunityCardList.tsx
> +const foxyID = 'eip155:1/erc20:0xdc49108ce5c57bc3408c3a5e95f3d864ec386ed3'
this should be scoped to the function they're used in

2022-05-31 23:04 UTC, 0xdef1cafe commented on src/pages/Defi/components/OpportunityCardList.tsx
> +              overrideAssetIconID={overrideIconAssetId}
why does this have two different names? `overrideAssetIconID` doesn't make sense, capitalization isn't consistent.

2022-05-31 23:04 UTC, 0xdef1cafe requested changes
comments

2022-06-01 12:17 UTC, gomesalexandre commented
@irohdw Can you fill in the missing description fields, including linking https://github.com/shapeshift/web/issues/1540 as an issue? It's not possible to review this without the right context.

2022-06-01 12:32 UTC, gomesalexandre requested changes
See comment.

From a high-level, not a fan of having such granular, asset-specific logic so close to components that are not asset-specific and map over many assets.

The idea is we try to have all the data fetching/parsing/selecting and deriving done in a very few contained places, and react to these. That solves (amongst other issues) discrepancies in logic, where you would have to repeat the logic in every component and possibly forget it in others.

That's precisely the case here: in #1889, `DeFi tab` is mentioned as a scope for these changes. That means that with such implementation, you'd have to duplicate the component-colocated logic for the Earn tab as well, else we'd still have the FOX icon in earn:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/17035424/171402737-7ad563a4-ce8f-4716-852b-f1270d59753f.png">

Have a look at `useFoxyBalances`, which returns the foxy opportunities, and `useNormalizeOpportunities` which normalizes FOXy/Yearn/Cosmos staking opportunities
https://github.com/shapeshift/web/blob/fd67442e47da2136ddf7148fa3549c330a1b89e5/src/pages/Defi/hooks/useFoxyBalances.tsx#L96
https://github.com/shapeshift/web/blob/af9483696fa1430802b71146def53c893415a2d7/src/features/defi/helpers/normalizeOpportunity.tsx#L165

Can't we make it so that the opportunity icon is present in the `EarnOpportunityType` (it is currently not, we get it from `Asset`), which will allow us to do that FOX -> FOXy icon transformation in opportunities parsing/normalizing?

2022-06-01 16:50 UTC, closed without merging