feat: add a tokemak APR fetching service
shapeshift/web pull request #1917
Opened 2022-06-01 16:03 UTC by gomesalexandre

## Description

This adds a service for fetching the FOX tokemak APR.

Note that this is self-contained in plugins folder for now, but eventually, we'll be able to use this app-wide to get FOXy's APY. 

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Partially tackles #1834

## Risk

None, this is isolated and not used as app code yet. 

## Testing

Test added for the hook, CI should be happy. 

## Screenshots (if applicable)

2022-06-01 19:37 UTC, gomesalexandre commented on src/plugins/foxPage/hooks/useFoxyApr.ts
> +const TOKEMAK_TFOX_POOL_ADDRESS = '0x808d3e6b23516967ceae4f17a5f9038383ed5311'
Shouldn't, if there's an upgrade of the pool contract, we/Tokemak probably have bigger problems WRT migration!

2022-06-02 13:49 UTC, elmutt submitted a review, later dismissed

2022-06-02 15:08 UTC, 0xdef1cafe requested changes
fix variable naming otherwise goodly

2022-06-02 15:08 UTC, 0xdef1cafe commented on sample.env
> +REACT_APP_TOKEMAK_STATS_URL=https://stats.tokemaklabs.com/
i've added this to fleek for you

2022-06-02 15:10 UTC, gomesalexandre commented on src/plugins/foxPage/hooks/useFoxyApr.ts
> +    const loadGovernanceData = async () => {
unwoopsed

2022-06-02 17:20 UTC, 0xdef1cafe approved these changes

2022-06-02 17:20 UTC, merged