feat: generic approve tx history
shapeshift/web pull request #1921
Opened 2022-06-01 23:33 UTC by vividwood

## Description

Added tx history for generic ERC20 approve method

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/lib/issues/658

## Risk

## Testing

1. Build and link `unchained-client` with this branch https://github.com/shapeshift/lib/pull/731
2. Select DemoWallet in web app
3. Open transaction history, you should see `Approve FOX` tx

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/101632255/171518265-dd19740f-c416-4d00-88d6-054e0311bfce.png)

2022-06-02 15:20 UTC, 0xdef1cafe requested changes

2022-06-02 15:20 UTC, 0xdef1cafe commented on src/components/TransactionHistoryRows/TransactionGenericRow.tsx
> +  title?: string | null | [string, number | Polyglot.InterpolationOptions]
absolutely not

2022-06-02 21:22 UTC, vividwood commented on src/hooks/useTxDetails/useTxDetails.ts
> +    case ChainTypes.Ethereum:
Ok, got it

2022-06-02 21:23 UTC, vividwood commented
> putting in draft till you're passing CI

yes we need to merge https://github.com/shapeshift/lib/pull/731 first

2022-07-25 20:16 UTC, 0xdef1cafe commented on src/assets/translations/en/main.json
> +        "approve": "Approve %{symbol}"
most of the complexity in this PR can be avoided by not translating a symbol - we can't translate a symbol anyway, so let's just translate `Approve` using some common translation and show the symbol next to it?

2022-07-27 21:18 UTC, 0xdef1cafe commented
closing as stale in favor of https://github.com/shapeshift/web/pull/2257

2022-07-27 21:18 UTC, closed without merging