chore: update the OpportunityCard component to show the icon for Foxy
shapeshift/web pull request #1922
Opened 2022-06-02 00:27 UTC by nejos97

## Description

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1540 
## Risk

You will now see the Foxy icon instead Fox in the defi page.

## Testing

Go to the defi page and see if the 'FOX token staking' icon is indeed Foxy's. 

## Screenshots (if ap
![Screenshot 2022-06-02 at 01-16-57 ShapeShift DAO](https://user-images.githubusercontent.com/13876543/171522189-5eb2ccda-c2e6-4a10-b723-95efeb931900.png)
plicable)

2022-06-02 15:11 UTC, 0xdef1cafe commented on src/pages/Defi/components/OpportunityCard.tsx
> +import { FoxAssetId, FoxyIconUrl } from 'plugins/foxPage/foxPage'
please don't import these from this plugin folder - plugins are supposed to be used in isolation, and data from them shouldn't be consumed outside of them

2022-06-02 15:15 UTC, 0xdef1cafe requested changes

2022-06-02 15:15 UTC, 0xdef1cafe commented on src/plugins/foxPage/foxPage.tsx
> +export const FoxyIconUrl =
please do not add this here

2022-06-02 15:15 UTC, 0xdef1cafe commented on src/pages/Defi/components/OpportunityCard.tsx
> +  const icon = useMemo(() => {
please do not put asset specific logic in this component, we need to see a generic solution that is extensible in future

the guidance i gave to a previous contributor was as follows

make a function that takes the assetId, and returns an override asset icon url

don't hardcode the URLs - get them from the asset service

use a object of the original asset id, to the override asset id, then get the icon from the override asset

if there isn't an override, just use the original icon

2022-06-04 00:02 UTC, 0xApotheosis approved these changes
🍭

2022-06-04 00:04 UTC, 0xdef1cafe approved these changes

2022-06-04 00:15 UTC, 0xdef1cafe commented
merging as the cypress failure is known and not critical

2022-06-04 00:15 UTC, merged