feat: fiat ramp back button
shapeshift/web pull request #2284
Opened 2022-07-30 08:12 UTC by jmurphy5613

## Description

I added a back button to the fiat ramp modal. This is connected to [this issue](https://github.com/shapeshift/web/issues/2273).

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #2273 

## Risk

Small, ui changes to only the fiat ramp modal

## Testing

- Open the buy/sell crypto button on the dashboard
- Click on any of the ramps
- click the back button at the top left

## Screenshots (if applicable)
<img width="1434" alt="Screen Shot 2022-07-30 at 4 11 25 AM" src="https://user-images.githubusercontent.com/67712161/181890675-4ace1820-1fd3-46b6-9259-0f7b6ace43b4.png">

<img width="1434" alt="Screen Shot 2022-07-30 at 4 11 14 AM" src="https://user-images.githubusercontent.com/67712161/181890815-6293fbda-81ad-4e02-b8ae-b323ecca0a2e.png">

2022-07-30 10:59 UTC, gomesalexandre requested changes
Hi @jmurphy5613 👋🏽 thank you for the first contribution!

Could you please get lint autofix set up on your editor or run `yarn lint` / `yarn local-ci` and fix the lint errors accordingly?

WRT the functionality of this, it does work as intended when you're on the "Asset to buy / Asset to sell" route but when you're on a "Select an asset to buy" / "Select an asset to sell" route, there are now two back buttons, and the modal header is collapsed:

This diff:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/17035424/181907729-8d61c96e-965d-436e-91f8-a38acb3b5d5a.png">

develop:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/17035424/181907748-2467a737-8ded-4d94-afdf-5ada8a45e59f.png">

The larger one (the newly introduced one) routes back to the fiats ramp selection, while the smaller one routes back to the buy/sell screen.

We should keep only one (preferably the larger one, which is actually a more consistent one throughout the app) and make it superseed the behavior or the "smaller" one e.g route back to the buy/sell section if on the asset selection route, or route back to the fiat ramps selection if on the buy/sell section

2022-07-30 18:22 UTC, jmurphy5613 commented
Thanks for your feedback. How can I get access to the current location or url of the Manager components within the FiatRamps component without using something like the context api? The MemoryRouter isn't tracking the history of the nested routes.

2022-07-30 19:17 UTC, gomesalexandre commented
> Thanks for your feedback. How can I get access to the current location or url of the Manager components within the FiatRamps component without using something like the context api? The MemoryRouter isn't tracking the history of the nested routes.

I just gave it a try locally and yeah, our usage of `<MemoryRouter />` will make this impossible without revamping the routes logic. That would be out of the scope of this bounty.

@shapeshift/product What do we think about keeping only the newly added outer button, but losing the functionality of going back from "Select an asset to buy" / "Select an asset to sell" to "Asset to buy" / "Asset to sell" (it will route back to the ramps list) until the core team tackles the architectural change necessary to make it work properly?

2022-07-30 19:19 UTC, gomesalexandre commented on src/components/Modals/FiatRamps/FiatRamps.tsx
> +          }}
You can remove that wrapping arrow function to make it one less function in the stack trace

```suggestion
          onClick={history.goBack}
```

2022-07-31 16:19 UTC, gomesalexandre commented
Checked out locally and CI is passing. @shapeshift/product WRT https://github.com/shapeshift/web/pull/2284#issuecomment-1200280054 please use the Fleek build from this PR:

https://bafybeiffsd5b6o3weowpk23yzqpq2o4m726jcxrzh77c4quksjjw3id2ye.on.fleek.co/

2022-07-31 23:55 UTC, decentralized-j commented
> > Thanks for your feedback. How can I get access to the current location or url of the Manager components within the FiatRamps component without using something like the context api? The MemoryRouter isn't tracking the history of the nested routes.
> 
> I just gave it a try locally and yeah, our usage of `<MemoryRouter />` will make this impossible without revamping the routes logic. That would be out of the scope of this bounty.
> 
> @shapeshift/product What do we think about keeping only the newly added outer button, but losing the functionality of going back from "Select an asset to buy" / "Select an asset to sell" to "Asset to buy" / "Asset to sell" (it will now route back to the ramps list) until the core team tackles the architectural change necessary to make it work properly?
> 
> Or alternatively, keep the two, which might look weird from UI standpoint.

I think this is a fine approach to take until the bigger lift can be conducted. At the end of the day I think it's a win for users to be able to back out to the provider list rather than having to start the entire process over again and reopen the modal. We don't have the data to back it up but I'd guess our conversion rate would be higher in this instance.

I ran through the Fleek link and did my best to break it, this functions exactly as expected in my testing across all 3 providers. Curious if ops can break it somehow but if they can't then this looks ready to roll to me! thank you @gomesalexandre @jmurphy5613

2022-08-01 09:26 UTC, gomesalexandre requested changes

2022-08-01 09:26 UTC, gomesalexandre commented on src/components/Modals/FiatRamps/FiatRamps.tsx
> +  if (location.pathname == FiatRampsRoutes.Select) {
Got some eqeqeq tweak spinned up so we error on this vs. simply emitting a warning currently: https://github.com/shapeshift/web/pull/2291

2022-08-01 14:12 UTC, gomesalexandre approved these changes
From a bounty perspective, this is it! Well done @jmurphy5613 👍🏽 

Keep in mind you'll need another stamp here before this gets merged and the bounty is completed

2022-08-01 15:20 UTC, 0xdef1cafe approved these changes

2022-08-01 15:20 UTC, merged