feat: add explorer's link and contract name when approving
shapeshift/web pull request #2315
Opened 2022-08-02 16:01 UTC by NeOMakinG

## Description
I still added the contract name inside a link to the explorer.

There are 2 approvals components, `Approve.tsx` is linked to the swap feature, this one is afaik only linked to ERC20, meaning that we can use etherscan

The other one (`Approval.tsx`) is linked to DeFi features, which will be linked to Cosmos soon and other blockchain we will be supporting some staking contracts

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
closes #2268

## Risk

## Testing
- Try to swap a token, like FOX => ETH for example, when you see the approval window, you'll see the swapper name + a link to the explorer 
- Try to stake some Fox to the Foxy contract, you'll see the approval modal with the same thing

## Screenshots (if applicable)
<img width="396" alt="image" src="https://user-images.githubusercontent.com/14963751/182419262-7090f8c8-2034-4e47-a464-9dfaa4677e3d.png">

2022-08-02 16:42 UTC, NeOMakinG commented on src/features/defi/components/Approve/Approve.tsx
> +            <Link href={`https://etherscan.io/address/${contractAddress}`}>Contract</Link>
Fixed as seen together, I used `ShapeShift DAO Router` as used everywhere else on the DeFi part

2022-08-02 18:49 UTC, gomesalexandre requested changes
Tested locally, FOXy Deposit/Withdraw and swapper approvals are showing the right name and linking to the right contract. 

For Yearn (yvUSDT vault) this is properly displaying the Shapeshift DAO router name and and prompting to sign a Tx `approve()`ing it, but is linking to a different contract address (the token i.e [USDT yVault (yvUSDT)](https://etherscan.io/token/0x7da96a3891add058ada2e826306d812c638d87a7))
<img width="536" alt="image" src="https://user-images.githubusercontent.com/17035424/182447884-aa508b87-942c-4aa5-bfc5-8f0e94f90325.png">

2022-08-02 18:49 UTC, gomesalexandre commented on src/features/defi/components/Approve/Approve.tsx
> +              {translate('modals.approve.routerName')}
I can kind of see why the original `Allow ShapeShift DAO Router to use your %{asset}` was there as a string, but would prefer this to be dynamic now, passed as a prop to the component, and then interpolated.

Given the ramifications of working with the DeFi UI abstraction and the diff size, this doesn't need to be as part of this PR but would be a nice-to-have refactor follow-up

2022-08-02 18:49 UTC, gomesalexandre commented on src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx
> +      contractAddress={contractAddress}
`contractAddress` is the address of the token being staked, not the address of the actual contract. What you're looking for is `ssRouterContractAddress` from `investor-yearn` - it is the same ShapeShift router contract for all Yearn tokens stakings

2022-08-03 21:49 UTC, gomesalexandre approved these changes
Tested again with the previous testing flow, works as previously tested and is now linking to the Shapeshift DAO Yearn Router for Yearn

2022-08-03 21:49 UTC, gomesalexandre commented on src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx
> +        },
Not a fan of a catch-all prop called props, especially not typed as `Record<any, any>` but that works for the purpose of fixing this

2022-08-04 12:21 UTC, merged