feat: native wallet passphrase recovery
shapeshift/web pull request #2470
Opened 2022-08-18 00:52 UTC by stackedq

## Description

[wip]

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

## Risk

## Testing

## Screenshots (if applicable)

2022-08-18 15:38 UTC, gomesalexandre reviewed
Tested and while this mostly looks fine functionally, noticed these discrepancies with the spec:

- `The user must pick from a selection of 15 words. If it’s correct, the user is moved forward to the next screen. If its incorrect, the screen re-scrambles and asks the user again.` - this doesn't re-scramble and it is possible to select from any of the scrambled words, until the right one is eventually chosen
- `User will see 3 subsequent screens to test their seed phrase, or they have the option to check a box, indicating they already have it written down successfully.` - this one isn't present in the PR

Are those approved by product as a deviation from the initial spec?

2022-08-18 15:38 UTC, gomesalexandre commented on src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx
> +              key={word}
Usually an antipattern, but I'd rather use the index as a key here for security reasons. At this point the words are already in clear in the browser, and rendered as a children but still, the less places they are in the better

2022-08-18 15:38 UTC, gomesalexandre commented on src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx
> +  const [shuffledNumbers] = useState(slice(shuffle(range(12)), 0, TEST_COUNT_REQUIRED))
Abstract away to `initialShuffledNumbersState` and/or disable eslint for it? Clojure-style expressions are hard to read when one-lined

2022-08-18 15:38 UTC, gomesalexandre commented on src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx
> +const ordinalSuffix = (n: number) => {
I know this is taken from a current implementation, but let's not spread this naming and make it clear this is a function and not an expression
```suggestion
const makeOrdinalSuffix = (n: number) => {
```

2022-08-18 21:20 UTC, 0xdef1cafe commented on src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx
> +              key={word}
just for safety make this the index

2022-08-19 05:26 UTC, stackedq commented
Reshuffling on failure and skip added
<img width="465" alt="Screen Shot 2022-08-19 at 09 53 40" src="https://user-images.githubusercontent.com/20498757/185549081-406097be-6f0e-4368-8bde-17ebd3ca3d02.png">

2022-08-19 10:54 UTC, gomesalexandre requested changes
@stackedq looking good with the checkbox now, and the reshuffling works but with it implemented perhaps we should also remove the "already tried" logic/UI, WDYT?

Also with the current logic, it is possible to end up in a state where all wrong tries are used, and it is not possible to select the right word anymore, see:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/17035424/185603429-e5a31c0b-1ec4-4d10-959b-94584424b0e4.png">

2022-08-19 14:00 UTC, gomesalexandre approved these changes
LGTM now with the removal of the "invalid tries" flow, retested the whole flow as a sanity check and does what it says on the box.

Well done ser! 🤵‍♂️

2022-08-19 14:15 UTC, merged