feat: account selection FOX-ETH farming
shapeshift/web pull request #2639
Opened 2022-09-01 22:14 UTC by gomesalexandre

## Description

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2022-09-01 22:14 UTC, gomesalexandre commented
Current dependencies on/for this PR:
* develop
  * **PR #2639** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2639" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2639?utm_source=stack-comment).

2022-09-02 16:29 UTC, 0xdef1cafe requested changes
<img width="724" alt="image" src="https://user-images.githubusercontent.com/88504456/188198015-ec0088b1-0285-4247-a322-0e3d09491cdc.png">

seeing new console error on defi page with metamask, and my FOXy balance is loading sporadically

2022-09-02 16:31 UTC, 0xdef1cafe commented
ETH-FOX LP and Farming are showing in on the earn opportunities list with multi account on and off correctly

2022-09-02 17:43 UTC, gomesalexandre commented
> <img alt="image" width="724" src="https://user-images.githubusercontent.com/88504456/188198015-ec0088b1-0285-4247-a322-0e3d09491cdc.png">
> 
> seeing new console error on defi page with metamask, and my FOXy balance is loading sporadically

Nice catch, inserted a new base PR in the stack (https://github.com/shapeshift/web/pull/2643) which fixes this - tl;dr is we were out of sync on the lib deps between lib packages internal deps and web

2022-09-02 21:42 UTC, 0xdef1cafe approved these changes
🧀

2022-09-02 21:42 UTC, merged