fix: default asset pair issues
shapeshift/web pull request #2641
Opened 2022-09-02 03:32 UTC by 0xApotheosis

## Description

Resubmitting https://github.com/shapeshift/web/pull/2626 with an additional commit, https://github.com/shapeshift/web/commit/5b49f3a0a2cf3f741ab74bc904b9e1e315b3b40f, which fixes the chain selection re-renders.

---

Simplifies the default asset setting logic, and turns it into a dedicated service, which inadvertently fixes all known related bugs.

- Switches `getUsdRate` calls to RTK query, cutting network calls to this endpoint by ~70% vs current production build
- Fixes `useEffect` logic so it only fires once, instead of multiple times, which is causing default assets for a connected wallet to be overwritten by default assets (ETH/FOX)
- Correctly resets `ethNetwork` between wallet reconnections

Note, this fixes the bugs across both V1 and V2 swapper.

## Notice

- [X] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Closes https://github.com/shapeshift/web/issues/2446
Closes https://github.com/shapeshift/web/issues/2627

## Risk

Touches default asset setting in the trade component. There is a risk these will not be set correctly.

## Testing

Default assets are no longer overwritten:

1. Connect to a wallet on Avalanche, e.g. MetaMask, and load the Dashboard. Notice that the default assets are correctly set to the AVAX/WETH pair.

Switching wallets resets `ethNetwork`, and thus triggers default assets to reset:

1. Connect to MetaMask on the Avalanche chain
2. Observe that AVAX is selected as a default asset
3. Switch to a Native wallet.
4. Observe that ETH is now selected, instead of AVAX

### Engineering

See shared instructions above.

### Operations

See shared instructions above.

## Screenshots (if applicable)

N/A

2022-09-02 09:46 UTC, gomesalexandre approved these changes
Tested:

- Switching from Avalanche to Mainnet and back from the ChainMenu / MetaMask
- Switching from Avalanche-connected MetaMask to Native

The correct pair is set, and the previously spotted flash of loading ChainMenu is fixed on page refresh / `ethNetwork` change.

The assets page buy asset bug spotted by @MBMaria in 1.7.0.0 (https://discord.com/channels/554694662431178782/1014978606906212432/1014991273293254706) is also fixed, and the fix also propagates to accounts page.

🪅

2022-09-02 09:46 UTC, gomesalexandre approved these changes
Post-rebase stamp

2022-09-02 10:08 UTC, 0xApotheosis commented
> Post-rebase stamp

Thank you, sir!

2022-09-02 10:48 UTC, gomesalexandre requested changes
Native asset's pages default pairs are rugged, spotted by Cypress 🤖 :

<img width="395" alt="image" src="https://user-images.githubusercontent.com/17035424/188123772-3be4dfa3-7825-4a10-b546-7673abd0f6f5.png">
<img width="390" alt="image" src="https://user-images.githubusercontent.com/17035424/188123825-97c7fb5b-a79e-4d96-811b-65bc89ea85ac.png">

Requesting changes until this is fixed

2022-09-02 10:51 UTC, 0xApotheosis commented
Cypress isn't just an annoying thing that CI does 😀

2022-09-02 11:44 UTC, gomesalexandre commented
> Native asset's pages default pairs are rugged, spotted by Cypress 🤖 :
> 

Fixed in a27ed03b4b0843b6609b882b8ca1eb9924816902

2022-09-02 11:51 UTC, gomesalexandre reviewed
Spotted another bug WRT native assets:

When you switch from one native asset to another, we optimistically set the buyAssetId to be the one from the new route, resulting in these toasts, and a flicker of the wrong buy asset while reconciliation happens:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/17035424/188135099-3098d02b-0ba6-4745-975a-588fd794668b.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/17035424/188135472-86ea2607-fd4e-491e-ae1c-9cf921877688.png">

2022-09-02 11:55 UTC, gomesalexandre commented
> Spotted another bug WRT native assets:
> 
> When you switch from one native asset to another, we optimistically set the buyAssetId to be the one from the new route, resulting in these toasts, and a flicker of the wrong buy asset while reconciliation happens:
> 
> <img alt="image" width="390" src="https://user-images.githubusercontent.com/17035424/188135099-3098d02b-0ba6-4745-975a-588fd794668b.png">
> 
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/17035424/188135472-86ea2607-fd4e-491e-ae1c-9cf921877688.png">

Fixed in d375e6ee234b1577571707dd3fc88a3836a12b8f - unfortunately `getDerivedStateFromProps` and similar methods are a relic of the past, but `usePrevious()` did the trick here!

2022-09-02 11:57 UTC, gomesalexandre submitted a review, later dismissed
Retested according to the previous testing criteria and with the latest fixes in

2022-09-02 16:18 UTC, 0xdef1cafe requested changes
few good and few bad things here

* evm switching now works smoothly without kicking the user out to the connect wallet screen
* default trade pair works nicely for erc20s

getting a blank trade pair when navigating to the following assets (with a native wallet)

* FOXy - needs elasticswap, hence we need to default to ETH-FOX here
* Cosmos (and by extension probably osmo) - needs thorchain
* All UTXO coins

2022-09-06 08:06 UTC, 0xApotheosis commented
@0xdef1cafe @gomesalexandre issues should be fixed 👌 

Note, now that we use RTK query on `getUsdRate`, the endpoint we hackily use to see if a pair is supported, if you change feature flags (e.g. Thor) you gotta wait 60 seconds before the default assets will correctly reflect the supported assets.

We might want to add logic to clear RTK caches on feature flag change.

2022-09-06 10:12 UTC, gomesalexandre commented on src/components/Trade/services/useDefaultAssetsService.ts
> +    isUninitialized: isBuyAssetFiatRateUninitialized,
💜

2022-09-06 10:13 UTC, gomesalexandre commented on src/components/Trade/hooks/useSwapper/useSwapperV2.ts
> +      // TODO: get the actual receive address instead of the first
🤌

2022-09-06 10:15 UTC, gomesalexandre approved these changes
Tested:

- FOXy - correctly defaults to ETH-FOX
- ATOM and OSMO - correctly default to ETH-FOX both with the Thor flag on/off on MM, and ATOM<>OSMO with native and the Thor flag on/off.
- UTXOs - correctly default to ETH-<UTXO> with the Thor flag on and Native Wallet, and ETH-FOX with the flag off / MetaMask and `Thor` on
- Native assets - correctly default to ETH-FOX/AVAX-WETH and routing from one to the other properly reconciliates pairs
- ERC20s/.e - correctly default to (ETH|AVAX)/<Token> and routing from one token to the other (either on the same chain or on another) properly reconciliates pairs

Note, re: `if you change feature flags (e.g. Thor) you gotta wait 60 seconds before the default assets will correctly reflect the supported assets.` - tested with restarting the app after updating the `Thor` flag for testing, since invalidation seems to be a bit flaky currently.
Not considering this a blocker since as you've mentioned, we want to introduce `refetch()` on flags change as a feature.

2022-09-06 10:16 UTC, merged