feat: wire up yearn deposit screen
shapeshift/web pull request #275
Opened 2021-11-01 21:22 UTC by technojak

## Description

feat: wire up yearn deposit screen

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [ ] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/orgs/shapeshift/projects/3#card-71075268
closes https://github.com/orgs/shapeshift/projects/3#card-71074138

2021-11-01 21:30 UTC, reallybeard approved these changes

2021-11-01 21:31 UTC, theoboldfrazier approved these changes

2021-11-01 23:23 UTC, 0xdef1cafe requested changes

2021-11-01 23:23 UTC, 0xdef1cafe commented on src/context/EarnManagerProvider/providers/yearn/components/YearnManager/YearnManager.tsx
> +        providerUrl: process.env.REACT_APP_ETHEREUM_NODE_URL!
get this from config not off process.env

2021-11-02 16:00 UTC, 0xdef1cafe approved these changes

2021-11-02 16:35 UTC, merged