feat: show welcome modal when wallet imported
shapeshift/web pull request #2769
Opened 2022-09-15 20:04 UTC by reallybeard

## Description

On mobile when the wallet is imported successfully, we will show a welcome modal that will ask the user to backup their recovery phrase or allow them to skip it. This should only fire on the import of the wallet.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #2754 

## Risk

By default this modal is not set to show, but once that event fires it will show. There is a risk that it blocks the user from entering their passphrase via modal stacking.

## Testing

Import mobile wallet, on success you should see this welcome modal.

### Engineering

We are using the store to dispatch a change to user preferences `setWelcomeModal` we set that to `true` and when they hit continue or dismiss we set it to false.
 
### Operations

Import mobile wallet, on success you should see this welcome modal.

Close and re-open the app, to confirm that you do not see this modal again.

## Screenshots (if applicable)

2022-09-15 21:07 UTC, gomesalexandre commented on src/state/slices/preferencesSlice/preferencesSlice.ts
> +    setWelcomeModal(state, { payload }: { payload: { show: boolean } }) {
Nitpick but `setShowWelcomeModal` would be more declarative and avoid calling `setWelcomeModal` with an object, but totally happy with this implementation

2022-09-15 21:13 UTC, gomesalexandre requested changes
Conceptual stamp as logic looks sane, added a few requested changes, once this is cleaned up let's get this in

2022-09-15 21:13 UTC, gomesalexandre commented on src/components/Modals/MobileWelcome/views/Notice.tsx
> +  const handleDismissClick = () => {
`useCallback()`, I'm not so concerned if existing event handlers aren't tackled in PRs, but any event handlers or expressions passed down as props which are not memoized make it harder for us to get full memoization across the app (https://github.com/shapeshift/web/pull/2699) in

2022-09-15 21:13 UTC, gomesalexandre commented on src/components/Modals/MobileWelcome/views/Notice.tsx
>    const handleRecoveryClick = () => {
Not required for this PR but as this was touched, can we `useCallback()` while at it?

2022-09-15 21:13 UTC, gomesalexandre commented on src/components/Layout/Header/Header.tsx
> +              <Button onClick={() => mobileWelcomeModal.open({})}>Fire Some shit</Button>
Revert file

2022-09-15 21:13 UTC, gomesalexandre commented on src/App.tsx
> +    if (showWelcomeModal) {
For extra safety
```suggestion
    if (showWelcomeModal && !isWelcomeModalOpen) {
```

2022-09-15 21:13 UTC, gomesalexandre commented on src/App.tsx
> +  const { mobileWelcomeModal } = useModal()
```suggestion
  const { mobileWelcomeModal, isOpen: isWelcomeModalOpen } = useModal()
```

2022-09-15 21:21 UTC, gomesalexandre submitted a review, later dismissed

2022-09-16 09:20 UTC, gomesalexandre approved these changes
Re-stamp after the origin/develop merge and the removal of duplicated env config key following said merge

2022-09-18 10:02 UTC, cjthompson commented
Mobile wallets don't have passwords so you won't get a password modal stacking.

@reallybeard were you able to test this? If not, I can.

2022-09-19 14:11 UTC, reallybeard commented
> Mobile wallets don't have passwords so you won't get a password modal stacking.
> 
> @reallybeard were you able to test this? If not, I can.

@cjthompson I was only able to test if it got triggered manually. Would be great if you could test it in the app.

2022-09-22 16:27 UTC, 0xdef1cafe approved these changes

2022-09-22 16:57 UTC, merged