fix: clear stale values on asset toggle
shapeshift/web pull request #2918
Opened 2022-09-30 09:39 UTC by 0xApotheosis

## Description

When toggling assets in `swapperV2` there are a few UI issues that surface when a `useEffect` doesn't fire when expected, or a quote or rate request fails/takes a long time to return.

This can be observed with the gas fee or rate (1 ETH = 333 POO) where they will briefly flash an incorrect value when toggling assets. In some case the they will stay an incorrect value.

This PR clears values we know become stale when an asset changes so they are never shown to the user.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A - general swapper improvement.

## Risk

Minimal - only clears swapper data that is stale.

## Testing

With `swapperV2` enabled, notice that when toggling assets we don't get a flash of incorrect values in the rate or gas fields.

### Engineering

As above.

### Operations

As above.

## Screenshots (if applicable)

N/A

2022-09-30 14:48 UTC, gomesalexandre approved these changes
Tested against develop with ZRX and CoW (no gas fees) and this properly resets stale values on asset toggle

I've noticed that the flash of unstyled content while the form data is cleared and the new data is being populated is now also happening on the gas, fees, input amounts and expected amount, I don't consider this one to be a blocker per se so here's a 🎟️ 

https://user-images.githubusercontent.com/17035424/193296189-27f2054a-a0e5-4b41-aba3-0c473687c7ba.mov

2022-09-30 17:25 UTC, 0xdef1cafe requested changes
this fixes the trilly dollar fees bug, but unfortunately breaks when toggling assets, we get in a state where we never refetch a quote

2022-10-03 00:13 UTC, 0xdef1cafe approved these changes

2022-10-03 00:13 UTC, merged

2022-10-03 01:33 UTC, 0xApotheosis commented
Merged as it's a strict improvement on the as-is, but we still need to tackle the case where we don't have quotes and ensure we trigger a request.