Revert "fix: revert #2898"
shapeshift/web pull request #3010
Opened 2022-10-07 22:00 UTC by brymut

This reverts commit 7a91b4d768f1a541d216c9679c5b4fed3ef5d320.

## Description

This PR is to revert, recent revert of changes made during #2898.

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2022-10-08 01:37 UTC, cjthompson approved these changes

2022-10-08 01:58 UTC, 0xdef1cafe requested changes
requesting changes until ops has a chance to retest this on an ephemeral branch

2022-10-10 20:56 UTC, 0xdef1cafe commented
@brymut putting this back into draft until issues are resolved https://discord.com/channels/554694662431178782/1029122345648009398/1029134133311569950

2022-10-11 20:21 UTC, 0xdef1cafe approved these changes

2022-10-11 20:21 UTC, merged