chore: remove old feat flags
shapeshift/web pull request #3033
Opened 2022-10-11 15:34 UTC by brymut

## Description

Removing old feat flags for:
- `OnRamperFiatRamp`
- `MtPelerinFiatRamp`
- `RainbowCharts`

Using #2861 as guidance reference.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #2995 

## Risk

Lower risk, dealing with technical debt removing old feat flags.

## Testing

- Check list of 

### Engineering

### Operations

## Screenshots (if applicable)

2022-10-11 15:38 UTC, 0xdef1cafe requested changes
@brymut this is completely wrong - did you even read the issue?

2022-10-11 15:59 UTC, brymut commented
> @brymut this is completely wrong - did you even read the issue?

Sorry about that @0xdef1cafe , forgot about the second A/C when I started working. Will fix asap

2022-10-11 16:44 UTC, brymut commented
Could you please have another look @0xdef1cafe ?

2022-10-11 19:04 UTC, 0xdef1cafe requested changes
@brymut

2022-10-11 19:04 UTC, 0xdef1cafe commented on src/config.ts
>    REACT_APP_FEATURE_MTPELERIN_FIAT_RAMP: bool({ default: false }),
?

2022-10-11 23:47 UTC, brymut commented on src/config.ts
>    REACT_APP_FEATURE_MTPELERIN_FIAT_RAMP: bool({ default: false }),
Sorry, having a bad day 😓

2022-10-12 00:45 UTC, 0xApotheosis approved these changes
`OnRamperFiatRamp`, `MtPelerinFiatRamp`, and `RainbowCharts` feature flags no longer appear in codebase, and their respective functionality still works as expected.

2022-10-12 16:57 UTC, 0xdef1cafe approved these changes

2022-10-12 16:57 UTC, merged