feat: limit recent tx on dashboard to 4
shapeshift/web pull request #3578
Opened 2023-01-06 17:50 UTC by reallybeard

## Description

- To make more room for some promo cards in the dashboard sidebar we are going to limit the recent tx history to 4 with a view all link.

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

Shouldn't be too big of a risk

## Testing

### Engineering

### Operations

On the dashboard you should see up to 4 TX --- then you can click the view all link to be taken to the tx history page.

## Screenshots (if applicable)
![Screen Shot 2023-01-06 at 11 48 39 AM](https://user-images.githubusercontent.com/89934888/211069602-9d2d10c2-b78d-417e-b408-c093cf04ab49.png)

2023-01-06 18:02 UTC, 0xdef1cafe commented
<img width="882" alt="image" src="https://user-images.githubusercontent.com/88504456/211071552-2910dc5e-9d5d-4704-9f27-4eb76cbbbafc.png">

2023-01-06 18:03 UTC, 0xdef1cafe requested changes
view all not showing on ~960ish px breakpoint

2023-01-09 16:35 UTC, reallybeard commented
> view all not showing on ~960ish px breakpoint

Tested this on dev without my changes --- still does the same thing locally. But testing on the prod version it doesn't do this. So kinda hard to debug whats going on. 

Regardless my change didn't introduce this issue. @0xdef1cafe

2023-01-09 17:26 UTC, 0xdef1cafe approved these changes

2023-01-09 17:57 UTC, merged