fix: undefined swapper on first render
shapeshift/web pull request #3609
Opened 2023-01-11 05:37 UTC by 0xApotheosis

## Description

**Fixes `undefined` swapper on first render**
Fixes an issue where we would not get a swapper in the first render cycle if the asset pair's swapper supports cross-account trades. 

It's a multi-factorial bug with a simple fix. 

In summary: the bug is a side-effect from the account bug fix, where the early returning on the first render now leaves us with a receive address of `undefined`. This stops the first quote from firing, which stops us from getting a swapper now that getting the best swapper requires a quote - and if we don't have a swapper we show "Invalid Trade Pair". Phew

**Adds commentary for safety**
Adds commentary about logic that could, if changed in an incorrect way, result in an incorrect receive asset being used for a trade (this is now checked for downstream, but _this_ is the root cause of what was going on)

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A - safety first.

## Risk

High risk as this touches account selection.

## Testing

Things to test:

**Bug fix**

When selecting a UTXO asset from the Dashboard, we often display "Invalid Trade Pair" until the form is interacted with.
This should no longer occur.

**Synchronised account selection**

- For swappers that do not support multi-account (`0x` and `CoW Swap`), we should only be able to select the sell asset account. The buy asset should then update to match any selections.
- For swappers that _do_ support multi-account (`THORSwapper` and `Osmosis`), we should be able to select the sell asset account and buy asset accounts independently

**THORTrading**

Out of an abundance of caution, we should do a cross-chain swap on THORChain (i.e. one with a UTXO asset as the receive asset) and ensure that the funds are received.

### Engineering

☝️ 

### Operations

☝️ 

## Screenshots (if applicable)

N/A

2023-01-11 05:40 UTC, 0xApotheosis reviewed
Comments for reviewers.

2023-01-11 05:40 UTC, 0xApotheosis commented on src/components/Trade/hooks/useSwapper/useSwapper.tsx
> +    if (!bestTradeSwapper) return undefined
No runtime changes here, but semantically more correct - if we have no swapper, the disposition of a swapper can be neither `true` or `false`.

2023-01-11 05:40 UTC, 0xApotheosis commented on src/components/Trade/hooks/useAccountsService.tsx
> -      swapperSupportsCrossAccountTrade ? buyAssetAccountId : sellAssetAccountId,
This was part of the incorrect receive account problem, and would occur when, for whatever reason, we did not get a swapper in the first render.

2023-01-11 05:40 UTC, 0xApotheosis commented on src/components/Trade/TradeInput.tsx
> +      setValue('selectedBuyAssetAccountId', accountId)
We now do the dangerous `selectedBuyAssetAccountId` sync here, and be very clear about what we are doing, and why.

2023-01-11 05:59 UTC, elmutt approved these changes

2023-01-11 10:24 UTC, gomesalexandre requested changes
Tested:

#### Thorchain UTXO <-> UTXO - independant sellAssetAccountId / buyAssetAccountId selection working - same accounts

Note accounts 1 and 1 were manually selected here, not autoselected

<img width="411" alt="image" src="https://user-images.githubusercontent.com/17035424/211770294-8532fe40-2471-4c12-b246-6a3496fd32cf.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/17035424/211770350-edf14e2a-c608-4668-a1b1-481d7c54faa5.png">

https://viewblock.io/thorchain/tx/42156C5EB71F4287E7610DE7B0FDDE7CB9BB897352F496E4C9452261B1E9E53A


#### Thorchain UTXO <-> UTXO - independant sellAssetAccountId / buyAssetAccountId selection working - different accounts

<img width="404" alt="image" src="https://user-images.githubusercontent.com/17035424/211773958-c62ed62a-7ff3-4df9-b0fd-0e0242180bb2.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/17035424/211778767-742b21b4-5199-47f1-8f33-d97095138840.png">

https://viewblock.io/thorchain/tx/E82B6FF24F868B33B1CA973078A2F9C9F80979C23E7BB2D8D0806673ED2E0350

#### CoW swap

- OK, sellAssetAccountId and buyAssetAccountId are synced at input step
- NOK, swap Tx cannot be sent, debugged the failing network request and we're using the account 0 to the `/orders` endpoint, which produces this error message

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/17035424/211782060-33da8e28-e6be-42a9-9580-6bfd78940d9e.png">


<img width="399" alt="image" src="https://user-images.githubusercontent.com/17035424/211779903-6d10f74e-c2b1-458f-a25b-138253c64224.png">

Note, not sure if that was introduced by this PR, but after successfully doing a THOR trade and coming back to the swapper, I'm getting "Invalid Trade Pair" consistently. A full swapper unmount/remount e.g going to another page and back, doesn't fix this, but a page reload does:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/17035424/211773052-37c7ebc4-3d88-4b66-b8f3-c21f411542d8.png">

2023-01-11 10:28 UTC, 0xApotheosis commented
Thanks big gomes, I'll suss that out that CoW thing tomorrow.

2023-01-12 04:59 UTC, 0xApotheosis commented
Closing in favour of https://github.com/shapeshift/web/pull/3617 and https://github.com/shapeshift/web/pull/3625.

2023-01-12 04:59 UTC, closed without merging