fix: add osmosis token send support
shapeshift/web pull request #3858
Opened 2023-02-17 07:42 UTC by pastaghost

## Description

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2023-02-17 10:50 UTC, gomesalexandre commented on src/components/Modals/Send/utils.ts
> +              ...params.chainSpecific,
Can use `lodash/merge` or immer to avoid the deep spread, fine here but a good practice to avoid spread madness

2023-02-17 11:17 UTC, gomesalexandre requested changes
@pastaghost Please test that the Tx value is actually matching the intended one and don't rely on the confirmed toast, this could have been verified through Mintscan or with the Keplr popup, which is showing amounts using again the wrong precision for IBC sends.


<img width="530" alt="image" src="https://user-images.githubusercontent.com/17035424/219635707-8add2d74-e780-4820-9082-879284e1707a.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/17035424/219635718-4e740282-036f-4e4c-bf15-745bc289aff4.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/17035424/219635727-159aa5bb-b2a8-4956-84ef-3f8a1f0bd601.png">
<img width="813" alt="image" src="https://user-images.githubusercontent.com/17035424/219635736-cb61c848-9578-402e-8ce1-cee70e5b1112.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/17035424/219635756-cff72488-f55c-4ba1-9c50-af80354626b7.png">

2023-02-17 22:30 UTC, pastaghost commented
> @pastaghost Please test that the Tx value is actually matching the intended one and don't rely on the confirmed toast, this can be verified through Mintscan or with the Keplr popup, which is showing amounts using again the wrong precision for Osmosis LP tokens sends.
> 
> I've checked on both Keplr and Osmosis and it doesn't seem to be possible to send LP tokens, which would explain why Mintscan shows such 0-balance amount, if that's so the send button should be disabled for those

No, that's not quite right. Cosmos send amounts are denominated in base units. (0.631788)^18 = 631788000000000000, so the send amount shown in the Keplr confirmation is correct. That also matches the Osmosis network representation of LP asset balances. [See here.](https://lcd.osmosis.zone/cosmos/bank/v1beta1/balances/osmo1zjk9dkhzz2waxmtvtl3hnnl0t3ac0k5utyhxgz)
 
If you take another look at the error message you posted, you'll see that it's complaining about insufficient funds, in fact a _zero_ balance for the token you tried to send. That doesn't match your Pool 1 LP token balance as shown in the app, so there must be something else going on. 

The problem is actually the denom. The correct denom for the Pool 1 LP token is 'gamm/pool/1' not 'ibc/gamm/pool/1' as shown in Keplr and on Mintscan for your test transaction. I fixed this by passing the raw denom through in the case that we're trying to send an LP asset and prepending `ibc/` otherwise. 

The Osmosis network doesn't make any distinction between LP tokens and native/IBC tokens as far as sends are concerned, and you can [send](https://www.mintscan.io/osmosis/txs/24AA6BF74DDCE1B6B0A8E762E24143BD8E4D00634D4A398C8ADEA40984EBED94) them just like any other.

<img width="1210" alt="Screenshot 2023-02-17 at 2 56 14 PM" src="https://user-images.githubusercontent.com/62026038/219803377-af207209-dbef-4d57-b8fc-9e12f472b62f.png">


Keplr wallet has separate names for the base-unit and decimal-precision units for each recognized asset. For example:

```javascript
    currencies: [
      {
        coinDenom: "OSMO",
        coinMinimalDenom: "uosmo",
        coinDecimals: 6,
        coinGeckoId: "osmosis",
      },
      {
        coinDenom: "ION",
        coinMinimalDenom: "uion",
        coinDecimals: 6,
        coinGeckoId: "ion",
      },
    ],
```

The asset data is hardcoded in the extension source code. If an asset entry exists, Keplr uses the asset data to format the transaction amounts in decimal-precision format before displaying the send confirmation to the user. If no asset entry exists, the transaction data is passed through as-is. That's why the amount is shown in base units on the Keplr send confirmation screen for Osmosis LP assets but not others.
<img width="426" alt="Screenshot 2023-02-17 at 3 04 27 PM" src="https://user-images.githubusercontent.com/62026038/219804651-3f5fc72b-4080-47ac-a072-296d57d42786.png">


This is a UI problem on the Keplr side that we can't control, but there is something that we can (should) do about it on our side. Since the network lists [asset balances](https://lcd.osmosis.zone/cosmos/bank/v1beta1/balances/osmo1zjk9dkhzz2waxmtvtl3hnnl0t3ac0k5utyhxgz) in base units along with the base unit denom, we shouldn't be using `gamm/pool/1` when showing the amount in decimal-precision units. Mintscan apparently encountered the same problem and decided to use `GAMM-N` for LP token amounts in decimal-precision and `gamm/pool/n` for LP token amounts in base units - I think we should follow suit. This will resolve any ambiguity in the web app and keep the UI consistent with Mintscan. CC: @DiggyDiggy2 @reallybeard 
<img width="1176" alt="Screenshot 2023-02-17 at 3 12 20 PM" src="https://user-images.githubusercontent.com/62026038/219805242-b424ee0f-ffdd-4a99-b1fa-51f9e249d7f0.png">

2023-02-20 09:55 UTC, gomesalexandre approved these changes
Tested again locally, LGTM, both "regular" IBC tokens as well as LP tokens are sent

<img width="347" alt="image" src="https://user-images.githubusercontent.com/17035424/220072240-275ce5db-bf86-4ebb-9576-c1810c87eeeb.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/17035424/220072471-1a55101b-83c6-44e6-9693-ef3eb3f702d1.png">

2023-02-20 09:55 UTC, merged