update favico and include brand assets (issue #17)
shapeshift/web pull request #39
Opened 2021-09-01 21:58 UTC by 420coupe

#17

2021-09-01 22:15 UTC, 0xdef1cafe requested changes

2021-09-01 22:15 UTC, 0xdef1cafe commented on public/manifest.json
> +  "name": "Shapeshift web app",
```suggestion
  "short_name": "ShapeShift",
  "name": "ShapeShift",
```

2021-09-01 22:15 UTC, 0xdef1cafe commented
ty for the first community contribution PR!

can i request that you remove the .eps file as it's not referenced anywhere?

2021-09-02 14:41 UTC, bootsboogie approved these changes

2021-09-02 15:22 UTC, 0xdef1cafe approved these changes

2021-09-02 15:23 UTC, merged