feat: mixpanel events for osmosis
shapeshift/web pull request #4027
Opened 2023-03-14 20:37 UTC by reallybeard

## Description

Add events for the osmosis LP opportunity
- Deposit
- Withdraw

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

No logic was changed, but I did bundle some properties for the withdraw step so possible small risk there.

## Testing

### Engineering

### Operations

Test deposits and withdraws and confirm they work as normal.

## Screenshots (if applicable)

2023-03-15 11:04 UTC, gomesalexandre commented on src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/LpDepositCommon.ts
> +  underlyingAsset1: OsmosisToken & { fiatAmont: string; amountCryptoHuman: string }
We should be able to derive both of these in-place?

2023-03-15 11:05 UTC, gomesalexandre commented on src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/LpWithdrawCommon.ts
> +  fiatAmount: string
Ditto should be able to derive the newly added crypto human amounts and fiat amount

2023-03-15 11:08 UTC, gomesalexandre reviewed
@reallybeard let's pile and discuss this one out - in general, the least reliance we have on form state fields except for the most atomic fields (e.g crypto amount, in base unit ideally), the better.
Selectors would be the ideal option, though Osmosis LP was implemented in a non-standard way with a lot of component-level derivation logic which really should belong in selectors. Happy to discuss a way to either move the logic to selectors (mightn't be a far stretch for the scope of this PR) or reuse the derivation logic in all components.

2023-03-15 16:03 UTC, gomesalexandre commented on src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Deposit.tsx
> +            fiatAmont: formValues.fiatAmount1,
ser

2023-03-15 16:07 UTC, 0xdef1cafe commented on src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Deposit.tsx
> +            fiatAmont: formValues.fiatAmount1,
fiatAMONT

2023-03-15 18:15 UTC, gomesalexandre commented on src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Confirm.tsx
> +              amountCryptoHuman:
If we're calling this human it should be a human value e.g stripped digits, let's call it precision for consistency?

2023-03-15 18:16 UTC, gomesalexandre commented on src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Confirm.tsx
> +      cryptoAmountBaseUnit: state.withdraw.shareInAmountBaseUnit,
No need to tackle it in your PR but since the `shareInAmountBaseUnit` naming was turbo confusing to figure out, let's rename it in a follow-up

2023-03-15 18:20 UTC, gomesalexandre commented on src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Confirm.tsx
> +              amountCryptoHuman:
Disregard me, just tried a LSP rename on that bad boy and there would be a *lot* of updates, also, it is sometimes human, sometimes not

2023-03-15 18:40 UTC, gomesalexandre requested changes
Tested locally, both underlying assets' crypto and fiat amounts are off by many many dp

<img width="465" alt="image" src="https://user-images.githubusercontent.com/17035424/225409354-b5b11b4e-2bed-46db-914d-2beb1bb313ae.png">

2023-03-16 21:33 UTC, gomesalexandre approved these changes
Retested locally, LGTM

2023-03-16 21:37 UTC, merged