feat: add pageview event
shapeshift/web pull request #4054
Opened 2023-03-16 16:27 UTC by reallybeard

## Description

- Track page views

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #4044 

## Risk

## Testing

### Engineering

### Operations

No testing required

## Screenshots (if applicable)

2023-03-16 16:46 UTC, 0xdef1cafe requested changes

2023-03-17 06:36 UTC, gomesalexandre submitted a review, later dismissed
Tested locally:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/17035424/225829656-c9467ae2-b045-43c8-bc14-0aab783ed6f8.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/17035424/225829730-99aff4bd-b991-4140-a9e6-46dcdccbf55f.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/17035424/225829764-af1732f9-b65b-4cb4-aa70-d3ed8e610d41.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/17035424/225829822-e29a343f-52b8-4318-bb5d-16a0d6309afd.png">
<img width="474" alt="image" src="https://user-images.githubusercontent.com/17035424/225829892-a4bc8914-5693-47a3-9801-f85a1168c9ee.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/17035424/225829955-cc36a832-1aab-4cd5-bbcd-f5b54065ec98.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/17035424/225830013-5981f68b-7e5e-4669-aa16-945c4379a28c.png">
<img width="518" alt="image" src="https://user-images.githubusercontent.com/17035424/225830110-ab725289-90bf-4cbf-b6a1-e185354c0dc7.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/17035424/225830163-69bddd98-1a5d-4efa-aba9-2f35f93659bf.png">
<img width="491" alt="image" src="https://user-images.githubusercontent.com/17035424/225830257-92016838-fb55-47a1-aaf1-b5e75a2ac51a.png">

Looks like deserialization is borked for Osmosis LP asset pages however:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/17035424/225830581-7e4f58be-4ba8-48d4-8a34-e045f1493c98.png">

2023-03-17 07:44 UTC, gomesalexandre submitted a review, later dismissed
Retested according to the previous criteria after b3c35b1e14577ce0694f14ec8c1516dd54d3403a, confirmed no regression and this now also works for Osmo LP CAIP-19s

2023-03-17 07:48 UTC, gomesalexandre approved these changes

2023-03-17 07:53 UTC, merged