chore: bump hdwallet to support additional KK assets
shapeshift/web pull request #4146
Opened 2023-03-28 22:19 UTC by 0xdef1cafe

## Description

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2023-03-28 22:48 UTC, gomesalexandre requested changes
Wasn't able to test BSC as node is currently down both on dev and prod, only Avalanche and Optimism.

AVAX doesn't look happy after updating to the latest firmware:

- AVAX is displayed as "UNKN" on KK

- Tx fails and is deriving the wrong address as a from when doing a self-send

<img width="1088" alt="Screenshot 2023-03-29 at 00 36 43" src="https://user-images.githubusercontent.com/17035424/228382314-3631d740-a349-4223-9da6-1e42574eeafe.png">
<img width="386" alt="Screenshot 2023-03-29 at 00 36 26" src="https://user-images.githubusercontent.com/17035424/228382322-c3393333-7c1f-4d5c-bbbf-5d57d7a20290.png">

- Optimism is similarly showing "UNKN" as a symbol when sending ETH, though the Tx goes through successfully

<img width="821" alt="image" src="https://user-images.githubusercontent.com/17035424/228383506-6cb46d5a-02c2-4a0d-969a-bf52515290c9.png">

2023-03-28 22:52 UTC, 0xApotheosis reviewed
Sending on Optimism ✅ 

https://optimistic.etherscan.io/tx/0x07641dfe33a33c2587c27a27b103e0dd81a0d57a49a6725301eaea9e59824357

However, UNKN symbol is shown on KeepKey.

![IMG_2227](https://user-images.githubusercontent.com/97164662/228384403-3ea150e9-5793-4e82-a513-6dbefbb780df.jpeg)


Sending on Avalanche ❌ 

UNKN symbol is shown on KeepKey, then:

```json
{
    "message": "insufficient funds for gas * price + value: address 0xE9850d44c2528AfC61D2cbf209e275d36f6b66cd have (0) want (2279822348711803)"
}
```

Haven't been able to test BSC yet.

2023-04-12 16:33 UTC, 0xdef1cafe commented
confirmed BSC and OP sends are working on KK, avalanche not supported in this PR

2023-04-12 16:55 UTC, gomesalexandre approved these changes

2023-04-12 17:07 UTC, merged