feat: tail halted swappers
shapeshift/web pull request #4158
Opened 2023-03-30 06:27 UTC by 0xApotheosis

## Description

When multiple swappers are available, we want to show halted swappers last in the list (even if they have the best rate). The list order is also used to determine the initial (active) swapper selection, which should be the best non-halted swapper.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Contributes to https://github.com/shapeshift/web/issues/3468.

## Risk

Small. If we are getting all expected swappers, all is well.

## Testing

Enable the REACT_APP_FEATURE_TRADE_RATES feature and ensure swappers are shown in the correct order, and that all expected swappers are listed.

### Engineering

👆

You could monkey patch the halt flag to false is interested.

### Operations

👆

## Screenshots (if applicable)

N/A

2023-03-30 06:28 UTC, 0xApotheosis commented
Current dependencies on/for this PR:
* develop
  * **PR #4138** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4138" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4158** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4158" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #4159** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4159" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4158?utm_source=stack-comment).

2023-03-30 15:59 UTC, 0xdef1cafe commented
two questions

a) are these marked as such in the UI? and
b) should we display these at all? @reallybeard

2023-03-31 04:49 UTC, 0xApotheosis commented
implemented the above proposed change in https://github.com/shapeshift/web/pull/4158/commits/6438d5c34396f20f7e4cd5e588cc6f00568df6e6.

2023-03-31 10:39 UTC, gomesalexandre requested changes
Core logic WRT to the tail/displaying halted only if they're the available option looks good, though the partitioning is currently broken, see below.

Tested:

- by 🐒 patching `isTradingActive` return value to false on THOR swapper

<img width="653" alt="image" src="https://user-images.githubusercontent.com/17035424/229084263-c2664e01-0835-452a-99d7-428401ee1c67.png">

- by 🐒 patching `isTradingActive` return value to false on other swappers (but not THOR), and removing the `if (isThorSwapper) {} else {}` flow in here:

https://github.com/shapeshift/web/blob/bd2a7334f89048270884aae56f8308dbed8a6b77/src/components/Trade/hooks/useAvailableSwappers.tsx#L105

<img width="605" alt="image" src="https://user-images.githubusercontent.com/17035424/229087499-da72ea18-bbfb-4e17-9f83-4c8e122d5f2d.png">

As can be seen in the screenshots above, halted state seemed to have no effect on the actual rendering logic, despite being correct on the RTK layer / view-layer RTK query selection.

Tried monkey patching both `isActiveTrading` branches to false as a sanity check and noticed `partitionnedSwapperPromises` tuple still only gives an array of `active` swappers.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/17035424/229088768-6e10eb21-2477-4598-9903-533426d53f12.png">

After debugging this, looks like `partition` doesn't play well with async predicates, and we'd have to either
- pass it an actual function not a Promise, i.e produce an augmented flavor of `swappersWithQuoteMetadata` with active status so that it is synchronous
- or do the partitioning logic manually with an async map/reduce of sorts, e.g:

```diff
diff --git a/src/components/Trade/hooks/useAvailableSwappers.tsx b/src/components/Trade/hooks/useAvailableSwappers.tsx
index bbb964593..6bb9cf15e 100644
--- a/src/components/Trade/hooks/useAvailableSwappers.tsx
+++ b/src/components/Trade/hooks/useAvailableSwappers.tsx
@@ -1,10 +1,13 @@
-import type { GetSwappersWithQuoteMetadataReturn } from '@shapeshiftoss/swapper'
-import { SwapperName } from '@shapeshiftoss/swapper'
-import { partition } from 'lodash'
+import type {
+  GetSwappersWithQuoteMetadataReturn,
+  SwapperWithQuoteMetadata,
+} from '@shapeshiftoss/swapper'
+// import { SwapperName } from '@shapeshiftoss/swapper'
+// import { partition } from 'lodash'
 import { useEffect, useState } from 'react'
 import { getSwapperManager } from 'components/Trade/hooks/useSwapper/swapperManager'
 import { useTradeQuoteService } from 'components/Trade/hooks/useTradeQuoteService'
-import { isFulfilled, isSome } from 'lib/utils'
+import { isSome } from 'lib/utils'
 import { getIsTradingActiveApi } from 'state/apis/swapper/getIsTradingActiveApi'
 import { getSwappersApi } from 'state/apis/swapper/getSwappersApi'
 import { selectFeeAssetByChainId } from 'state/slices/assetsSlice/selectors'
@@ -97,42 +100,46 @@ export const useAvailableSwappers = () => {
         The available swappers endpoint returns all available swappers for a given trade pair, ordered by rate, including halted.
         A halted swapper may well have the best rate, but we don't want to show it unless there are none other available.
        */
-      const partitionedSwapperPromises = await Promise.allSettled(
-        partition(swappersWithQuoteMetadata, async swapperWithQuoteMetadata => {
+      const active: SwapperWithQuoteMetadata[] = []
+      const halted: SwapperWithQuoteMetadata[] = []
+      await Promise.allSettled(
+        swappersWithQuoteMetadata.map(async swapperWithQuoteMetadata => {
           const activeSwapper = swapperWithQuoteMetadata.swapper
-          const isThorSwapper = activeSwapper.name === SwapperName.Thorchain
+          // const isThorSwapper = activeSwapper.name === SwapperName.Thorchain
           // Avoid unnecessary network requests unless we have a THORChain swapper
-          if (isThorSwapper) {
-            const isTradingActiveOnSellPoolResult =
-              sellAssetId &&
-              activeSwapper &&
-              (
-                await dispatch(
-                  getIsTradingActive.initiate({
-                    assetId: sellAssetId,
-                    swapperName: activeSwapper.name,
-                  }),
-                )
-              ).data
+          const isTradingActiveOnSellPoolResult =
+            sellAssetId &&
+            activeSwapper &&
+            (
+              await dispatch(
+                getIsTradingActive.initiate({
+                  assetId: sellAssetId,
+                  swapperName: activeSwapper.name,
+                }),
+              )
+            ).data
+
+          const isTradingActiveOnBuyPoolResult =
+            buyAssetId &&
+            activeSwapper &&
+            (
+              await dispatch(
+                getIsTradingActive.initiate({
+                  assetId: buyAssetId,
+                  swapperName: activeSwapper.name,
+                }),
+              )
+            ).data
 
-            const isTradingActiveOnBuyPoolResult =
-              buyAssetId &&
-              activeSwapper &&
-              (
-                await dispatch(
-                  getIsTradingActive.initiate({
-                    assetId: buyAssetId,
-                    swapperName: activeSwapper.name,
-                  }),
-                )
-              ).data
-            return !!isTradingActiveOnSellPoolResult && !!isTradingActiveOnBuyPoolResult
-          } else return true
+          const isActive = !!isTradingActiveOnSellPoolResult && !!isTradingActiveOnBuyPoolResult
+          if (isActive) {
+            active.push(swapperWithQuoteMetadata)
+          } else {
+            halted.push(swapperWithQuoteMetadata)
+          }
         }),
       )
 
-      const [active, halted] = partitionedSwapperPromises.filter(isFulfilled).map(p => p.value)
-
       /*
         If we have active swappers, show only them. Else, show any halted swappers so the user knows the trade pair
         is actually supported by us, it's just currently halted.
```

Using this diff (the `isThorSwapper` related bits are commented out for testing so we can monkey patch in/active state on any swapper), the partition is now happy:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/17035424/229097156-2c8e00e6-00e2-45d8-a500-2c0022ffa715.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/17035424/229097297-069cac9b-18c0-4e7f-a926-6bcd98d5a975.png">

<img width="465" alt="image" src="https://user-images.githubusercontent.com/17035424/229097918-082d490c-9b45-4200-bafb-42f946edd149.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/17035424/229097954-97d65593-f9c3-442c-866a-b211136b1657.png">

<img width="465" alt="image" src="https://user-images.githubusercontent.com/17035424/229098052-7beb7451-cdfb-4b8a-81fa-2cfa9ce8f11d.png">
<img width="645" alt="image" src="https://user-images.githubusercontent.com/17035424/229098081-237ac52f-2fb6-4390-a451-555d66c05b5d.png">

2023-03-31 10:44 UTC, gomesalexandre commented on src/components/Trade/hooks/useAvailableSwappers.tsx
> +      const [active, halted] = partitionedSwapperPromises.filter(isFulfilled).map(p => p.value)
We should also be able to remove the `isFulfilled` / `allSettled` bits: https://redux-toolkit.js.org/api/createAsyncThunk

RTK async thunks will never reject, so `Promise.all()` is effectively guaranteeing resolved promises (with monadic error-handling being done within their inner value)

2023-04-01 09:44 UTC, gomesalexandre approved these changes
Agreed with @0xApotheosis to commit the manual partitioning - 4b0d958eb0d7c53a24c8990d0339831e1f25407b. Also used `Promise.all()` instead of `Promise.allSettled()` as async thunks can't reject (and we don't care about the resolved value of the promises anymore, only executing them) - f0fd7e884ba524695aff14ff4759d5d1babef2f0.

Retested and LGTM now!

re @0xdef1cafe

> > two questions
> 
> a) are these marked as such in the UI?
> b) should we display these at all? @reallybeard

They are marked in the UI on the trade button with the "halted" translation if that swapper is selected (which I think is sane UX).

I believe we could improve the UX further here by showing a red border color instead of the current green one when a halted swapper is the only available one, thus is selected (green currently), though the halted state might be enough for that.

But let's get this one in in this current state 🤌

2023-04-01 10:05 UTC, merged

2023-04-03 02:07 UTC, 0xApotheosis commented
Nice suggestion on the colors @gomesalexandre - added in https://github.com/shapeshift/web/pull/4176.