fix: cowswap receive amount
shapeshift/web pull request #4448
Opened 2023-05-08 10:24 UTC by 0xApotheosis

## Description

Fixes a bug where we double counting the CoW Swap fee, which was causing us to show lower-than-actual receive amounts for CoW Swap quotes.

Also improves naming throughout to better convey the data each constant holds.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

Small/medium. If CoW Swap quotes look sane, we should be gravy.

## Testing

Check our CoW Swap quotes against https://swap.cow.fi/ and confirm that they are similar (they will be slighly different due to rounding/fiat conversions etc).

### Engineering

☝️

Check the response to the https://api.cow.fi/mainnet/api/v1/quote POST request (the "sell" kind.

The `buyAmount` field should roughly match that which we are showing in the "You get" amount. 

### Operations

☝️

## Screenshots (if applicable)

N/A

2023-05-08 10:24 UTC, 0xApotheosis commented
Current dependencies on/for this PR:
* develop
  * **PR #4448** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4448" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4448?utm_source=stack-comment).

2023-05-09 03:49 UTC, woodenfurniture commented on src/lib/swapper/swappers/CowSwapper/cowBuildTrade/cowBuildTrade.test.ts
> +  buyAmountBeforeFeesCryptoBaseUnit: '14707533959600717283163', // 14501 FOX
```suggestion
  buyAmountBeforeFeesCryptoBaseUnit: '14707533959600717283163', // 14707 FOX
```

2023-05-09 04:17 UTC, woodenfurniture requested changes
seeing a couple issues with the amounts when running locally
- gas fee appearing as 0
- it seems that the gas fee is being subtracted from the sell amount on cowswap's side -- `47914924+34726523 = 82641447`, but the other swappers add the gas fee separately

![image](https://user-images.githubusercontent.com/125113430/236991863-92c9fc60-6235-4637-bc2e-1aa1b913c30f.png)

2023-05-09 04:26 UTC, 0xApotheosis commented
The gas fee on CoW swaps _is_ 0, ser 👌

2023-05-09 04:47 UTC, woodenfurniture approved these changes

2023-05-09 04:47 UTC, merged