feat: empty portfolio allow to receive without an asset selected
shapeshift/web pull request #451
Opened 2021-11-18 22:41 UTC by reallybeard

## Description

- Needed a way to receive an asset without one selected
- Added empty account list
- Fixed some key warnings

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [ ] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. etc...

## Screenshots (if applicable
![Screen Shot 2021-11-18 at 4 35 57 PM](https://user-images.githubusercontent.com/89934888/142508259-dc98904d-8219-4463-abcc-a951492be409.png)
![Screen Shot 2021-11-18 at 4 36 02 PM](https://user-images.githubusercontent.com/89934888/142508263-b23de3d2-9bcc-416d-bc84-b4afb40d4263.png)
![Screen Shot 2021-11-18 at 4 36 06 PM](https://user-images.githubusercontent.com/89934888/142508264-1d4c5a92-90f5-4a41-b306-8ba71d3247fc.png)
)

2021-11-18 22:45 UTC, 0xdef1cafe commented on package.json
> +    "yarn": "^1.22.17"
?

2021-11-18 22:46 UTC, 0xdef1cafe commented on package.json
> +    "add": "^2.0.6",
?

2021-11-18 22:47 UTC, 0xdef1cafe requested changes
yarn add yarn add?

2021-11-18 23:11 UTC, elmutt approved these changes

2021-11-19 16:56 UTC, 0xdef1cafe commented
tested and this look fuckin rad we should merge today

2021-11-19 16:56 UTC, 0xdef1cafe approved these changes

2021-11-19 16:57 UTC, merged