fix: don't show update message on localhost
shapeshift/web pull request #506
Opened 2021-11-24 18:48 UTC by 0xdef1cafe

2021-11-24 19:05 UTC, reidrankin approved these changes

2021-11-24 19:08 UTC, reidrankin requested changes

2021-11-24 19:08 UTC, reidrankin commented on src/hooks/useHasAppUpdated/useHasAppUpdated.ts
> +    if (window.location.hostname === 'localhost') return
introducing a dependency on `window.location.hostname` seems brittle to me; how about checking an env var?
```suggestion
    if (process.env.NODE_ENV !== 'production') return
```

2021-11-24 22:58 UTC, reidrankin approved these changes

2021-11-24 23:08 UTC, theoboldfrazier approved these changes

2021-11-30 16:41 UTC, elmutt approved these changes

2021-11-30 19:11 UTC, natven approved these changes
🍭

2021-11-30 21:44 UTC, merged