Fix metamask connect
shapeshift/web pull request #525
Opened 2021-12-01 17:06 UTC by pastaghost

## Description

Please describe your changes

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [ ] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. etc...

## Screenshots (if applicable)

2021-12-01 19:24 UTC, cjthompson commented on src/context/WalletProvider/components/RedirectModal.tsx
> +  onClickAction(): any
```suggestion
  onClickAction(): () => any
```

2021-12-01 19:24 UTC, cjthompson commented on src/context/WalletProvider/components/RedirectModal.tsx
> +  children?: any
Should probably be typed to ReactComponent or something similar

2021-12-03 16:46 UTC, 0xdef1cafe commented on src/context/WalletProvider/components/RedirectModal.tsx
> +export const RedirectModal = (props: RedirectModalProps) => {
```suggestion
export const RedirectModal: React.FC<RedirectModalProps> = props => {
```

2021-12-03 16:47 UTC, 0xdef1cafe requested changes
suggestions

2021-12-03 16:48 UTC, theoboldfrazier approved these changes

2021-12-03 17:06 UTC, 0xdef1cafe approved these changes

2021-12-03 17:15 UTC, merged