chore: fix typos
shapeshift/web pull request #5428
Opened 2023-10-06 06:32 UTC by omahs

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2023-10-08 22:28 UTC, woodenfurniture commented on src/assets/translations/de/main.json
> +    "rewards": "Belohnungen",
it seems this key isnt used any more so can be removed from all `main.json`

2023-10-08 22:30 UTC, woodenfurniture requested changes
TY for the the PR ser, lets get that unused entry removed, fill in the PR template and get this in 🍻

2023-10-09 06:36 UTC, omahs commented
@woodenfurniture Done ser! 🍻

2023-10-09 23:37 UTC, woodenfurniture approved these changes

2023-10-09 23:42 UTC, merged

2023-10-10 21:46 UTC, firebomb1 commented
@woodenfurniture gm, I've only noticed this PR now, it would be better to not alter the translations files manually as they are generated from Gitlocalize (our translation platform) and in the past it caused issues with synchronization.

If coincidentally translators were to work on the same strings that got modified here, the changes they made could potentially get overwritten when we update the repo used for Gitlocalize if we don't notice such PR. So if changes are needed in translations, please inform us in [#engineering-translations](https://discord.com/channels/554694662431178782/1001570348380200980) or in any #global channel, I can include them in our fork in due time and later push them during a weekly sync so we avoid these issues.

Lastly, `en/main.json` is our *source of truth* when it comes to Gitlocalize, when you delete a key from the English file it will automatically get deleted in all the translation files, so it shouldn't be necessary to manually delete them in each one.