Use dompurify to remove link html from assets
shapeshift/web pull request #58
Opened 2021-09-03 03:43 UTC by unclerom

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #15 

## Description

Please describe your changes

Added `dompurify` to remove `<script>` and `<a>` tags from description

Still uses `dangerouslySetInnerHTML` so worth a discussion if necessary

Please outline all testing steps

Open asset page, see text

## Screenshots (if applicable)

2021-09-03 18:51 UTC, bootsboogie approved these changes
LGTM!

2021-09-08 16:39 UTC, 0xdef1cafe requested changes

2021-09-08 16:39 UTC, 0xdef1cafe commented on src/pages/Assets/AssetDetails/AssetHeader.tsx
> +  const sanitizedDescription = sanitize(description ?? '', {
as discussed please add tooltips for links that have been removed

2021-09-17 18:06 UTC, 0xdef1cafe approved these changes

2021-09-17 18:23 UTC, TrancelikeTechno approved these changes

2021-09-17 18:23 UTC, technojak approved these changes

2021-09-17 19:16 UTC, merged