feat: swapper invalidate queries
shapeshift/web pull request #5839
Opened 2023-12-12 21:06 UTC by gomesalexandre

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2023-12-12 21:06 UTC, gomesalexandre commented
Current dependencies on/for this PR:
* `develop`
  * **PR #5837** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5837?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #5839** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5839?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5839?utm_source=stack-comment).

2023-12-12 21:20 UTC, gomesalexandre commented on src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
> +          receiveAddress &&
We shouldn't need this anymore, checking for `receiveAddress` will be enough, and this would rug manual receive address

2023-12-12 21:34 UTC, gomesalexandre commented on src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
> +          receiveAddress &&
eff62f5e7ea6aad4082bbfaa1b57ec3f6fb88bee

2023-12-13 23:47 UTC, 0xApotheosis reviewed
Noting that the issue [mentioned in the PR below](https://github.com/shapeshift/web/pull/5837#pullrequestreview-1780653079) this is resolved by in this PR.

It might be worth merging the stack before merging to `develop`.

2023-12-13 23:59 UTC, 0xApotheosis reviewed
Code-wise looking solid. I'll give another functional test whilst watching the network tab to confirm all is as it should be.

2023-12-14 00:04 UTC, 0xApotheosis requested changes
@gomesalexandre it does seem like the debounce is no longer working correctly.

E.g. if I rapidly input a 4 numbers to do a 4 digit fiat sell amount for a THORChain quote, 4 network requests are made, whereas previously only 1 would be made in this scenario.

I think this is important, as removing this could really increase our API usage, and this bills.

2023-12-14 08:25 UTC, gomesalexandre commented
> @gomesalexandre it does seem like the debounce is no longer working correctly.
> 
> E.g. if I rapidly input a 4 numbers to do a 4 digit fiat sell amount for a THORChain quote, 4 network requests are made, whereas previously only 1 would be made in this scenario.
> 
> I think this is important, as removing this could really increase our API usage, and this bills.

Very nice catch @0xApotheosis - fixed in f8159aac5a by *always* using the debounced flavor of trade quote input, and doing the `shouldRefetchTradeQuotes` checks as a ternary in `useGetTradeQuoteQuery` first arg.

- Network requests in develop when fast fingers is true

https://github.com/shapeshift/web/assets/17035424/b1e5cc59-43a1-4acc-b91d-9e1e891cd9e7

- Network requests in this diff when fast fingers is true


https://github.com/shapeshift/web/assets/17035424/12825e8d-3057-49be-a05c-34b867e5304e

Note one difference compared to develop, which is inherent to us having a debounce in place and now invalidating queries: the previous query will still run once when args change, which AFAIK we can't fix, unless we try to be smart with an effect specifically for tags invalidation instead of running it at the beginning of our main effect here, which brings a lot more risks to the table.

2023-12-15 02:05 UTC, 0xApotheosis reviewed
Re-tested and confirming the previous debounce issue is resolved.

It seems a bit bizarre to me though that we can't fix the additional request for the _old_ quote whenever we start trying to get a new quote? That seems pretty wild...

2023-12-15 07:38 UTC, gomesalexandre commented
> Re-tested and confirming the previous debounce issue is resolved.
> 
> It seems a bit bizarre to me though that we can't fix the additional request for the _old_ quote whenever we start trying to get a new quote? That seems pretty wild...

Agreed that's not a be havior wanted - though that's debounce working as it should now, as we don't wrongly cache queries. Since this is a `useDebounce` behavior, tackled in https://github.com/shapeshift/web/pull/5872 🙏🏽

2023-12-15 22:55 UTC, 0xApotheosis approved these changes
Very happy with this guy now that we have https://github.com/shapeshift/web/pull/5872#pullrequestreview-1785035994 ready 🙏

2023-12-15 22:56 UTC, merged