\
shapeshift/web pull request #6007
Opened 2024-01-16 00:00 UTC by woodenfurniture

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2024-01-16 00:00 UTC, woodenfurniture commented
Current dependencies on/for this PR:
* `develop`
  * **PR #6007** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6007?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/6007?utm_source=stack-comment).

2024-01-16 11:37 UTC, gomesalexandre commented on src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
> +  const marketDataDidLoad = useAppSelector(selectMarketDataDidLoad)
🧠

2024-01-16 11:40 UTC, gomesalexandre commented on src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
> +    const assetIdsSet = new Set(data.supportedSellAssetIds)
Speed 🚀

2024-01-16 11:40 UTC, gomesalexandre commented on src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
> +    const assetIdsSet = new Set(data.supportedSellAssetIds)
blazingly fast 🧠

2024-01-16 12:00 UTC, gomesalexandre requested changes
Tested locally with a full cache clear every test:

- MM (EVM only)

https://github.com/shapeshift/web/assets/17035424/156715e4-9d7c-4058-90c8-585c1c7915b7

- Native


https://github.com/shapeshift/web/assets/17035424/f8eb47d0-1408-4dc0-9374-0db9dd87a4cf

- Native against develop, note how sorting by portfolio balance is now broken 😢 

https://github.com/shapeshift/web/assets/17035424/f0d5937d-e1cc-4ad0-8d2b-4a0b3026261d

Note, switching back and forth from the trade page succesfully sorts by balances/market cap, most likely because of the non-reactivity of https://github.com/shapeshift/web/pull/6007#discussion_r1453308207:


https://github.com/shapeshift/web/assets/17035424/0b28e55a-364c-49d7-88e1-be35db9878a1

2024-01-17 21:32 UTC, gomesalexandre approved these changes
Retested locally, confirmed reactivity rug is fixed 

https://github.com/shapeshift/web/assets/17035424/7d8cfb6e-2626-4517-bcd8-fe344a4d3c63

2024-01-17 22:09 UTC, merged