wip: fetch all LP user data
shapeshift/web pull request #6032
Opened 2024-01-17 20:05 UTC by gomesalexandre

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2024-01-17 20:05 UTC, gomesalexandre commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/shapeshift/web/6032?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `develop`
  * **PR #6028** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6028?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #6030** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6030?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #6032** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6032?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/6032?utm_source=stack-comment).

2024-01-17 22:50 UTC, gomesalexandre commented on src/pages/ThorChainLP/YourPositions.tsx
> +  userPoolData: any // TODO
uh oh

2024-01-17 22:57 UTC, gomesalexandre commented on src/pages/ThorChainLP/YourPositions.tsx
> +  userPoolData: any // TODO
ad53095c088656e9bf2a0890c3782335655e94f2

2024-01-17 23:08 UTC, 0xApotheosis reviewed
First functional note before I review the code is that this PR causes my RUNE aysm LPs to not show anymore.

2024-01-17 23:54 UTC, 0xApotheosis requested changes
Love me some skeletons, though we lose our RUNE asymmetrical pools in the PR.

2024-01-18 09:11 UTC, gomesalexandre commented
> Love me some skeletons, though we lose our RUNE asymmetrical pools in the PR.

This should be happy now! 

<img width="947" alt="image" src="https://github.com/shapeshift/web/assets/17035424/f7c01dda-8c6e-4cbe-bf7c-ed643d94f40e">

- RUNE fix: https://github.com/shapeshift/web/pull/6032/commits/81b688cd58fa13a60356c53edeffb55e8756a108
- Naive deduplication which was needed following the RUNE fix https://github.com/shapeshift/web/pull/6032/commits/36d2afdf4b978030122d62ddd0120c32f3a00bf4
- Less naive deduplication with multi-account future-proofing: https://github.com/shapeshift/web/pull/6032/commits/62a89176ac64395e66527f2aed47e35e7376cf13

2024-01-19 02:40 UTC, 0xApotheosis approved these changes
I'm now seeing all LP positions 🙏

2024-01-19 02:40 UTC, merged