fix: asym/sym logic
shapeshift/web pull request #6039
Opened 2024-01-18 01:50 UTC by 0xApotheosis

## Description

Fixes asym quote estimation logic so pool share and slippage is correct for both sym and asym deposits.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Contributes to https://github.com/shapeshift/web/issues/6019

## Risk

Small - isolated to code paths behind the LP feature flag.

## Testing

Ensure both sym and asym LPs are similar to THOSwap.

### Engineering

☝️

### Operations

Not required at this stage.

## Screenshots (if applicable)

N/A

2024-01-18 09:17 UTC, gomesalexandre commented on src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
> +      // If the pool is asymmetrical the then we are only depositing one asset amount, and the other is zero
```suggestion
      // If the pool is asymmetrical then we are only depositing one asset amount, and the other is zero
```

2024-01-18 09:30 UTC, gomesalexandre requested changes
Tested locally:

### Asym asset side

<img width="516" alt="image" src="https://github.com/shapeshift/web/assets/17035424/917746a0-86fa-43fc-8511-81934a4a1569">
<img width="421" alt="image" src="https://github.com/shapeshift/web/assets/17035424/328c1194-2d23-4e35-88ac-739fa85f315b">

Pool share is now *4 the THORSwap amount 🤯 

### Asym RUNE side

 
<img width="416" alt="image" src="https://github.com/shapeshift/web/assets/17035424/0553bd82-49f6-4c3e-b64d-89e885a17b00">
<img width="508" alt="image" src="https://github.com/shapeshift/web/assets/17035424/1e40cfae-ae6b-4b52-b137-d15caa4ed9a5">

- This is also around *4 the TS pool share amount

### Symmetrical

<img width="427" alt="image" src="https://github.com/shapeshift/web/assets/17035424/df6177ba-ad1d-42ac-af85-b1f9a4e9087f">

- Rebalanced amounts look good, but the pool share is around 3ish times higher than THORSwap

<img width="516" alt="image" src="https://github.com/shapeshift/web/assets/17035424/a269a93e-8229-4736-ad1e-d3642056ac2e">

2024-01-18 22:59 UTC, 0xApotheosis commented
Confirming this got rugged when develop was merged in, will investigate and fix 👌

2024-01-18 23:32 UTC, 0xApotheosis commented
After more investigation, I think @gomesalexandre you might have been checking against BNB on Beacon Chain instead of Smart Chain when using THORSwap (they use different colored asset icons than us).

I'm unable to get a delta from their values.

2024-01-19 08:11 UTC, gomesalexandre approved these changes
Tested again, confirmed I was a derp in my previous pass

### Asym asset

<img width="509" alt="Screenshot 2024-01-19 at 09 07 07" src="https://github.com/shapeshift/web/assets/17035424/68433eae-ce98-467f-92c6-48a4d2c3fa11">
<img width="459" alt="Screenshot 2024-01-19 at 09 07 01" src="https://github.com/shapeshift/web/assets/17035424/4b3d44e0-e1ec-43e1-9229-66e14c21f310">



### Asset RUNE

<img width="445" alt="Screenshot 2024-01-19 at 09 07 35" src="https://github.com/shapeshift/web/assets/17035424/c4f03cb1-a1f0-42ce-a312-296e63e5db1c">
<img width="519" alt="Screenshot 2024-01-19 at 09 07 42" src="https://github.com/shapeshift/web/assets/17035424/232078b5-43d7-4eac-b406-9c8d1c6fd514">

### Sym

<img width="544" alt="Screenshot 2024-01-19 at 09 08 24" src="https://github.com/shapeshift/web/assets/17035424/5b85ce54-b2ce-49fd-91ff-1177970244c1">
<img width="457" alt="Screenshot 2024-01-19 at 09 08 15" src="https://github.com/shapeshift/web/assets/17035424/bc70f9af-7ab3-47ff-8594-77f33062d506">

2024-01-19 14:58 UTC, gomesalexandre commented on src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
> +      // If the pool is asymmetrical the then we are only depositing one asset amount, and the other is zero
a595a9c1aa14d5463d075e1000711222f0064546

2024-01-19 14:58 UTC, gomesalexandre commented on src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
> +      const isAsym = foundPool?.asymSide !== null
a595a9c1aa14d5463d075e1000711222f0064546

2024-01-19 15:56 UTC, merged