feat: utxo scriptType in EquityRow
shapeshift/web pull request #6053
Opened 2024-01-22 11:19 UTC by gomesalexandre

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk
> High Risk PRs Require 2 approvals

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2024-01-22 11:23 UTC, gomesalexandre commented on src/components/Equity/EquityRow.tsx
> +              {subText && <RawText>{subText}</RawText>}
Removed `labelJoined` and moved this in-JSX to avoid having a divider between the subtext and the tag, which would look odd

2024-01-23 00:38 UTC, woodenfurniture requested changes
Correctly showing script type on http://localhost:3000/#/dashboard/accounts
![image](https://github.com/shapeshift/web/assets/125113430/f070a5a0-9e94-46db-aab0-23cd917b944a)

Clicking one of the accounts above, shows placeholder script types on asset page:
http://localhost:3000/#/assets/bip122:000000000019d6689c085ae165831e93/slip44:0
![image](https://github.com/shapeshift/web/assets/125113430/16b88ae1-d173-450d-b73c-c4629be302ae)

Getting placeholder script type when clicking an account:
![image](https://github.com/shapeshift/web/assets/125113430/1d145020-42cc-46a5-8b4a-523c86401452)

When clicking "<- Segwit Native" button on the page above, correct script types do appear:
![image](https://github.com/shapeshift/web/assets/125113430/8778e3c7-0be9-4698-b758-69b6e76ee0eb)

2024-01-23 19:55 UTC, gomesalexandre commented
@woodenfurniture something was definitely off with the diff as we weren't passing AccountIds around, explaining why you were seeing placeholders - fixed in https://github.com/shapeshift/web/pull/6053/commits/3ff91d5113cd5cc1049abc6f6622848c75f010b1 and also added some safety not to render the tag if `!subtitle`

2024-01-23 20:02 UTC, woodenfurniture approved these changes
✅ Script type now appearing instead of placeholder.
![image](https://github.com/shapeshift/web/assets/125113430/d71f8bfd-954e-44f3-b852-c6f7add43d9c)
![image](https://github.com/shapeshift/web/assets/125113430/e3a527a5-6f74-422f-806e-1dbea402cc4d)
![image](https://github.com/shapeshift/web/assets/125113430/42dca9da-9df2-435c-a00a-7bc0ba798123)

✅ Non-utxo accounts dont show script type where they shouldnt
![image](https://github.com/shapeshift/web/assets/125113430/a1d510b3-93f4-40cf-8a5c-054cce287c09)

2024-01-23 20:03 UTC, merged