fix: use proper yvUSDC vault address
shapeshift/web pull request #613
Opened 2021-12-28 14:16 UTC by jdambron

## Description

Use propoer yvUSDC vault address: `0xa354F35829Ae975e850e23e9615b11Da1B3dC4DE`

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #612 

## Testing

1. Visit earn section of app.shapeshift...https://app.shapeshift.com/earn/staking-vaults
2. Notice the APY of USDC
3. Visit Yearn directly: https://yearn.finance/#/vaults
4. Notice the same APY for USDC

## Screenshots (if applicable)

![2021-12-28_15-01](https://user-images.githubusercontent.com/5672954/147575250-4c6dd9e0-2124-4588-bb36-23584a3e3f87.png)
![2021-12-28_15-01_1](https://user-images.githubusercontent.com/5672954/147575258-cfa99817-bc56-4266-9bd4-8ac9beb7563e.png)

2021-12-28 23:52 UTC, 0xean commented
Thanks for the PR @jdambron !

I looked this up and want to confirm with the engineers who worked on the integration.

Looking at the documents it looks like the v2 vault was correct in the original code (prior to your PR).  See here - https://docs.yearn.finance/getting-started/products/yvaults/vault-tokens#v2-yvault-tokens

So maybe the Yearn UI is showing the older v1 vault?

2021-12-29 04:09 UTC, jdambron commented
@0xean you're welcome.

For sure. Let's check that with more knowledgeable engineers than me.

From what I got from the Yearn API it seemed the way to fix the difference in displayed APY, but I may be wrong.

Let me know if I can help.

2022-01-03 18:06 UTC, theoboldfrazier reviewed
We should consider about users that have already deposited into the old vault. I think better than replacing the old one, we should add a new one and differentiate with the symbol being yvUSDC 0.3.0 and yvUSDC 0.4.3

I think on the roadmap we have plans to add migration functionality where users in an old vault can migrate to the new one.

2022-01-03 18:13 UTC, reidrankin commented
Verified 0xa354f35829ae975e850e23e9615b11da1b3dc4de is the latest USDC vault (according to `v2.registry.ychad.eth`)

2022-01-03 18:20 UTC, 0xean commented
@reidrankin - thanks for confirming that, I am inclined to merge this then.

2022-01-03 18:20 UTC, 0xean approved these changes

2022-01-03 18:55 UTC, 0xdef1cafe commented
> We should consider about users that have already deposited into the old vault. I think better than replacing the old one, we should add a new one and differentiate with the symbol being yvUSDC 0.3.0 and yvUSDC 0.4.3
> 
> I think on the roadmap we have plans to add migration functionality where users in an old vault can migrate to the new one.

yeah - this is going to hide balances on the yearn screen for users that have deposited into 0.3.0

@jdambron do you want to make the change that @theoboldfrazier is suggesting so that we can see both vaults, differentiated by their version number in the list?

2022-01-03 18:59 UTC, 0xdef1cafe requested changes

2022-01-03 18:59 UTC, 0xdef1cafe commented on src/features/earn/providers/yearn/constants/vaults.ts
> +    vaultAddress: toLower('0xa354f35829ae975e850e23e9615b11da1b3dc4de'),
see comment, duplicate this vault, name the original `USDC 0.3.0` and the new one `USDC 0.4.3` until we have a migration pathway

2022-01-03 19:51 UTC, jdambron commented
@0xdef1cafe sure. I will have a look at it tomorrow.

2022-01-04 07:49 UTC, jdambron commented
@0xdef1cafe I did the modification to allow both USDC vaults at the same time.
I had to tweak a bit the existing code, as it was coded expecting only one vault for a specific token.

2022-01-05 19:07 UTC, 0xdef1cafe requested changes

2022-01-05 19:07 UTC, 0xdef1cafe commented on src/components/StakingVaults/StakingVaultRow.tsx
> +          {/* TODO Remove USDC 0.3.0 test and special case when we have a migration path */}
thanks for this @jdambron 

could you please implement this in a way such that we're not hard coding a check for the vault name here? e.g. if we have multiple vaults with the same symbol (yvUSDC) we do this conditional rendering, else do the normal rendering?

this just means when yearn releases 0.4.4 or 0.4.whatever we don't have special magic string conditions to update everywhere

2022-01-06 07:45 UTC, jdambron commented
@0xdef1cafe I changed the logic to get the names from the `constant/vaults.ts` file.
It will be more flexible to manage changes on Yearn side (as it will be managed on ours).
I just had to rename the `USD` vault into `YCURVE` to keep the same values displayed.
No more special magic string!

2022-01-06 17:40 UTC, 0xdef1cafe approved these changes

2022-01-06 17:44 UTC, 0xdef1cafe commented
looks great, thanks for the changes!

2022-01-06 17:50 UTC, merged