perf: segregate fungible assets from non-fungible assets
shapeshift/web pull request #6281
Opened 2024-02-25 22:31 UTC by woodenfurniture

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk
> High Risk PRs Require 2 approvals

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2024-02-25 22:31 UTC, woodenfurniture commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/shapeshift/web/6281?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#6281** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6281?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#6272** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6272?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#6230** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6230?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#6176** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6176?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#6213** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6213?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#6171** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6171?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `develop`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/6281?utm_source=stack-comment).

2024-03-05 19:31 UTC, woodenfurniture commented
Marking as draft until LP ships to mitigate risk during rollout

2024-03-25 10:50 UTC, gomesalexandre commented on src/components/Graph/RainbowChart/RainbowChart.tsx
> +import { selectFungibleAssets, selectSelectedLocale } from 'state/slices/selectors'
Feels like non-fungibles *should* be accounted for here?

2024-03-25 11:03 UTC, gomesalexandre commented on src/context/AppProvider/AppContext.tsx
> -
👀

2024-03-25 11:22 UTC, gomesalexandre commented on src/hooks/useBalanceChartData/useBalanceChartData.ts
> +  const assets = useAppSelector(selectFungibleAssets)
Even though we currently don't have market data per se for non-fungible, should we assume we can get *some* kind market data for non-fungible? Which we do as floor price in the NFT tab, even though we don't upsert it as market data:

<img width="303" alt="image" src="https://github.com/shapeshift/web/assets/17035424/d00cb7c7-3741-4293-a724-0de1abd41492">

See Zerion for instance, which do exclude it from the net worth, but still have a tab for NFTs with total floor price value

<img width="254" alt="image" src="https://github.com/shapeshift/web/assets/17035424/eb462638-8ce6-4a36-8457-a7bc845159e0">

2024-03-25 11:22 UTC, gomesalexandre commented on src/hooks/useBalanceChartData/utils.ts
> +  const assets = useSelector(selectFungibleAssets)
Same question as above here

2024-03-25 11:22 UTC, gomesalexandre commented on src/hooks/useTxDetails/useTxDetails.ts
> +  const assets = useAppSelector(selectFungibleAssets)
We should be able to `useTxDetails` on NFT Txs

2024-03-25 11:23 UTC, gomesalexandre commented on src/pages/Assets/Assets.tsx
> +import { selectFungibleAssetsSortedByName } from 'state/slices/selectors'
NFT assets are assets and should be visible in the assets page

2024-03-25 11:24 UTC, gomesalexandre commented on src/pages/TransactionHistory/DownloadButton.tsx
> +
Feels like this should be its own selector?

2024-03-25 11:25 UTC, gomesalexandre commented on src/pages/TransactionHistory/hooks/useSearch.tsx
> +  const assetsById = useAppSelector(selectFungibleAssets)
NFT Txs are Txs and we should be able to search them like any other Tx

2024-03-25 11:27 UTC, gomesalexandre commented on src/state/apis/zapper/zapperApi.ts
> +        const assets = selectNonFungibleAssets(getState() as ReduxState)
This is wrong - this query fetches UNI-V2 pool assetIds, which are fungible

2024-03-25 11:29 UTC, gomesalexandre commented on src/state/slices/assetsSlice/assetsSlice.ts
> +    upsertNonFungibleAsset: (state, action: PayloadAction<Asset>) => {
We should still be able to fetch fungibles - which we do when e.g upserting UNI-V2 assets data, or asset description on this same file on l.170:

https://github.com/shapeshift/web/blob/25c6ece1c1c628f4392594095a8f9413d8eb0a10/src/state/slices/assetsSlice/assetsSlice.ts#L170

2024-03-25 11:29 UTC, gomesalexandre commented on src/state/slices/assetsSlice/assetsSlice.ts
> +          if (data) dispatch(assets.actions.upsertNonFungibleAssets(data))
This is fungible asset data

2024-03-25 11:33 UTC, gomesalexandre commented on src/state/slices/assetsSlice/assetsSlice.ts
> -    getAssets: build.query<UpsertAssetsPayload, void>({
Feels like we shouldn't remove this?

2024-03-25 11:34 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +        store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
This is fungible assets data

2024-03-25 11:34 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +        store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
Ditto

2024-03-25 11:34 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +        store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
Ditto

2024-03-25 11:34 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +      store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
Ditto

2024-03-25 11:35 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +      store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
Ditto

2024-03-25 11:35 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +      store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
Ditto

2024-03-25 11:35 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +      store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
Ditto

2024-03-25 11:35 UTC, gomesalexandre commented on src/state/slices/portfolioSlice/portfolioSlice.test.ts
> +      store.dispatch(assetsSlice.actions.upsertNonFungibleAssets(assetData))
Ditto

2024-03-25 11:37 UTC, gomesalexandre commented on src/state/slices/search-selectors.ts
> +  selectFungibleAssetsBySearchQuery,
Ditto NFT assets are assets and should be searchable

2024-03-25 11:38 UTC, gomesalexandre commented on src/state/slices/txHistorySlice/selectors.ts
> +  selectFungibleAssets,
Ditto Txs with NFTs are Txs and should be searchable

2024-03-25 11:47 UTC, gomesalexandre requested changes
@woodenfurniture see testing below - many many regressions with this guy and probably a lot more than I've found out here.

While I conceptually get the intent re: perf here, I don't think this is feasible in a non-breaking fashion? i.e:

> Massively reduces the compute required to select the assets like because the static list is not invalidated every time an asset is added to the list. The dynamic list is very small so selector reselect is cheap.

The issue here is that a recompute *is* expected. As we upsert asset description and upsert assets meta (e.g Zapper UNI-V2 opportunities meta), assets *should* recompute so they are reflected at view-layer. Same goes for NFTs, and failure to do so will result in missing assets meta, and consequently user data.

Given how extensive this diff is because of the LSP rename and the number of places where fungible/non-fungible was forgotten, if we want to keep going with this PR, I would suggest to at the very least:

- keep `selectAssets` as a selector encapsulating fungible and non-fungible, and *don't* update consumption ensuring we still consume the same assets it in most places, except in ones where this is a huge perf. issue (e.g asset selection) 
- ensure there are no regressions in upsertion, see e.g comments in `<AppContext />` and RTK queries

However at this stage, most of the benefits would arguably be gone, with a high possiblity of regressions still present, so happy to discuss this PR further.

---

Tested locally (after a local merge of `origin/develop` which I didn't do in this PR to avoid restacking issues, and after a full cache clear):

- NFT assets are now missing in wallet in this diff

<img width="1725" alt="image" src="https://github.com/shapeshift/web/assets/17035424/13a68690-d82a-4b7e-b2d0-31db426559be">
<img width="1622" alt="image" src="https://github.com/shapeshift/web/assets/17035424/fbe54c79-ea64-4d20-92a5-8f86d95a073d">

- Idle and UNI-V2 assets are now missing in this diff

<img width="1728" alt="image" src="https://github.com/shapeshift/web/assets/17035424/b63f2691-2bc7-479f-86d1-e6dbef8a2f1a">

- Searching for NFTs is now broken

<img width="1451" alt="image" src="https://github.com/shapeshift/web/assets/17035424/f536718f-68f7-452e-bad2-f088cc386ab8">

- Manually navigating to an NFT asset page it's now obvious the meta isn't fetched for it, most likely the cause of all the issues above and most likely related to the removal of https://github.com/shapeshift/web/pull/6281/files#r1537409080

 
<img width="1674" alt="image" src="https://github.com/shapeshift/web/assets/17035424/971786af-9b04-47d7-92d4-c9248dad9458">

Note missing balance entry, and missing symbol in this screenshot

- Asset descriptions is now missing (tested with FOXy, ATOM, FOX and ETH)

<img width="1728" alt="image" src="https://github.com/shapeshift/web/assets/17035424/c8c5ac01-c85c-42f6-989c-f988f69136ec">
<img width="1728" alt="image" src="https://github.com/shapeshift/web/assets/17035424/573bf1c6-93af-41ea-a2dd-5caa50090c6c">
<img width="1728" alt="image" src="https://github.com/shapeshift/web/assets/17035424/f9a560d0-5bbe-4dbc-ad77-ce88d30ed90a">
<img width="1728" alt="image" src="https://github.com/shapeshift/web/assets/17035424/a204913f-f0b8-402e-af51-ffafe161eb93">

2024-03-25 23:22 UTC, woodenfurniture commented
Following converstation with @gomesalexandre , the decision is to close this in favour of new smaller tasks which should achieve the same / better gain with less risk:
Move uni v2 pools into generate-assets script #6559
Add staticAssets as a new field in assets slice #6560
Sort the static generated assets list by display name #6561

2024-03-25 23:23 UTC, woodenfurniture commented
Following converstation with @gomesalexandre , the decision is to close this in favour of new smaller tasks which should achieve the same / better gain with less risk:
Move uni v2 pools into generate-assets script https://github.com/shapeshift/web/issues/6559
Add staticAssets as a new field in assets slice https://github.com/shapeshift/web/issues/6560
Sort the static generated assets list by display name https://github.com/shapeshift/web/issues/6561

2024-03-25 23:23 UTC, closed without merging