fix: ledger don't verify manual receive address
shapeshift/web pull request #6399
Opened 2024-03-11 09:51 UTC by gomesalexandre

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk
> High Risk PRs Require 2 approvals

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2024-03-11 09:51 UTC, gomesalexandre commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/shapeshift/web/6399?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#6399** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6399?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#6398** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6398?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gomesalexandre and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-12 19:25 UTC, kaladinlight requested changes
![image](https://github.com/shapeshift/web/assets/35275952/09c597c5-6425-4f62-bf9f-806f12dd1920)

the logic and view seem inverted. we are still trying to verify the buy asset, but only showing the sell address.

2024-03-12 20:25 UTC, gomesalexandre commented
> ![image](https://private-user-images.githubusercontent.com/35275952/312211601-09c597c5-6425-4f62-bf9f-806f12dd1920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzUwNjQsIm5iZiI6MTcxMDI3NDc2NCwicGF0aCI6Ii8zNTI3NTk1Mi8zMTIyMTE2MDEtMDljNTk3YzUtNjQyNS00ZjYyLWJmOWYtODA2ZjEyZGQxOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDIwMTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZDAyYWFkNzUwNmMxY2Y3NmFjN2NhZjY4MGMxYjlhNTgzNDBhOTlhN2QwZmQ3ZWZhOWUwOTQyNzBiYzNiZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l_deJPgTxWq6NXzVSC-D7p1EQ1lf4q2J6JyTYK5_i7k)
> 
> the logic and view seem inverted. we are still trying to verify the buy asset, but only showing the sell address.

Nice catch! Did some little cleanup while at it which fixed things there.

- No manual receive address

<img width="591" alt="Screenshot 2024-03-12 at 21 17 27" src="https://github.com/shapeshift/web/assets/17035424/f88b8858-1503-4df5-9989-4828330a18ac">


- Manual receive address

 
<img width="601" alt="Screenshot 2024-03-12 at 21 18 36" src="https://github.com/shapeshift/web/assets/17035424/7a7de23e-3ec4-4dc0-8ca0-01b08b17cc78">

https://github.com/shapeshift/web/pull/6399/commits/2c36bc19f6ef18feb4588e75383f1bb83a651947 / https://github.com/shapeshift/web/pull/6399/commits/26ecc9d8d7918e0e295a7f5984bcb965e4041893

2024-03-12 20:26 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
> -
Now useless - part of the issue we were seeing

2024-03-13 18:01 UTC, kaladinlight commented on src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
> +    () => maybeManualReceiveAddress || isAddressVerified(buyAddress ?? ''),
nitpick refine type (boolean your fav! haha)

```suggestion
    () => Boolean(maybeManualReceiveAddress) || isAddressVerified(buyAddress ?? ''),
```

2024-03-13 18:01 UTC, kaladinlight approved these changes

2024-03-13 19:35 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
> +    () => maybeManualReceiveAddress || isAddressVerified(buyAddress ?? ''),
I like Boolean

2024-03-13 19:43 UTC, merged