feat: add v9 of fox farm
shapeshift/web pull request #6854
Opened 2024-05-08 18:52 UTC by 0xean

## Description

Adds v9 of fox farming.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk
> High Risk PRs Require 2 approvals

should be considered high risk even tho a tiny PR just in case I put the wrong addresses in or something of that nature. 

> What protocols, transaction types or contract interactions might be affected by this PR?

ETH fox farming 

## Testing

Not tested besides to confirm it shows up on screen. Ops might be able to test before it goes live with some small LP balances just to confirm staking and unstaking works and flows into the new contracts correctly 

https://etherscan.io/address/0xec84524385ffd1ea423ec4682caa5ab56071fbc7

### Engineering

### Operations

Please give this a once over with staking and unstaking to confirm funds flow into and out of 

https://etherscan.io/address/0xec84524385ffd1ea423ec4682caa5ab56071fbc7

## Screenshots (if applicable)
![Screenshot 2024-05-08 at 2 51 19 PM](https://github.com/shapeshift/web/assets/15096737/f5ecc288-582f-42dd-99c8-9bdf5c672934)

2024-05-08 18:54 UTC, 0xean commented
P.S I updated the arkeo code, just because it was there, but creating follow up ticket to remove https://app.shapeshift.com/#/arkeo entirely as the snapshot is now down

2024-05-08 19:09 UTC, gomesalexandre approved these changes
Tested locally, confirmed this does what it says on the box!

<img width="1424" alt="image" src="https://github.com/shapeshift/web/assets/17035424/459c79e8-785e-42e4-90ef-4a16bb5b7844">

2024-05-09 23:37 UTC, woodenfurniture requested changes
Unsure whether this is intentional but out of caution, requestiong changes so we can verify. Clicking the main "Start earning" appears to be linked to v8, as it shows the v8 contract address instead of the v9 contract address.

![image](https://github.com/shapeshift/web/assets/125113430/4ce34ae0-cc16-4c0e-bfe7-183cd4b2b03b)

Uploading Screen Recording 2024-05-10 at 9.33.43 AM.mov…

2024-05-10 02:40 UTC, woodenfurniture commented
V9 was not appearing in the carousel due to a filter enforcing >1% APY and >$50k TVL, which obviously the new contract does not satisfy. I've pushed a commit to hardcode the v9 contract to appear at the front of the carousel which we cna revert once V9 has adequate TVL.

2024-05-10 02:42 UTC, woodenfurniture approved these changes

2024-05-10 02:43 UTC, 0xApotheosis commented on src/pages/Defi/components/EligibleCarousel.tsx
> +    ].slice(0, 5)
Add a uniqueBy for when `foxFarmingV9` appears in the regular list.

2024-05-10 03:12 UTC, 0xApotheosis approved these changes
The spread is pretty gnarly, but I get why we are doing it.

V9 shows as expected, and initial load with no cache issue is mitigated with the re-positioning of the V9 contract as the second element of the opportunities list.

2024-05-10 03:12 UTC, 0xApotheosis commented on src/pages/Defi/components/EligibleCarousel.tsx
> +      [filteredEligibleOpportunities[0], foxFarmingV9, ...filteredEligibleOpportunities.slice(1)],
This is gross, but as discussed, it'll do the trick.

2024-05-10 03:14 UTC, merged