[skip ci] wip: wire-up RFOX Change address
shapeshift/web pull request #6963
Opened 2024-05-22 09:30 UTC by gomesalexandre

## Description

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

## Risk
> High Risk PRs Require 2 approvals

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

### Engineering

### Operations

## Screenshots (if applicable)

2024-05-22 09:33 UTC, gomesalexandre commented on src/pages/RFOX/components/ChangeAddress/ChangeAddressConfirm.tsx
This component is wrong - only the input part was actually implemented in the visual bits PR https://github.com/shapeshift/web/pull/6959, the confirmed part is actually a copy and paste from `<StakeConfirm />` which isn't matching the figma at all

See runtime after cleanup of ShapeShift fee and approval fees row vs. Figma 
<img width="512" alt="image" src="https://github.com/shapeshift/web/assets/17035424/0b436078-299a-4147-b6a6-2a4c88873507">
<img width="988" alt="image" src="https://github.com/shapeshift/web/assets/17035424/ef0ba17c-6c80-417b-80a3-a0ce98812588">

2024-05-23 11:02 UTC, gomesalexandre commented on src/components/AccountDropdown/AccountDropdown.tsx
> +  // Hides a given set of AccountIds from the dropdown
rm

2024-05-23 11:03 UTC, gomesalexandre commented on src/components/AccountDropdown/AccountDropdown.tsx
> +  // Hides a given set of AccountIds from the dropdown
3e57064a

2024-05-23 11:06 UTC, gomesalexandre commented on src/pages/RFOX/components/AddressSelection.tsx
> +      validateIsNewAddress?: never
i.e both or none, but not partial

2024-05-23 11:07 UTC, gomesalexandre commented on src/pages/RFOX/components/ChangeAddress/ChangeAddressConfirm.tsx
> +    // TODO(gomes): implement current/new rune address display here
Remove me

2024-05-23 11:08 UTC, gomesalexandre commented on src/pages/RFOX/components/ChangeAddress/ChangeAddressConfirm.tsx
> +    // TODO(gomes): implement current/new rune address display here
dda82383cc

2024-05-23 11:09 UTC, gomesalexandre commented on src/pages/RFOX/components/ChangeAddress/ChangeAddressInput.tsx
> +      // we change it to stakingInfo[3] vs. stakingInfo[2] currently after we deploy and consume the latest version of the contract
To be tackled as part of https://github.com/shapeshift/web/issues/6967

2024-05-23 11:11 UTC, gomesalexandre commented on src/pages/RFOX/components/Stake/StakeInput.tsx
> +              {errors.manualRuneAddress?.message || translate('RFOX.stake')}
This looks wrong

2024-05-23 12:20 UTC, gomesalexandre commented on src/pages/RFOX/components/Stake/StakeInput.tsx
> +              {errors.manualRuneAddress?.message || translate('RFOX.stake')}
c36cf6e211

2024-05-27 04:42 UTC, 0xApotheosis requested changes
Looking great!

✅ Manual change address works as expected
✅ Change address from list works as expected
✅ Cannot proceed with same address, either manually or from list
✅ Current address displayed and updated on change

Some minor things to tweak before we get this in:

❌ Can proceed with manual address after clearing it

https://github.com/shapeshift/web/assets/97164662/3aabc271-7b26-489d-9572-a84e0e2b1908

❓ The "You have successfully..." text feels a little misaligned/missing padding. Should also probably have a full stop.

<img width="333" alt="Screenshot 2024-05-27 at 2 35 13 PM" src="https://github.com/shapeshift/web/assets/97164662/eef3caf9-34ce-4c82-8c50-2f08c261ab92">

2024-05-27 04:42 UTC, 0xApotheosis commented on src/assets/translations/en/main.json
> +    "addressUpdateSucces": "You have successfully updated your Thorchain Reward Address",
We can remove both of these now.

2024-05-27 04:42 UTC, 0xApotheosis commented on src/assets/translations/en/main.json
> +    "noPositionBody": "You will be able to change your reward address here, once you have an active position.",
Nitpick:

```suggestion
    "noPositionBody": "You will be able to change your reward address here once you have an active position.",
```

2024-05-27 04:42 UTC, 0xApotheosis commented on src/pages/RFOX/components/Stake/StakeConfirm.tsx
> +    history.push(StakeRoutePaths.Status)
Duplicate lInes?

2024-05-27 04:42 UTC, 0xApotheosis commented on src/pages/RFOX/components/ChangeAddress/ChangeAddressStatus.tsx
> +        <Button as={Link} href={txLink} size='lg' variant='ghost'>
```suggestion
        <Button as={Link} href={txLink} size='lg' variant='ghost' isExternal>
```

2024-05-27 08:02 UTC, gomesalexandre commented on src/assets/translations/en/main.json
> +    "noPositionBody": "You will be able to change your reward address here, once you have an active position.",
33c3c04ac821a44378d068dc1c90e39137953598

2024-05-27 08:02 UTC, gomesalexandre commented on src/pages/RFOX/components/ChangeAddress/ChangeAddressStatus.tsx
> +        <Button as={Link} href={txLink} size='lg' variant='ghost'>
436f383d1dc5e58ff1f35769078fd08fce52853d

2024-05-27 08:06 UTC, gomesalexandre commented on src/assets/translations/en/main.json
> +    "addressUpdateSucces": "You have successfully updated your Thorchain Reward Address",
16bc6a37fb

2024-05-27 08:36 UTC, gomesalexandre commented
Nice catch @0xApotheosis - both fixed: 
> Some minor things to tweak before we get this in:
> 
> ❌ Can proceed with manual address after clearing it
> 
>  proceed-on-empty-address.mp4 

Fixed in 29db81d08b, we were too optimistic in not firing onChange when there is no (empty) rune address. Note this commit also fixes the same issue in staking:

https://jam.dev/c/a5d65acd-1487-4250-b1db-836d87728145

> 
> ❓ The "You have successfully..." text feels a little misaligned/missing padding. Should also probably have a full stop.

Fixed in b75ff3f3cf

@woodenfurniture looks like we already have two things we improved here and want to reflect in the status steps of all three stake, unstake and change address tabs: the `isExternal` on the `<Link />`, and the text alignment improvements.

While those are not functional bugs per se, that was definitely a good call on the follow-up components restaking as a follow-up cleanup PR! 🐐

2024-05-27 08:42 UTC, 0xApotheosis approved these changes
Retested, looking good ser - get 'er in.

2024-05-27 08:43 UTC, merged