fix: lending repayment don't try and estimate Tx fees on approval needed
shapeshift/web pull request #7088
Opened 2024-06-10 17:04 UTC by gomesalexandre

## Description

Does what it says on the box - no query, no problem

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/7083

## Risk
> High Risk PRs Require 2 approvals

> What protocols, transaction types or contract interactions might be affected by this PR?

Low, see testing

## Testing

- Token repayments with approval needed are now happy
- Token repayments without approval needed are still happy
- Native asset repayments are still happy

### Engineering

- ^

### Operations

- ^

## Screenshots (if applicable)

Develop (right) vs. this diff

2024-06-10 17:07 UTC, gomesalexandre commented on src/pages/Lending/Pool/components/Repay/RepayInput.tsx
> +
uh oh

2024-06-11 05:44 UTC, 0xApotheosis requested changes
✅ Native asset repay
✅ Already-approved asset repay
❌ Not-yet approved asset repay - getting strange behaviour here, see below:

On initial load I can approve the token, but the network fee never loads:

<img width="310" alt="Screenshot 2024-06-11 at 3 37 06 PM" src="https://github.com/shapeshift/web/assets/97164662/0a036458-2a95-4bed-a392-cae9c5e6f20f">

If I approve a token, and then go to a different, non-approved token, the approve button is disabled, and the network fee does not load:

<img width="311" alt="Screenshot 2024-06-11 at 3 34 25 PM" src="https://github.com/shapeshift/web/assets/97164662/a4a6e23a-99a1-4e48-8f1a-79f9210a8d75">

https://jam.dev/c/afc17501-2e4f-4545-9c5e-b11e8f6d5755

2024-06-11 17:21 UTC, gomesalexandre commented
> ✅ Native asset repay ✅ Already-approved asset repay ❌ Not-yet approved asset repay - getting strange behaviour here, see below:
> 
> On initial load I can approve the token, but the network fee never loads:
> 
> <img alt="Screenshot 2024-06-11 at 3 37 06 PM" width="310" src="https://private-user-images.githubusercontent.com/97164662/338450044-0a036458-2a95-4bed-a392-cae9c5e6f20f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjE1OTcsIm5iZiI6MTcxODEyMTI5NywicGF0aCI6Ii85NzE2NDY2Mi8zMzg0NTAwNDQtMGEwMzY0NTgtMmE5NS00YmVkLWEzOTItY2FlOWM1ZTZmMjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE1NTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzI5YzE4OWIyYTdjZjdkZmIwNzc5YzYzNWNhOTZjYTZmYmI0ODE2NGEyZGI3MTA1MTU2ZDQwNmZmOWIxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VnuXnnXi85w0yZjGEi70AFMFjEEv313h-qgi9rAQMuk">
> If I approve a token, and then go to a different, non-approved token, the approve button is disabled, and the network fee does not load:
> 
> <img alt="Screenshot 2024-06-11 at 3 34 25 PM" width="311" src="https://private-user-images.githubusercontent.com/97164662/338450195-a4a6e23a-99a1-4e48-8f1a-79f9210a8d75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjE1OTcsIm5iZiI6MTcxODEyMTI5NywicGF0aCI6Ii85NzE2NDY2Mi8zMzg0NTAxOTUtYTRhNmUyM2EtOTlhMS00ZTQ4LThmMWEtNzlmOTIxMGE4ZDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE1NTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZDcxMTljYTA0M2E3YzcxMWVmOWFjYmM5NWQ2OWE5ZDhmYzAzMDg3M2ZjZWQ2NGYxNWY3MTY0ZDg5NGU5NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y84sVqSIVf-K5leQtqpmcSaynrFcRmiD8FVRVjgt_W8">
> https://jam.dev/c/afc17501-2e4f-4545-9c5e-b11e8f6d5755

ty for the review @0xApotheosis!

There are two components to this:

1. Network fee being shown as a skeleton, as we *cannot* estimate fees with an approval required. I believe we should bring in the same "network fees *or* approval fees pattern as in RFOX here" though that's probably a different concern IMO, going to bring this one in as a direct follow-up on top of this PR not to mix concerns. 
2. Infinite loading state while selecting another token after approving one. Indeed, there's definitely a case of wanting to clear the approvalTx to handle the edge case of having a stale approval Tx.

Brought a few more fixes in, which effectively contribute to fixing 2. (and more issues spotted whilst in the house):

- 01fa0d8d00 - ensures `repaymentAmountCryptoPrecision` is in the repayment asset's precision, *without* more precision as originally coming over from the wire (THOR). This means approvals would fail to be properly detected, as we're effectively approving a smaller amount (repayment asset precision on-chain) compared to the input amount (too much precision)
- 7203359e5c - uses `selectPortfolioCryptoPrecisionBalanceByFilter` to select the crypto precision balance precision, effectively fixing the wrong repayment asset balance, previously in base unit
- 1e3c4b1ebe - type-safety ensuring we have a quote when doing balance checks 

https://jam.dev/c/2e907761-f031-4102-bd30-4230032b0c9b

2024-06-13 04:31 UTC, 0xApotheosis approved these changes
This works as it claims to 🤝 

We still have the issue of the network fee skeleton on approval (i.e. not showing the approval fee estimate to the user), but that is not expected for this PR (though as you noted, we should absolutely do in a follow up).

2024-06-13 04:31 UTC, merged