chore: initial refactor for limit orders
shapeshift/web pull request #7912
Opened 2024-10-09 23:57 UTC by woodenfurniture

## Description

Refactors trade input components to allow us easy build-out of limit orders.

## Issue (if applicable)

closes #7908 

## Risk

> High Risk PRs Require 2 approvals

High risk. The changes here are theoretically straightforwards but considering the impact of getting things wrong and breaking the ability to make trades, we should review this under a "high risk" lens.

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

All trades for all protocols, namely UI transitions and interactions.

Additionally, arbitrum bridge which is not directly affected but may be indirectly affected UI-wise.

## Testing

Swaps, bridges, quotes, should be EXACTLY the same as prod.

Check trades, namely UI transitions and interactions around:
- trade input
- quote list
- confirming a trade
- settings "cog" menu (slippage etc)
- account selection
- manual receive address
- mobile UI layout

Additionally test the arbitrum bridge which is not directly affected but may be indirectly affected UI-wise.

### Engineering

Rebase was finicky, so please double check regression of https://github.com/shapeshift/web/pull/7896/files

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

2024-10-09 23:58 UTC, woodenfurniture commented on src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
> +              setSellAssetAccountId={setSellAssetAccountId}
![image](https://github.com/user-attachments/assets/7f3d94af-4ec4-483d-b7fd-e82bfda6e415)

2024-10-11 05:34 UTC, 0xApotheosis requested changes
Code-wise this is looking good.

I did a regression test with this branch (left) against `develop` (right) and found a few small but important things:

❌ **Going to the Claim tab and back again leads to a an empty Trade/Bridge route** 

<img width="416" alt="Screenshot 2024-10-11 at 16 19 43" src="https://github.com/user-attachments/assets/a3f19d3b-c646-4990-9cd8-c090a7412f8d">

✅ **End-to-end trade flow (including approval)**

<img width="368" alt="Screenshot 2024-10-11 at 16 23 59" src="https://github.com/user-attachments/assets/b1e13fe2-0411-47c0-be14-451917384a52">

❌ **Padding broken**

We are missing the padding (48px) that was wrapping the Trade component

<img width="2558" alt="Screenshot 2024-10-11 at 16 28 43" src="https://github.com/user-attachments/assets/8fa57c20-c0f2-4a00-96de-1baae6767eb2">

❓ **Infinite quote loading is back, and a weird flicker in the quote list - note this happened once and I couldn't repro again, so I"m not going to pin it to this branch**

<img width="2560" alt="Screenshot 2024-10-11 at 16 12 49" src="https://github.com/user-attachments/assets/37dbd6a3-cd77-4096-a9ff-6d155e353fea">

https://github.com/user-attachments/assets/3041c502-87d9-48e4-8a10-d36400912f94

2024-10-14 02:02 UTC, 0xApotheosis approved these changes
Retested - issues from the previous review have been resolved, looking good.

2024-10-14 12:36 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
> +            initialSellAssetAccountId={initialSellAssetAccountId}
suggestion: while these are called *initial* in destructuring of `useAccountId()` return value here:

https://github.com/shapeshift/web/blob/8272547a1fb78a64d436c0489dda52e32defdda3/src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx#L82-L87

There is not much of `initial`:

https://github.com/shapeshift/web/blob/253ed2c6d25c3a3c36b9613d22ba4d9f995d4d1e/src/components/MultiHopTrade/hooks/useAccountIds.tsx#L15-L17

I got quite confused while working in this domain, as this is really the *selected* AccountIds, do we want to use this terminology instead as part of the refactor?

2024-10-14 12:41 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
> +    buyAssetAccountId: initialBuyAssetAccountId,
See comment above re: do we want to stop destructure-renaming this, or perhaps use `selected` terminology instead?

2024-10-14 12:44 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
> +  const isKeplr = useMemo(() => !!wallet && isKeplrHDWallet(wallet), [wallet])
Note for a follow-up: we can probably remove this, historical reasons were Osmosis swaps were quite borky in Keplr (or not implemented, can't recall exactly) iirc, but with swapper v2 and custom receive addies, this should now work (and will even better once we bring EVM support to Keplr)

2024-10-14 12:47 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
> +  const isKeplr = useMemo(() => !!wallet && isKeplrHDWallet(wallet), [wallet])
https://github.com/shapeshift/web/pull/2971 for historical ref

2024-10-14 12:50 UTC, gomesalexandre reviewed
First conceptual pass, one smolish comment re: `useAccountIds()` destructured vals renaming but nothing obviously standing out here, runtime pass to follow!

2024-10-14 15:07 UTC, gomesalexandre approved these changes
Tested against *prod* (right, note that is *not* develop because of current ws issues in develop endpoints) and with *app* env, couldn't find any regression in swapper either presentational or functional!

- Trade input is happy (desktop)

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/5c6a038d-1e12-4384-93e6-649242c29311">

- Trade input is happy (mobile)

<img width="1446" alt="image" src="https://github.com/user-attachments/assets/5a432412-5ae8-41cc-a46d-ad29c69c4475">

- Claims are happy (mobile)

<img width="1472" alt="image" src="https://github.com/user-attachments/assets/186586d1-edc4-413b-b068-77f194651fab">

- Claims are happy (desktop)

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8c3defda-9775-457b-a99a-9f4b39a91d99">

- Quotes list (desktop)

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/3f8738a8-3b63-4de4-9b4a-c63b17449b42">

- Quotes list (mobile)

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/7db72033-bfd2-4b9b-ba82-2e805e3e0b79">

- Cog settings wheel is happy

https://jam.dev/c/21445392-954b-4017-b643-39305a9afd30

- Trade confirm/execution is happy

https://jam.dev/c/7b57952c-cd00-404b-b134-2d8eecfc667d

- Multi-account and manual receive address swaps are happy

https://jam.dev/c/847a8b92-3d7d-4f1b-9b30-9c3b9a9508b9

2024-10-15 00:50 UTC, merged