[skip ci] wip: getTradeRate swapper endpoint
shapeshift/web pull request #7997
Opened 2024-10-24 11:56 UTC by gomesalexandre

## Description

## Issue (if applicable)

closes #

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

### Engineering

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

2024-10-24 22:01 UTC, gomesalexandre commented
Notes after discussing with woody:

- Let's try not to add a new RTK api slice and abuse the current `getTradeQuote` instead (assuming flag on) to get rates
- Execution may be borked with flag on if we do this, which is fine as we can just turn it off in base *and* dev
- Alternatively, can always duplicate everything tradeQuote with a new API/slice but that's going to be a huge lift / risks

tl;dr ditch all the boilerplate and console.logs validating this works and make it actually work i.e
- rates work with the flag on and execution probably borked (but ideally not) which is expected
- quotes are still happy with the flag off
- assess next steps re: state machine with @woodenfurniture once we're ready to merge this

2024-10-25 10:52 UTC, gomesalexandre commented on src/state/apis/swapper/helpers/validateTradeQuote.ts
review with whitespaces diff off

2024-10-25 10:55 UTC, gomesalexandre commented on src/state/apis/swapper/swapperApi.ts
> +          // Always get a trade rate with the flag enabled. This will break execution for the time being, but as discussed with @woodenfurniture
@woodenfurniture for vis since this inline tags no worky

2024-10-28 22:54 UTC, gomesalexandre commented on .env.dev
> +REACT_APP_FEATURE_PUBLIC_TRADE_ROUTE=false
one too deep on the mergefix

2024-10-29 00:23 UTC, woodenfurniture requested changes
# Testing notes

❓ Metamask generally very flaky with signing, rarely pops up the signature modal in the extension, but this appears to affect prod too. Basically unable to test with metamask on any chain as metamask is not allowing the signing of txs.

✅ LiFi
<img src="https://github.com/user-attachments/assets/0e53c793-68d4-4548-baba-fde27bb4c677" width="200">

✅ 0x with Permit2
<img src="https://github.com/user-attachments/assets/c1f4adf4-567c-471a-b4d5-b5cbc15cb64e" width="200">

✅ Portals
<img src="https://github.com/user-attachments/assets/8e284ec5-815c-4435-8511-fb283ce61d11" width="200">

✅ Cow

❌ When connected to metamask (without snaps), user is able to select RUNE on THORChain but unable to get a rate. In prod this is not possible.
<img src="https://github.com/user-attachments/assets/7ad3c6e9-db52-44e8-be76-d88f32c4917c" width="200">

❌ Sitting on the screen above waiting for a re-fetch, the loading state gets stuck on.
<img src="https://github.com/user-attachments/assets/9a650ddb-f436-4ee0-b87b-27198afaa76a" width="200">

Will test rates on second pass! 🙏

2024-10-29 01:39 UTC, woodenfurniture approved these changes
Confirmed issues raised are with flag off and are expected 🎉 LFGTM

2024-10-29 01:41 UTC, gomesalexandre commented on src/pages/RFOX/components/Stake/Bridge/hooks/useRfoxBridge.ts
> +    () => ({ ...tradeQuoteInput, wallet, quoteOrRate: 'quote' as const }),
Happy to cleanup as follow-up 🙏🏽 unrelated to the split per se

2024-10-29 01:41 UTC, gomesalexandre commented on packages/swapper/src/types.ts
> +}
Happy to cleanup as follow-up 🙏🏽 unrelated to the split per se

2024-10-31 08:27 UTC, 0xApotheosis reviewed
Holy moly, monster 🐐 PR ser.

Code-wise looking excellent and tidy. Non-blocking, but it might be better if the `quoteOrRate` logic was an enum (though this may have implications on type narrowing).

Working on the functional review as we speak.

2024-10-31 09:06 UTC, 0xApotheosis approved these changes
✅ Able to get quotes for (and execute) permit2 ZRX with permit2 flag

<img width="345" alt="Screenshot 2024-10-31 at 19 50 16" src="https://github.com/user-attachments/assets/ff33dda5-a6a3-49d3-840e-9a0988071aa6">

✅ Able to get quotes for (and execute) classic ZRX without permit2 flag

<img width="334" alt="Screenshot 2024-10-31 at 20 01 15" src="https://github.com/user-attachments/assets/3f280fcc-7fe9-43ad-bcfa-259306cefcdd">

✅ Able to get quotes for (and execute) Portals (note, this is a non-breaking change, hence the super hacky "quote then maybe estimate then maybe another dummy quote" flow is still present, to be removed when we wire this up with rates instead of quotes, with "TBA" for network fees)

<img width="355" alt="Screenshot 2024-10-31 at 19 54 02" src="https://github.com/user-attachments/assets/d56a894a-5547-483c-a71c-2c7330d59967">

✅ Able to get quotes (and execute) for CoW

<img width="348" alt="Screenshot 2024-10-31 at 19 56 24" src="https://github.com/user-attachments/assets/a19e8317-4ade-45ca-9f08-588d03094b89">

✅ Able to get quotes (and execute) for Li.Fi

<img width="355" alt="Screenshot 2024-10-31 at 19 52 05" src="https://github.com/user-attachments/assets/ef46b399-52e0-4bd9-acf7-94e8b3ec2707">

✅ Able to get quotes (and execute) for THOR

<img width="337" alt="Screenshot 2024-10-31 at 19 57 55" src="https://github.com/user-attachments/assets/1dcb9ae3-0bc6-4d2e-8d57-2c3886eddab2">

In addition, _rates_ are happy with `REACT_APP_FEATURE_PUBLIC_TRADE_ROUTE` - note, I did not attempt to execute any of these.

2024-10-31 09:07 UTC, 0xApotheosis commented
I'll merge this beast in the name of progress. The outstanding nitpicks/non-blockers can be tackled in a future PR 🙏

2024-10-31 09:07 UTC, merged