feat: limit orders quote wiring
shapeshift/web pull request #8095
Opened 2024-11-07 01:08 UTC by woodenfurniture

## Description

Wires up the limit order quote query to the input and config uis. Includes loading state improvements. Includes config reset when assets change. Config is not reset when amounts or quote changes to avoid annoying users during polling (polling yet to be implemented).

TODO
- [ ] remove "no rate available" ui
<img src="https://github.com/user-attachments/assets/da4d10e7-0ee6-41be-bec0-79dd70a3cfca" width="200">

## Issue (if applicable)

closes #8033

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

### Engineering

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

2024-11-10 21:57 UTC, woodenfurniture commented on src/components/MultiHopTrade/components/RateGasRow.tsx
> -
Was moved into a separate component `SwapperIcons` during a different refactor and decided to leave it separated.

2024-11-10 21:58 UTC, woodenfurniture commented on src/components/MultiHopTrade/components/RateGasRow.tsx
> -    children,
Changes to this component are just making it more generic for use with limit orders.

2024-11-11 22:10 UTC, 0xean commented
blame woody if those go haywire - but only 1 review needed here :) 💀

2024-11-12 09:51 UTC, NeOMakinG requested changes
Code point of view looks very sane, big tree @woodenfurniture 🐐 

Testing at runtime: https://jam.dev/c/85d588ef-05e2-43a3-a714-04134c0719ba

A few things:

- 0$ is supposed to say `Free` as a green field as regular swapper does
![image](https://github.com/user-attachments/assets/e8af53c7-330e-4dc5-aac2-0d5f0d21ba16)

- When inverting assets I have a super weird behavior:
![image](https://github.com/user-attachments/assets/08c40d80-4967-44b0-9152-e92a0c29b552)

- Same as inverting, if you look at https://jam.dev/c/85d588ef-05e2-43a3-a714-04134c0719ba , there is a moment where you have USDC > FOX, with `When price reach 16`, which should be `0.06` instead, I think it's due to the useEffect that is not rerunning on market price change

## Regular trade
![image](https://github.com/user-attachments/assets/3fcd4e55-8963-4aff-970b-caf1a178ef24)
![image](https://github.com/user-attachments/assets/f4e4ecfc-b399-47a1-a299-42418161c543)
![image](https://github.com/user-attachments/assets/5ef8617e-be6a-4b62-8d3a-acdb4b0a43af)

Seems ok so far

2024-11-12 09:51 UTC, NeOMakinG commented on src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
> +      isVotingPowerLoading
It's even more true since the vote power is only two requests now for FOX and THOR

2024-11-12 09:51 UTC, NeOMakinG commented on src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
> +    // NOTE: we DO NOT want to react to `marketPriceBuyAsset` here, because polling will reset it
I think it's causing a bug: 

- Same as inverting, if you look at https://jam.dev/c/85d588ef-05e2-43a3-a714-04134c0719ba , there is a moment where you have USDC > FOX, with `When price reach 16`, which should be `0.06` instead

2024-11-12 23:04 UTC, NeOMakinG approved these changes
Summary seems like before

Slippage is rightly applied on a LI.FI swap
https://jam.dev/c/cb1cf9d0-4476-4953-9bd0-7fef0beda757

THORChain swap
https://jam.dev/c/e58929e6-6bb3-4e09-84b8-96bc6b284a30
memo is assuming 0.0006ETH as a receive amount vs 0.00067 estimated which is around 9.5 slippage, looking good

As long as it's behind a feature flag, limit order issues are not blocking and can be done in the next PR 👍

2024-11-12 23:42 UTC, merged

2024-11-13 01:05 UTC, woodenfurniture commented
Appreciate the stamp, I've fixed both bugs in #8112:
- [fix: free trades are free](https://github.com/shapeshift/web/pull/8112/commits/64fd7ed52af821e51e90e3341648a2eee172875f)
- [fix: reset market rate when switching assets](https://github.com/shapeshift/web/pull/8112/commits/2f7e1ab290ab08cc0ec9b5036eba7c297e3de413)