fix: remove price history data that is out of bounds of a given timeframe
shapeshift/web pull request #8235
Opened 2024-12-01 23:03 UTC by woodenfurniture

## Description

Fixes corrupted price charts caused by price samples spanning times outside of the selected timeframe. For example for the 24 hour time period, data prior to 24 hours ago was being displayed, resulting in corrupted charts in the UI. The solution was to trim price history data when it's upserted in redux, and also when it's read from redux.

NOTE: It's possible there is still chart corruption occurring due to incorrectly sorted price history samples. If this is the case, let me know and I'll add sorting to the selector. However if this is not the case we'd be best off avoiding the additional compute.

## Issue (if applicable)

closes #8093

## Risk

> High Risk PRs Require 2 approvals

Low risk, this affects display of price charts only, which is already broken.

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

### Engineering

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

Before:
<img src="https://github.com/user-attachments/assets/99140bff-6aff-48d5-b23f-f4df0b15ef38" width="200">

After:
<img src="https://github.com/user-attachments/assets/e163c8ab-9937-44f5-b8c6-7f927946c4b7" width="200">

2024-12-01 23:04 UTC, woodenfurniture commented on src/state/slices/marketDataSlice/utils.ts
> +export const getTrimmedOutOfBoundsMarketData = <T extends SupportedFiatCurrencies | AssetId>(
Creates a new array - used in selectors

2024-12-01 23:04 UTC, woodenfurniture commented on src/state/slices/marketDataSlice/utils.ts
> +export const trimOutOfBoundsMarketData = <T extends SupportedFiatCurrencies | AssetId>(
Mutates the input - used in actions

2024-12-01 23:18 UTC, 0xApotheosis requested changes
Confirmed this fixes the individual assets I have with corrupted chart state 👌 

Noticed one potential issues with the overall balance chart:

<img width="1128" alt="Screenshot 2024-12-02 at 10 14 57" src="https://github.com/user-attachments/assets/a3ba9c66-8091-4f95-9302-c221439a0758">

Today, for e.g. I seem to have no history before 0000 local time. Feels a little like a bug related to "current day" (in this PR) vs "last 24 hours" (expected).

2024-12-02 00:17 UTC, woodenfurniture commented
> Today, for e.g. I seem to have no history before 0000 local time. Feels a little like a bug related to "current day" (in this PR) vs "last 24 hours" (expected).

@0xApotheosis right you are, fixed!

<img src="https://github.com/user-attachments/assets/32a23e33-3928-4e86-a41a-48ddebe21039" width="200">


And comparing the chart against coingeck:
<img src="https://github.com/user-attachments/assets/64b16c09-55c6-40a6-8907-3f96c67b67f7" width="200">
<img src="https://github.com/user-attachments/assets/07b35682-dcd2-476c-99c3-d5e332a4e2b9" width="200">

6bc641a31f87738fbb6e286f5c062d43d4081de7

2024-12-02 02:09 UTC, 0xApotheosis approved these changes
Total balance bug fixed 👌 

Note, I'm still able to get broken charts if I don't clear my cache - I'm not sure if that's expected. That said, it's significantly better than the current `develop` state.

This branch:

<img width="1144" alt="Screenshot 2024-12-02 at 12 41 47" src="https://github.com/user-attachments/assets/62648b5c-089a-4c66-a415-1bf35f647831">

`develop`:

<img width="1143" alt="Screenshot 2024-12-02 at 12 56 32" src="https://github.com/user-attachments/assets/51c0e6d2-f7ec-446e-b612-7d64ab330683">

2024-12-02 02:49 UTC, gomesalexandre commented on packages/utils/src/historyTimeframe.ts
> +  let start = end // Shut up typescript.
😄

2024-12-02 02:57 UTC, woodenfurniture commented
> Note, I'm still able to get broken charts if I don't clear my cache - I'm not sure if that's expected. That said, it's significantly better than the current develop state.

I wasn't able to repro likely due to different local state, though here's a fix bab796ff4902dfc7c419379704686e33507e6efb (hopefully)

2024-12-02 02:59 UTC, 0xApotheosis commented
Confirming https://github.com/shapeshift/web/pull/8235/commits/bab796ff4902dfc7c419379704686e33507e6efb fixed it 👌 

<img width="1127" alt="Screenshot 2024-12-02 at 13 59 50" src="https://github.com/user-attachments/assets/5412e6f7-4b8d-49f0-a348-e2555be2b358">

2024-12-02 03:06 UTC, merged

2024-12-02 03:07 UTC, gomesalexandre requested changes
Tested locally against develop (left), LGTM minus one q:

- Assets price chart is fixed ❔ 

https://jam.dev/c/c0b7b30d-9adc-4274-9063-26e740716444

@woodenfurniture noting that "All" price chart for e.g BTC only goes up to 2 years ago, vs. all the way to 2013 in develop, this looks like a regression, is this known about / expected? 

This can be repro'd for other dinosaur coins too e.g CharlieCoin:

<img width="861" alt="image" src="https://github.com/user-attachments/assets/586ba494-2f3b-40b4-b1cd-6e28c9096e0f">
<img width="871" alt="image" src="https://github.com/user-attachments/assets/6e6409b1-71ec-4b3b-9fae-56c0532941b7">

Balance chart looks sane:

<img width="1649" alt="image" src="https://github.com/user-attachments/assets/b8617307-821a-4040-9bdd-a24b6e433828">
<img width="1658" alt="image" src="https://github.com/user-attachments/assets/96763520-dc61-4fbc-84e9-c8aa6762e410">
<img width="1645" alt="image" src="https://github.com/user-attachments/assets/ebf36ba1-6c99-4485-b87d-c0a6b12d3201">
<img width="1663" alt="image" src="https://github.com/user-attachments/assets/aa6edcc3-8110-4780-ae98-6b24ce23e45a">

Noting:

- 24h chart looks v. different (perhaps because of degraded accounts?) as well as 1M one showing green vs. red previously 
- 1h and all are perma loading
<img width="1639" alt="image" src="https://github.com/user-attachments/assets/45d660c3-ee61-4f00-9c3e-177d1936e0dd">
<img width="1661" alt="image" src="https://github.com/user-attachments/assets/0c216af5-94a8-4bd4-8eeb-6bf7ef26b3a7">