fix: limit order custom limit price state lost
shapeshift/web pull request #8299
Opened 2024-12-06 02:18 UTC by woodenfurniture

## Description

## Issue (if applicable)

closes #

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

### Engineering

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

2024-12-06 02:38 UTC, woodenfurniture commented on src/state/slices/tradeInputSlice/tradeInputSlice.ts
> +  }),
This is why spot trades should be safe - no real change.

2024-12-06 13:20 UTC, gomesalexandre commented on src/state/slices/limitOrderInputSlice/limitOrderInputSlice.ts
> +  }),
💜

2024-12-06 13:35 UTC, gomesalexandre requested changes
E2E tested locally, LGTM minus akschual price still resetting

- Limit slice state does not leak into swapper and swapper is happy after using limit functionality ✅ 

https://jam.dev/c/e774c8ea-ce6f-4041-8076-b184608fe169

- Custom sell amount is not lost ✅ 
- Pair selection is not lost ✅ 
- Selected price option (market/percentage is not lost) ✅ 
- Actual price resets to default 🚫 i.e regardless of whether market/percentage/custom is used as a price, the actual price always reverts to default

https://jam.dev/c/11ec50fa-4b80-4168-ac29-0b3715d7bbff

2024-12-09 10:56 UTC, gomesalexandre approved these changes
Retested locally, LGTM 🎈 

https://jam.dev/c/a16f02ef-053d-4a69-bf9f-f5f451dbd64d

2024-12-09 11:05 UTC, merged