feat: handle not/enough fee asset balance for network fees at final trade quote time
shapeshift/web pull request #8305
Opened 2024-12-06 14:17 UTC by gomesalexandre

## Description

Does what it says on the box - this ensures that users aren't able to execute (and either end up with estimate failures if using native, or being stuck at signing time if using e.g MM) trades without enough balance for gas.

Note, this isn't specific to Portals only: 
- as we refetch network fees at interval, this will apply to other swappers too
- for any swapper currently, this will also work with any swapper if you fund/drain native asset from addy during the swap

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/8268

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

Low, ensure you don't see this when you shouldn't

## Testing

- For Portals swaps, not enough balance should be caught and the button should be disabled, in error state. Funding your account with enough native asset should make the button green (blue) again
- For other swappers, you can also test this by

### Engineering

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

- Enough asset balance is happy

- Not enough asset balance is happy

- Draining native asset makes button go sad

- Funding native asset makes button go happy

2024-12-06 14:18 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
> +        asset: feeAsset!.symbol,
Actually defined if we end up here

2024-12-08 21:29 UTC, woodenfurniture approved these changes

2024-12-08 21:30 UTC, woodenfurniture requested changes
Requesting changes to revok accidental approval.

2024-12-08 21:34 UTC, woodenfurniture approved these changes
First pas, looking good. Needs runtime testing (to follow)

2024-12-08 21:34 UTC, woodenfurniture commented on src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
> +  )
Try it, you'll like it :P

```suggestion
  const feeAsset = useSelectorWithArgs(selectFeeAssetById, orderToCancel?.sellAssetId ?? '')
```

2024-12-08 21:34 UTC, woodenfurniture commented on src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
> +  )
May as well try to suggest it

```suggestion
  const feeAssetBalance = useSelectorWithArgs(selectPortfolioCryptoBalanceBaseUnitByFilter, feeAssetBalanceFilter)
```

2024-12-08 22:43 UTC, woodenfurniture requested changes
# Testing notes

❌ Does not appear to be taking the gas fee into account when doing a ETH -> FOX trade on ethereum:

https://jam.dev/c/c86fe6b6-ae5a-44fd-bb1e-79bd5e62688f

MM is catching this, which confirms the lack of balance for gas:

<img src="https://github.com/user-attachments/assets/0c35b7c9-c4be-4dc9-8c9e-0a7588bff354" width="200">

2024-12-09 01:13 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
> +  )
hell yeah 2751c96d3a

2024-12-09 01:13 UTC, gomesalexandre commented on src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
> +  )
hell yeah 2751c96d3a

2024-12-09 01:13 UTC, gomesalexandre commented
> ❌ Does not appear to be taking the gas fee into account when doing a ETH -> FOX trade on ethereum:

Very nice catch ser, we indeed need to check for the Tx value as well in the case of native sells 🧠 286d25dacae8d1ad3d7b620649d73a756067fe32
https://jam.dev/c/79d024d3-8d12-45af-aa5a-6aafe1310f28

2024-12-10 20:39 UTC, woodenfurniture approved these changes
Retested, native balance checks are worky again 🎉

2024-12-11 03:14 UTC, merged