feat: adjust fiat text size to avoid clipping in Trade modal
shapeshift/web pull request #836
Opened 2022-01-21 15:56 UTC by helr441

## Description

Adjust fiat text size to avoid clipping in Trade modal.

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (~Breaking~/Non-breaking Change)

## Issue (if applicable)

Closes #709.

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. Enter a large number in the ETH like 50,000 (depends on your locale) and wait for fiat rates to be fetched, and once fetched, see that fiat value displayed does not get clipped.

## Screenshots (if applicable)

2022-01-21 23:02 UTC, cjthompson commented on src/components/FiatInput/useFontSizeInPx.ts
> +    setTextSizeInPx(parseInt(match![0]))
Why not just use `calc()` CSS function? this seems heavy handed and I feel there must be a way to accomplish this with just CSS.

2022-01-21 23:05 UTC, cjthompson requested changes
There must be a simpler way to do this

2022-01-21 23:05 UTC, cjthompson commented on src/components/FiatInput/useFontSizeInPx.ts
> +    setTextSizeInPx(parseInt(match![0]))
https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()

2022-01-22 02:05 UTC, helr441 commented on src/components/FiatInput/useFontSizeInPx.ts
> +    setTextSizeInPx(parseInt(match![0]))
Thanks for pointing `clamp()` my way. I think some amount of calculation is also needed to arrive at the font sizes in the arguments of `clamp()`, specifically as the 3rd/max font size. I just read [Font scaling based on width of container on Stack Overflow](https://stackoverflow.com/questions/16056591/font-scaling-based-on-width-of-container) and [Fitting Text to a Container on CSS-Tricks](https://css-tricks.com/fitting-text-to-a-container/). I quite like the svg approach, which doesn't need any JavaScript/calculation.

2022-01-24 16:11 UTC, helr441 commented on src/components/FiatInput/useFontSizeInPx.ts
> +    setTextSizeInPx(parseInt(match![0]))
I realised SVG approach won't work, as this an `<Input>` that accepts user input.

2022-01-24 16:14 UTC, helr441 commented
I realised my previous work only targetted FiatInput above the `lg` (992px) breakpoint, and doesn't work well when below that. I've pushed something that handles this using `clamp()` referencing [this CSS-tricks article](https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/) for arriving at the expression.

2022-01-24 19:34 UTC, cjthompson commented
@0xdef1cafe - what do you think? I'd prefer some mix of `calc/clamp` in CSS, but I'm not a CSS expert.

2022-01-24 19:44 UTC, cjthompson commented
Can you post a side-by-side of what it looks like now vs your changes, for my reference?

2022-01-24 22:52 UTC, helr441 commented
Here's the previous diff: https://github.com/helr441/shapeshift-web/compare/58c853e...feat/font-clip-v1 (I tried [generating a diff between them](https://github.com/helr441/shapeshift-web/compare/feat/font-clip-v1...feat/font-clip) directly but it's output is not indicative of what changed between the now vs my initial PR)

2022-01-25 17:59 UTC, 0xean commented
Pulled this down and tested locally, it is working as expected.

New:
![Screen Shot 2022-01-25 at 10 55 12 AM](https://user-images.githubusercontent.com/15096737/151032276-cdc714ef-a4cb-41d1-85cf-802f8b48d59c.png)

Old:
![Screen Shot 2022-01-25 at 10 58 39 AM](https://user-images.githubusercontent.com/15096737/151032765-8111ec98-a6aa-4e4f-b7b6-ce084e629008.png)

I am inclined to merge this, we have spent a fair amount of time discussing the implementation for a relatively trivial feature.  If it can be improved in the future, great, but for now this should solve the problem and doesn't lock us in to anything long term.

2022-01-25 18:00 UTC, 0xean approved these changes

2022-01-25 18:31 UTC, cjthompson approved these changes

2022-01-25 19:22 UTC, merged

2022-01-25 19:26 UTC, 0xean commented
@helr441 - thanks for taking a pass at this. bounty payment + tip is pending.