fix: remove connect wallet page
shapeshift/web pull request #8446
Opened 2024-12-30 16:22 UTC by NeOMakinG

## Description

Now that this page is not used anymore, we can remove it

## Issue (if applicable)

closes #8163

## Risk
Low

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
- Play with the app disconnected, try to disconnect on specific pages such as wallet
I think we shouldn't block this PR if we discover some disconnected wallet wrong behavior as this PR is absolutely related to removing the dead code 

### Engineering
na

### Operations
n/a
- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
https://jam.dev/c/c6fd3848-f219-4a75-958f-43c54f7e4fd8

2025-01-01 21:47 UTC, woodenfurniture requested changes
Found some more stuff to kill :D

2025-01-01 21:47 UTC, woodenfurniture commented on src/Routes/Routes.tsx
> -      </Route>
[blocking]: Now this is gone we can also remove all other references to it

<img src="https://github.com/user-attachments/assets/7bb58cef-e47b-4662-a9c8-26af8303dfd1" width="200">

2025-01-01 21:47 UTC, woodenfurniture commented on src/assets/translations/en/main.json
>    "connectWalletPage": {
[preferably blocking]: `src/pages/ConnectWallet/MobileConnect.tsx` is not used anywhere, so we can delete that too, meaning this whole section can also go 🎉

2025-01-01 21:47 UTC, woodenfurniture commented on src/pages/ConnectWallet/ConnectWallet.tsx
> -export const ConnectWallet = () => {
🎉

2025-01-02 08:05 UTC, NeOMakinG commented on src/Routes/Routes.tsx
> -      </Route>
Added it back as `MobileConnect` and `/connect-mobile-wallet` as it's not very mobile specific, in [48e5381](https://github.com/shapeshift/web/pull/8446/commits/48e5381bdda5c477bb2509bc61f4b8dd175533a9)

2025-01-02 08:05 UTC, NeOMakinG commented on src/assets/translations/en/main.json
>    "connectWalletPage": {
It was a mistake, mobile should absolutely use this page, killing the splace screen on mobile is not a today thing 

Added this page back in [48e5381](https://github.com/shapeshift/web/pull/8446/commits/48e5381bdda5c477bb2509bc61f4b8dd175533a9)

2025-01-03 03:36 UTC, woodenfurniture approved these changes
Lets get this in!

2025-01-03 03:36 UTC, merged

2025-01-03 06:44 UTC, gomesalexandre commented
👋🏽