feature : Gem integration draft PR
shapeshift/web pull request #897
Opened 2022-02-02 04:50 UTC by sivaganeshan

## Description

Please describe your changes

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. etc...

## Screenshots (if applicable)

2022-02-02 17:20 UTC, 0xdef1cafe requested changes
hey @sivaganeshan thanks for the PR, this is a good first pass. i've left a bunch of comments to be addressed.

can you please run `yarn lint:fix` to get things formatted nicely? you can also configure your editor to respect the `.eslintrc` file in the root of the repo so it automatically formats on save.

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +        await fetch('https://api.gem.co/institutions/wyre/supported_currencies')
env var please

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +      throw 'Unknown error detedcted while fetching wyre supported currencies'
typo in error message, plus same comments as above

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +  const filterAndMerge = (arr1, arr2, key, filter) => {
please wrap this in `useMemo` to avoid rerenders

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +                            Buy or sell Crypto with Gem
translations

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +                                SELL
translations

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +                            Coming soon ...
translations - @SS-FOX-McCloud do we want this whole coming soon for onjuno?

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                            Select an assest to buy
translations

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                                        src={`https://gem-widgets-assets.s3-us-west-2.amazonaws.com/currencies/crypto/${buyCoin.ticker.toLowerCase()}.svg`}
env vars

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                        <Button>Continue</Button>
translations

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                        <Button>Cancel</Button>
translations

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                        <Button>Continue</Button>
translations

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                        <Button>Cancel</Button>
translations

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                      marginTop={'15%'}
i think we have enums for these margin sizes defined so we're consistent with our styles everywhere

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +export default function GemBuySell() {
please avoid default exports

2022-02-02 17:20 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +    let filteredResults = []
please use a reduce here rather than mutating

2022-02-02 18:08 UTC, sivaganeshan commented
will work on the changes and update the PR

2022-02-02 19:55 UTC, 0xdef1cafe commented
additionally, @sivaganeshan can you please fill out the PR template, including some screenshots?

2022-02-03 21:51 UTC, 0xdef1cafe commented
hey @sivaganeshan - quite a few unresolved comments. are you able to resolve the rest please?

2022-02-04 17:19 UTC, sivaganeshan commented
> 0xdef1cafe

working on the same

2022-02-05 23:32 UTC, 0xdef1cafe commented
> > 0xdef1cafe
> 
> working on the same

thanks @sivaganeshan - do you have an estimated completion date for this PR?

2022-02-07 15:52 UTC, sivaganeshan commented
> > > 0xdef1cafe
> > 
> > 
> > working on the same
> 
> thanks @sivaganeshan - do you have an estimated completion date for this PR?

Hi  @0xdef1cafe ,  I will be finishing all the review comments by tomorrow, and the gem parameters formation is still pending from me to work on.  Required gem sandbox parameters to work on the same

2022-02-09 19:13 UTC, 0xdef1cafe commented
hey @sivaganeshan - thanks for the contribution but as discussed with josh in discord we are going to assign this to another contributor at this point. please speak with @0xean on or after 2/14 with respect to compensation for this bounty.

2022-02-09 19:13 UTC, closed without merging

2022-02-21 20:56 UTC, 0xean commented
ref: #847