Draft
shapeshift/web pull request #987
Opened 2022-02-09 19:27 UTC by StephenMRicks85

## Description

Please describe your changes

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. etc...

## Screenshots (if applicable)

2022-02-09 19:29 UTC, 0xdef1cafe commented on headers.js
> +    // @gem(onramp) to get coinify supported currencies
plz refer to the gem SDK URL here, the @ convention was related to the npm package names

2022-02-09 19:46 UTC, 0xdef1cafe requested changes
left a bunch of comments but it was starting to get repetitive, please let me know if you want more or get where i'm going with this

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/Routes/helpers.ts
> +  disableHeaderIcon?: boolean
please remove this

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/assets/translations/messages-en.json
> +      "titleMessage": "ShapeShift has Partnered with several fiat ramp providers for buying and selling cryptocurrencies.",
```suggestion
      "titleMessage": "ShapeShift has partnered with several fiat ramp providers for buying and selling cryptocurrencies.",
```

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/assets/translations/messages-en.json
> +      "comingSoon": "Coming soon ...",
```suggestion
      "comingSoon": "Coming soon...",
```

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/assets/translations/messages-en.json
> +      "selectAnAssestToSell": "Select an assest to buy",
```suggestion
      "assetBuyMessage": "Asset to Buy",
      "selectAnAssetToBuy": "Select an asset to buy",
      "continue": "Continue",
      "cancel": "Cancel",
      "assetSellMessage": "Asset to Sell",
      "selectAnAssetToSell": "Select an asset to buy",
```

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/components/Layout/Header/NavBar/BuySell.tsx
> +  const [isLargerThan765] = useMediaQuery('(min-width: 765px)')
@reallybeard will defer to you here

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/components/Layout/Header/NavBar/BuySell.tsx
> +      {isLargerThan765 && (
if we're doing this media query thing do this in separate return statements rather than nesting

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/components/Layout/Header/NavBar/NavBar.tsx
> +        .filter(route => !route.disableHeaderIcon)
remove please

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +  const [isLargerThan550] = useMediaQuery('(min-width: 550px)')
@reallybeard thoughts?

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +    } catch (ex: any) {
```suggestion
    } catch (e: unknown) {
```

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +      let coinifyResponse = await (
please do this across two lines rather than jested awaits, just return the last one, don't let and assign

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +      let wyreResponse = await (await fetch(getConfig().REACT_APP_GEM_WYRE_SUPPORTED_COINS)).json()
same comment above

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +  const buyFilter = (arg: { transaction_direction: string }) =>
this type is used twice and should be defined separately and ideally picked from a gem exported type

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +    arg.transaction_direction === 'bank_blockchain' ||
`transaction_direction.endsWith('blockchain')`

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +  const ridirectToGem = () => {
one line this and fix typo

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
remove this and inject the dep it won't change

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +      console.error(e)
```suggestion
      console.error('error fetching gem supported coins:', e)
```

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +                      }}
```suggestion
                      onClick={redirectToGem}
```

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +              maxWidth={isLargerThan550 ? '70%' : '120%'}
@reallybeard ?

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +            transform={'translate(-35%,-50%)'}
@reallybeard

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +  const filterAndMerge = useMemo(
please rewrite this whole thing

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +                      }}
wait, what the hell is even going on here? don't do this at all

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +  const [supportedSellCoins, setSupportedSellCoins] = useState<any[]>([])
type these properly, rename first as `supportedBuyCoins`

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +  const [redirectToGem, setRedirectToGem] = useState(false)
delete this

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/BuySell.tsx
> +                      minWidth={isLargerThan550 ? '120%' : '100%'}
i'm going to stop commenting on each of these, but no hardcoded values, we have set sizes/breakpoints and should be using those, @reallybeard can advise

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +  const location: any = useLocation()
type and parse and do this nicer. is the coin list from the state the only way to get this? seems off.

2022-02-09 19:46 UTC, 0xdef1cafe commented on src/pages/BuySell/GemBuySell.tsx
> +                              return (
don't do this

2022-02-14 17:42 UTC, 0xdef1cafe commented
hey @StephenMRicks85 - could we please get a status update on this PR and an ETA for completion?

feel free to push up any WIP commits to this branch or open a new PR if you're taking a completely new implementation as we discussed on discord.

2022-02-21 20:55 UTC, 0xean commented
closing this PR.

Another bounty hunter is slated to pick up #847 so will link this PR if useful.

2022-02-21 20:55 UTC, closed without merging